// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgr/v1/micro/usermgr.proto

package usermgr

import (
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// cluster provider status
type ClusterProviderStatus int32

const (
	ClusterProviderStatus_NOT_PROVIDER ClusterProviderStatus = 0
	ClusterProviderStatus_PENDING      ClusterProviderStatus = 1
	ClusterProviderStatus_PROVIDER     ClusterProviderStatus = 2
)

var ClusterProviderStatus_name = map[int32]string{
	0: "NOT_PROVIDER",
	1: "PENDING",
	2: "PROVIDER",
}

var ClusterProviderStatus_value = map[string]int32{
	"NOT_PROVIDER": 0,
	"PENDING":      1,
	"PROVIDER":     2,
}

func (x ClusterProviderStatus) String() string {
	return proto.EnumName(ClusterProviderStatus_name, int32(x))
}

func (ClusterProviderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{0}
}

type UserStatus int32

const (
	UserStatus_CONFIRMING  UserStatus = 0
	UserStatus_CONFIRMED   UserStatus = 1
	UserStatus_DEACTIVATED UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "CONFIRMING",
	1: "CONFIRMED",
	2: "DEACTIVATED",
}

var UserStatus_value = map[string]int32{
	"CONFIRMING":  0,
	"CONFIRMED":   1,
	"DEACTIVATED": 2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{1}
}

type FetchAccountsType int32

const (
	FetchAccountsType_FetchAccountsUnknown        FetchAccountsType = 0
	FetchAccountsType_FetchAccountsEthereum       FetchAccountsType = 1
	FetchAccountsType_FetchAccountsDCCNTendermint FetchAccountsType = 2
	FetchAccountsType_FetchAccountsBinance        FetchAccountsType = 3
)

var FetchAccountsType_name = map[int32]string{
	0: "FetchAccountsUnknown",
	1: "FetchAccountsEthereum",
	2: "FetchAccountsDCCNTendermint",
	3: "FetchAccountsBinance",
}

var FetchAccountsType_value = map[string]int32{
	"FetchAccountsUnknown":        0,
	"FetchAccountsEthereum":       1,
	"FetchAccountsDCCNTendermint": 2,
	"FetchAccountsBinance":        3,
}

func (x FetchAccountsType) String() string {
	return proto.EnumName(FetchAccountsType_name, int32(x))
}

func (FetchAccountsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{2}
}

type ClusterProviderApplyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	JobTitle             string   `protobuf:"bytes,4,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Company              string   `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	Country              string   `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	TimeZone             int32    `protobuf:"varint,8,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterProviderApplyRequest) Reset()         { *m = ClusterProviderApplyRequest{} }
func (m *ClusterProviderApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterProviderApplyRequest) ProtoMessage()    {}
func (*ClusterProviderApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{0}
}

func (m *ClusterProviderApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProviderApplyRequest.Unmarshal(m, b)
}
func (m *ClusterProviderApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProviderApplyRequest.Marshal(b, m, deterministic)
}
func (m *ClusterProviderApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProviderApplyRequest.Merge(m, src)
}
func (m *ClusterProviderApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterProviderApplyRequest.Size(m)
}
func (m *ClusterProviderApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProviderApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProviderApplyRequest proto.InternalMessageInfo

func (m *ClusterProviderApplyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterProviderApplyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ClusterProviderApplyRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ClusterProviderApplyRequest) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *ClusterProviderApplyRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *ClusterProviderApplyRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ClusterProviderApplyRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ClusterProviderApplyRequest) GetTimeZone() int32 {
	if m != nil {
		return m.TimeZone
	}
	return 0
}

type SearchDepositRequest struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchDepositRequest) Reset()         { *m = SearchDepositRequest{} }
func (m *SearchDepositRequest) String() string { return proto.CompactTextString(m) }
func (*SearchDepositRequest) ProtoMessage()    {}
func (*SearchDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{1}
}

func (m *SearchDepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDepositRequest.Unmarshal(m, b)
}
func (m *SearchDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDepositRequest.Marshal(b, m, deterministic)
}
func (m *SearchDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDepositRequest.Merge(m, src)
}
func (m *SearchDepositRequest) XXX_Size() int {
	return xxx_messageInfo_SearchDepositRequest.Size(m)
}
func (m *SearchDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDepositRequest proto.InternalMessageInfo

func (m *SearchDepositRequest) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *SearchDepositRequest) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

type GenerateAddressRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Purpose              string   `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressRequest) Reset()         { *m = GenerateAddressRequest{} }
func (m *GenerateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressRequest) ProtoMessage()    {}
func (*GenerateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{2}
}

func (m *GenerateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressRequest.Unmarshal(m, b)
}
func (m *GenerateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressRequest.Marshal(b, m, deterministic)
}
func (m *GenerateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressRequest.Merge(m, src)
}
func (m *GenerateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressRequest.Size(m)
}
func (m *GenerateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressRequest proto.InternalMessageInfo

func (m *GenerateAddressRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GenerateAddressRequest) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

type GenerateAddressResponse struct {
	Typeaddress          string   `protobuf:"bytes,1,opt,name=typeaddress,proto3" json:"typeaddress,omitempty"`
	Purposeaddress       string   `protobuf:"bytes,2,opt,name=purposeaddress,proto3" json:"purposeaddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressResponse) Reset()         { *m = GenerateAddressResponse{} }
func (m *GenerateAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressResponse) ProtoMessage()    {}
func (*GenerateAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{3}
}

func (m *GenerateAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressResponse.Unmarshal(m, b)
}
func (m *GenerateAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressResponse.Marshal(b, m, deterministic)
}
func (m *GenerateAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressResponse.Merge(m, src)
}
func (m *GenerateAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressResponse.Size(m)
}
func (m *GenerateAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressResponse proto.InternalMessageInfo

func (m *GenerateAddressResponse) GetTypeaddress() string {
	if m != nil {
		return m.Typeaddress
	}
	return ""
}

func (m *GenerateAddressResponse) GetPurposeaddress() string {
	if m != nil {
		return m.Purposeaddress
	}
	return ""
}

type DepositHistoryResponse struct {
	Deposits             []*common.Deposit `protobuf:"bytes,1,rep,name=deposits,proto3" json:"deposits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DepositHistoryResponse) Reset()         { *m = DepositHistoryResponse{} }
func (m *DepositHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*DepositHistoryResponse) ProtoMessage()    {}
func (*DepositHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{4}
}

func (m *DepositHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositHistoryResponse.Unmarshal(m, b)
}
func (m *DepositHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositHistoryResponse.Marshal(b, m, deterministic)
}
func (m *DepositHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositHistoryResponse.Merge(m, src)
}
func (m *DepositHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_DepositHistoryResponse.Size(m)
}
func (m *DepositHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositHistoryResponse proto.InternalMessageInfo

func (m *DepositHistoryResponse) GetDeposits() []*common.Deposit {
	if m != nil {
		return m.Deposits
	}
	return nil
}

type User struct {
	// uuid
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// email user's email, unique.
	Email                string          `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status               UserStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=usermgr.UserStatus" json:"status,omitempty"`
	Attributes           *UserAttributes `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_CONFIRMING
}

func (m *User) GetAttributes() *UserAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type UserAttribute struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*UserAttribute_IntValue
	//	*UserAttribute_DoubleValue
	//	*UserAttribute_StringValue
	//	*UserAttribute_BoolValue
	Value                isUserAttribute_Value `protobuf_oneof:"value"`
	Muted                bool                  `protobuf:"varint,7,opt,name=muted,proto3" json:"muted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserAttribute) Reset()         { *m = UserAttribute{} }
func (m *UserAttribute) String() string { return proto.CompactTextString(m) }
func (*UserAttribute) ProtoMessage()    {}
func (*UserAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{6}
}

func (m *UserAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAttribute.Unmarshal(m, b)
}
func (m *UserAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAttribute.Marshal(b, m, deterministic)
}
func (m *UserAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAttribute.Merge(m, src)
}
func (m *UserAttribute) XXX_Size() int {
	return xxx_messageInfo_UserAttribute.Size(m)
}
func (m *UserAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_UserAttribute proto.InternalMessageInfo

func (m *UserAttribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isUserAttribute_Value interface {
	isUserAttribute_Value()
}

type UserAttribute_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type UserAttribute_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type UserAttribute_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type UserAttribute_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*UserAttribute_IntValue) isUserAttribute_Value() {}

func (*UserAttribute_DoubleValue) isUserAttribute_Value() {}

func (*UserAttribute_StringValue) isUserAttribute_Value() {}

func (*UserAttribute_BoolValue) isUserAttribute_Value() {}

func (m *UserAttribute) GetValue() isUserAttribute_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UserAttribute) GetIntValue() int64 {
	if x, ok := m.GetValue().(*UserAttribute_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *UserAttribute) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*UserAttribute_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *UserAttribute) GetStringValue() string {
	if x, ok := m.GetValue().(*UserAttribute_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *UserAttribute) GetBoolValue() bool {
	if x, ok := m.GetValue().(*UserAttribute_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *UserAttribute) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserAttribute) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserAttribute_IntValue)(nil),
		(*UserAttribute_DoubleValue)(nil),
		(*UserAttribute_StringValue)(nil),
		(*UserAttribute_BoolValue)(nil),
	}
}

type UserAttributes struct {
	// name of a user
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// public key of tendermint wallet
	PubKey                string                `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	CreationDate          uint64                `protobuf:"varint,3,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate      uint64                `protobuf:"varint,4,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	ExtraFields           []*UserAttribute      `protobuf:"bytes,5,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	ClusterProviderStatus ClusterProviderStatus `protobuf:"varint,6,opt,name=cluster_provider_status,json=clusterProviderStatus,proto3,enum=usermgr.ClusterProviderStatus" json:"cluster_provider_status,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *UserAttributes) Reset()         { *m = UserAttributes{} }
func (m *UserAttributes) String() string { return proto.CompactTextString(m) }
func (*UserAttributes) ProtoMessage()    {}
func (*UserAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{7}
}

func (m *UserAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAttributes.Unmarshal(m, b)
}
func (m *UserAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAttributes.Marshal(b, m, deterministic)
}
func (m *UserAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAttributes.Merge(m, src)
}
func (m *UserAttributes) XXX_Size() int {
	return xxx_messageInfo_UserAttributes.Size(m)
}
func (m *UserAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_UserAttributes proto.InternalMessageInfo

func (m *UserAttributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAttributes) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *UserAttributes) GetCreationDate() uint64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *UserAttributes) GetLastModifiedDate() uint64 {
	if m != nil {
		return m.LastModifiedDate
	}
	return 0
}

func (m *UserAttributes) GetExtraFields() []*UserAttribute {
	if m != nil {
		return m.ExtraFields
	}
	return nil
}

func (m *UserAttributes) GetClusterProviderStatus() ClusterProviderStatus {
	if m != nil {
		return m.ClusterProviderStatus
	}
	return ClusterProviderStatus_NOT_PROVIDER
}

type RegisterRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{8}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{9}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AuthenticationResult *AuthenticationResult `protobuf:"bytes,1,opt,name=authentication_result,json=authenticationResult,proto3" json:"authentication_result,omitempty"`
	User                 *User                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{10}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAuthenticationResult() *AuthenticationResult {
	if m != nil {
		return m.AuthenticationResult
	}
	return nil
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AuthenticationResult struct {
	Expiration           uint64   `protobuf:"varint,1,opt,name=expiration,proto3" json:"expiration,omitempty"`
	IssuedAt             uint64   `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResult) Reset()         { *m = AuthenticationResult{} }
func (m *AuthenticationResult) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResult) ProtoMessage()    {}
func (*AuthenticationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{11}
}

func (m *AuthenticationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResult.Unmarshal(m, b)
}
func (m *AuthenticationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResult.Marshal(b, m, deterministic)
}
func (m *AuthenticationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResult.Merge(m, src)
}
func (m *AuthenticationResult) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResult.Size(m)
}
func (m *AuthenticationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResult.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResult proto.InternalMessageInfo

func (m *AuthenticationResult) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *AuthenticationResult) GetIssuedAt() uint64 {
	if m != nil {
		return m.IssuedAt
	}
	return 0
}

func (m *AuthenticationResult) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthenticationResult) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshToken struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{12}
}

func (m *RefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshToken.Unmarshal(m, b)
}
func (m *RefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshToken.Marshal(b, m, deterministic)
}
func (m *RefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshToken.Merge(m, src)
}
func (m *RefreshToken) XXX_Size() int {
	return xxx_messageInfo_RefreshToken.Size(m)
}
func (m *RefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshToken proto.InternalMessageInfo

func (m *RefreshToken) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ConfirmRegistrationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRegistrationRequest) Reset()         { *m = ConfirmRegistrationRequest{} }
func (m *ConfirmRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmRegistrationRequest) ProtoMessage()    {}
func (*ConfirmRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{13}
}

func (m *ConfirmRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRegistrationRequest.Unmarshal(m, b)
}
func (m *ConfirmRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRegistrationRequest.Merge(m, src)
}
func (m *ConfirmRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmRegistrationRequest.Size(m)
}
func (m *ConfirmRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRegistrationRequest proto.InternalMessageInfo

func (m *ConfirmRegistrationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmRegistrationRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{14}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ConfirmPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPasswordRequest) Reset()         { *m = ConfirmPasswordRequest{} }
func (m *ConfirmPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmPasswordRequest) ProtoMessage()    {}
func (*ConfirmPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{15}
}

func (m *ConfirmPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPasswordRequest.Unmarshal(m, b)
}
func (m *ConfirmPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPasswordRequest.Merge(m, src)
}
func (m *ConfirmPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmPasswordRequest.Size(m)
}
func (m *ConfirmPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPasswordRequest proto.InternalMessageInfo

func (m *ConfirmPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmPasswordRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{16}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangeEmailRequest struct {
	NewEmail             string   `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEmailRequest) Reset()         { *m = ChangeEmailRequest{} }
func (m *ChangeEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEmailRequest) ProtoMessage()    {}
func (*ChangeEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{17}
}

func (m *ChangeEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEmailRequest.Unmarshal(m, b)
}
func (m *ChangeEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEmailRequest.Marshal(b, m, deterministic)
}
func (m *ChangeEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEmailRequest.Merge(m, src)
}
func (m *ChangeEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEmailRequest.Size(m)
}
func (m *ChangeEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEmailRequest proto.InternalMessageInfo

func (m *ChangeEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type UpdateAttributesRequest struct {
	UserAttributes       []*UserAttribute `protobuf:"bytes,1,rep,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateAttributesRequest) Reset()         { *m = UpdateAttributesRequest{} }
func (m *UpdateAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAttributesRequest) ProtoMessage()    {}
func (*UpdateAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{18}
}

func (m *UpdateAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAttributesRequest.Unmarshal(m, b)
}
func (m *UpdateAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAttributesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAttributesRequest.Merge(m, src)
}
func (m *UpdateAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAttributesRequest.Size(m)
}
func (m *UpdateAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAttributesRequest proto.InternalMessageInfo

func (m *UpdateAttributesRequest) GetUserAttributes() []*UserAttribute {
	if m != nil {
		return m.UserAttributes
	}
	return nil
}

type ConfirmEmailRequest struct {
	ConfirmationCode     string   `protobuf:"bytes,1,opt,name=ConfirmationCode,proto3" json:"ConfirmationCode,omitempty"`
	OldEmail             string   `protobuf:"bytes,2,opt,name=OldEmail,proto3" json:"OldEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailRequest) Reset()         { *m = ConfirmEmailRequest{} }
func (m *ConfirmEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailRequest) ProtoMessage()    {}
func (*ConfirmEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{19}
}

func (m *ConfirmEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailRequest.Merge(m, src)
}
func (m *ConfirmEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailRequest.Size(m)
}
func (m *ConfirmEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailRequest proto.InternalMessageInfo

func (m *ConfirmEmailRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmEmailRequest) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

type FetchAccountsRequest struct {
	AccountType          FetchAccountsType `protobuf:"varint,1,opt,name=accountType,proto3,enum=usermgr.FetchAccountsType" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FetchAccountsRequest) Reset()         { *m = FetchAccountsRequest{} }
func (m *FetchAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*FetchAccountsRequest) ProtoMessage()    {}
func (*FetchAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{20}
}

func (m *FetchAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchAccountsRequest.Unmarshal(m, b)
}
func (m *FetchAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchAccountsRequest.Marshal(b, m, deterministic)
}
func (m *FetchAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchAccountsRequest.Merge(m, src)
}
func (m *FetchAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_FetchAccountsRequest.Size(m)
}
func (m *FetchAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchAccountsRequest proto.InternalMessageInfo

func (m *FetchAccountsRequest) GetAccountType() FetchAccountsType {
	if m != nil {
		return m.AccountType
	}
	return FetchAccountsType_FetchAccountsUnknown
}

type FetchAccountsResponse struct {
	Address              []string `protobuf:"bytes,1,rep,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchAccountsResponse) Reset()         { *m = FetchAccountsResponse{} }
func (m *FetchAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*FetchAccountsResponse) ProtoMessage()    {}
func (*FetchAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{21}
}

func (m *FetchAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchAccountsResponse.Unmarshal(m, b)
}
func (m *FetchAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchAccountsResponse.Marshal(b, m, deterministic)
}
func (m *FetchAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchAccountsResponse.Merge(m, src)
}
func (m *FetchAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_FetchAccountsResponse.Size(m)
}
func (m *FetchAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchAccountsResponse proto.InternalMessageInfo

func (m *FetchAccountsResponse) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterEnum("usermgr.ClusterProviderStatus", ClusterProviderStatus_name, ClusterProviderStatus_value)
	proto.RegisterEnum("usermgr.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterEnum("usermgr.FetchAccountsType", FetchAccountsType_name, FetchAccountsType_value)
	proto.RegisterType((*ClusterProviderApplyRequest)(nil), "usermgr.ClusterProviderApplyRequest")
	proto.RegisterType((*SearchDepositRequest)(nil), "usermgr.SearchDepositRequest")
	proto.RegisterType((*GenerateAddressRequest)(nil), "usermgr.GenerateAddressRequest")
	proto.RegisterType((*GenerateAddressResponse)(nil), "usermgr.GenerateAddressResponse")
	proto.RegisterType((*DepositHistoryResponse)(nil), "usermgr.DepositHistoryResponse")
	proto.RegisterType((*User)(nil), "usermgr.User")
	proto.RegisterType((*UserAttribute)(nil), "usermgr.UserAttribute")
	proto.RegisterType((*UserAttributes)(nil), "usermgr.UserAttributes")
	proto.RegisterType((*RegisterRequest)(nil), "usermgr.RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "usermgr.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "usermgr.LoginResponse")
	proto.RegisterType((*AuthenticationResult)(nil), "usermgr.AuthenticationResult")
	proto.RegisterType((*RefreshToken)(nil), "usermgr.RefreshToken")
	proto.RegisterType((*ConfirmRegistrationRequest)(nil), "usermgr.ConfirmRegistrationRequest")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "usermgr.ForgotPasswordRequest")
	proto.RegisterType((*ConfirmPasswordRequest)(nil), "usermgr.ConfirmPasswordRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "usermgr.ChangePasswordRequest")
	proto.RegisterType((*ChangeEmailRequest)(nil), "usermgr.ChangeEmailRequest")
	proto.RegisterType((*UpdateAttributesRequest)(nil), "usermgr.UpdateAttributesRequest")
	proto.RegisterType((*ConfirmEmailRequest)(nil), "usermgr.ConfirmEmailRequest")
	proto.RegisterType((*FetchAccountsRequest)(nil), "usermgr.FetchAccountsRequest")
	proto.RegisterType((*FetchAccountsResponse)(nil), "usermgr.FetchAccountsResponse")
}

func init() { proto.RegisterFile("usermgr/v1/micro/usermgr.proto", fileDescriptor_07324a721ebdf9ff) }

var fileDescriptor_07324a721ebdf9ff = []byte{
	// 1543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x16, 0x65, 0xc9, 0x96, 0x47, 0xb2, 0xac, 0xac, 0x2d, 0x5b, 0x47, 0x3e, 0xb1, 0x1d, 0xe6,
	0xe0, 0x20, 0x70, 0x72, 0xec, 0x63, 0x07, 0x38, 0x3f, 0x68, 0x80, 0x54, 0x91, 0xe4, 0x1f, 0x24,
	0xb1, 0x5d, 0x46, 0x31, 0xd0, 0x00, 0x81, 0x40, 0x91, 0x6b, 0x99, 0x89, 0xc8, 0x65, 0x97, 0x4b,
	0x3b, 0xea, 0x45, 0x6f, 0x0a, 0xf4, 0xb2, 0x17, 0xbd, 0xed, 0x65, 0xdf, 0xa6, 0x2f, 0xd1, 0x57,
	0x29, 0xf6, 0x87, 0x34, 0x45, 0x51, 0x86, 0x7b, 0x25, 0xcd, 0xcc, 0x37, 0xb3, 0x33, 0xb3, 0xb3,
	0xdf, 0x72, 0x61, 0x33, 0x0c, 0x30, 0x75, 0x87, 0x74, 0xef, 0x7a, 0x7f, 0xcf, 0x75, 0x2c, 0x4a,
	0xf6, 0x94, 0x62, 0xd7, 0xa7, 0x84, 0x11, 0xb4, 0xa0, 0xc4, 0xe6, 0x8a, 0x45, 0x5c, 0x97, 0x78,
	0x7b, 0xf2, 0x47, 0x5a, 0x9b, 0x5b, 0x43, 0x42, 0x86, 0x23, 0xbc, 0x27, 0xa4, 0x41, 0x78, 0xb9,
	0xc7, 0x1c, 0x17, 0x07, 0xcc, 0x74, 0x7d, 0x09, 0xd0, 0xff, 0xd0, 0x60, 0xa3, 0x3d, 0x0a, 0x03,
	0x86, 0xe9, 0x39, 0x25, 0xd7, 0x8e, 0x8d, 0x69, 0xcb, 0xf7, 0x47, 0x63, 0x03, 0x7f, 0x17, 0xe2,
	0x80, 0x21, 0x04, 0x05, 0xcf, 0x74, 0x71, 0x43, 0xdb, 0xd6, 0x9e, 0x2c, 0x1a, 0xe2, 0x3f, 0x5a,
	0x85, 0x22, 0x76, 0x4d, 0x67, 0xd4, 0xc8, 0x0b, 0xa5, 0x14, 0xb8, 0xd6, 0xbf, 0x22, 0x1e, 0x6e,
	0xcc, 0x49, 0xad, 0x10, 0xd0, 0x06, 0x2c, 0x7e, 0x22, 0x83, 0x3e, 0x73, 0xd8, 0x08, 0x37, 0x0a,
	0xc2, 0x52, 0xfa, 0x44, 0x06, 0x3d, 0x2e, 0xa3, 0x06, 0x2c, 0x58, 0xc4, 0xf5, 0x4d, 0x6f, 0xdc,
	0x28, 0x0a, 0x53, 0x24, 0x4a, 0x4b, 0xe8, 0x31, 0x3a, 0x6e, 0xcc, 0x47, 0x16, 0x21, 0xf2, 0x84,
	0x2c, 0x87, 0x8d, 0x1b, 0x0b, 0x32, 0x21, 0xfe, 0x9f, 0x2f, 0xc2, 0xeb, 0xea, 0x7f, 0xcf, 0x97,
	0x2f, 0x6d, 0x6b, 0x4f, 0x8a, 0x46, 0x89, 0x2b, 0x3e, 0x10, 0x0f, 0xeb, 0xd7, 0xb0, 0xfa, 0x0e,
	0x9b, 0xd4, 0xba, 0xea, 0x60, 0x9f, 0x04, 0x0e, 0x8b, 0x2a, 0xfb, 0x37, 0x14, 0x03, 0x66, 0x52,
	0x26, 0x4a, 0x2b, 0x1f, 0x34, 0x77, 0x65, 0xab, 0x76, 0xa3, 0x56, 0xed, 0xf6, 0xa2, 0x56, 0x19,
	0x12, 0x88, 0x9e, 0xc1, 0x1c, 0xf6, 0x6c, 0x51, 0xf5, 0xdd, 0x78, 0x0e, 0xd3, 0x0f, 0x61, 0xed,
	0x08, 0x7b, 0x98, 0x9a, 0x0c, 0xb7, 0x6c, 0x9b, 0xe2, 0x20, 0x48, 0xf4, 0x94, 0x8d, 0xfd, 0xb8,
	0xa7, 0xfc, 0x3f, 0x2f, 0xd8, 0x0f, 0xa9, 0x4f, 0x02, 0xac, 0xba, 0x1a, 0x89, 0xba, 0x05, 0xeb,
	0x53, 0x71, 0x02, 0x9f, 0x78, 0x01, 0x46, 0xdb, 0x50, 0xe6, 0xce, 0xa6, 0x54, 0xab, 0x78, 0x49,
	0x15, 0xfa, 0x27, 0x54, 0x55, 0x9c, 0x08, 0x24, 0xa3, 0xa7, 0xb4, 0xfa, 0x6b, 0x58, 0x53, 0xed,
	0x39, 0x76, 0x02, 0x46, 0xe8, 0x38, 0x5e, 0x63, 0x1f, 0x4a, 0xb6, 0xb4, 0xf0, 0x05, 0xe6, 0x9e,
	0x94, 0x0f, 0xea, 0xbb, 0xc9, 0x11, 0xdb, 0x8d, 0xda, 0x1a, 0xc3, 0xf4, 0x5f, 0x34, 0x28, 0xbc,
	0x0f, 0x30, 0x45, 0x55, 0xc8, 0x3b, 0xb6, 0x4a, 0x2b, 0xef, 0xd8, 0x33, 0x06, 0xe7, 0x29, 0xcc,
	0x07, 0xcc, 0x64, 0x61, 0x20, 0x26, 0xa7, 0x7a, 0xb0, 0xb2, 0x1b, 0x4d, 0x38, 0x0f, 0xf2, 0x4e,
	0x98, 0x0c, 0x05, 0x41, 0xff, 0x05, 0x30, 0x19, 0xa3, 0xce, 0x20, 0x64, 0x38, 0x10, 0x03, 0x55,
	0x3e, 0x58, 0x9f, 0x70, 0x68, 0xc5, 0x66, 0x23, 0x01, 0xd5, 0x7f, 0xd7, 0x60, 0x69, 0xc2, 0x8c,
	0x6a, 0x30, 0xf7, 0x19, 0x8f, 0x55, 0x7a, 0xfc, 0x2f, 0x7a, 0x08, 0x8b, 0x8e, 0xc7, 0xfa, 0xd7,
	0xe6, 0x28, 0x94, 0xdb, 0x30, 0x77, 0x9c, 0x33, 0x4a, 0x8e, 0xc7, 0x2e, 0xb8, 0x06, 0x3d, 0x86,
	0x8a, 0x4d, 0xc2, 0xc1, 0x08, 0x2b, 0x04, 0x4f, 0x57, 0x3b, 0xce, 0x19, 0x65, 0xa9, 0x8d, 0x41,
	0x01, 0xa3, 0x8e, 0x37, 0x54, 0x20, 0x31, 0xf3, 0x1c, 0x24, 0xb5, 0x12, 0xb4, 0x05, 0x30, 0x20,
	0x64, 0xa4, 0x20, 0x7c, 0xf6, 0x4b, 0xc7, 0x39, 0x63, 0x91, 0xeb, 0x24, 0x60, 0x15, 0x8a, 0x6e,
	0xc8, 0xb0, 0x2d, 0xc6, 0xbc, 0x64, 0x48, 0xe1, 0xd5, 0x02, 0x14, 0x85, 0x87, 0xfe, 0x5b, 0x1e,
	0xaa, 0x93, 0xb5, 0x66, 0x1e, 0xd4, 0x75, 0x3e, 0x54, 0x83, 0x3e, 0xaf, 0x52, 0x76, 0x7c, 0xde,
	0x0f, 0x07, 0xaf, 0xf1, 0x18, 0x3d, 0x86, 0x25, 0x8b, 0x62, 0x93, 0x39, 0xc4, 0xeb, 0xdb, 0x26,
	0x93, 0xa5, 0x14, 0x8c, 0x4a, 0xa4, 0xec, 0x98, 0x0c, 0xa3, 0x67, 0x80, 0x46, 0x66, 0xc0, 0xfa,
	0x2e, 0xb1, 0x9d, 0x4b, 0x07, 0xdb, 0x12, 0x59, 0x10, 0xc8, 0x1a, 0xb7, 0xbc, 0x55, 0x06, 0x81,
	0xfe, 0x3f, 0x54, 0xf0, 0x17, 0x46, 0xcd, 0xfe, 0xa5, 0x83, 0x47, 0x76, 0xd0, 0x28, 0x8a, 0x59,
	0x59, 0xcb, 0xde, 0x1a, 0xa3, 0x2c, 0xb0, 0x87, 0x02, 0x8a, 0x2e, 0x60, 0xdd, 0x92, 0x14, 0xd4,
	0xf7, 0x15, 0x07, 0xf5, 0xd5, 0x44, 0xcc, 0x8b, 0x89, 0xd8, 0x8c, 0xa3, 0xa4, 0xa8, 0x4a, 0x0d,
	0x47, 0xdd, 0xca, 0x52, 0xeb, 0xe7, 0xb0, 0x6c, 0xe0, 0xa1, 0xc3, 0x2d, 0xd1, 0xd1, 0x7b, 0x04,
	0x05, 0x1e, 0x4a, 0x9d, 0xf9, 0xa5, 0x89, 0xec, 0x0c, 0x61, 0x42, 0x4d, 0x28, 0xf9, 0x66, 0x10,
	0xdc, 0x10, 0x6a, 0xab, 0xae, 0xc5, 0xb2, 0xfe, 0x35, 0x54, 0xde, 0x90, 0xa1, 0xe3, 0x45, 0xe1,
	0xe2, 0x81, 0xd6, 0x92, 0x03, 0x7d, 0x57, 0x84, 0x9f, 0x34, 0x58, 0x52, 0x21, 0xd4, 0x01, 0x33,
	0xa0, 0x6e, 0x86, 0xec, 0x0a, 0x7b, 0xcc, 0xb1, 0xe4, 0x8e, 0x50, 0x1c, 0x84, 0xa3, 0x88, 0x97,
	0x1e, 0xc6, 0x39, 0xb6, 0x26, 0x50, 0x86, 0x00, 0x19, 0xab, 0x66, 0x86, 0x36, 0x2e, 0x33, 0x3f,
	0xb3, 0x4c, 0xfd, 0x57, 0x0d, 0x56, 0xb3, 0x22, 0xa2, 0x4d, 0x00, 0xfc, 0xc5, 0x77, 0xa8, 0xd0,
	0x89, 0x24, 0x0a, 0x46, 0x42, 0xc3, 0xc9, 0xd6, 0x09, 0x82, 0x10, 0xdb, 0x7d, 0x93, 0x89, 0x05,
	0x0a, 0x46, 0x49, 0x2a, 0x5a, 0x7c, 0xe1, 0x8a, 0x69, 0x59, 0x38, 0x08, 0xfa, 0x8c, 0x7c, 0xc6,
	0x9e, 0xba, 0x0b, 0xca, 0x52, 0xd7, 0xe3, 0x2a, 0x3e, 0x7b, 0x14, 0x5f, 0x52, 0x1c, 0x5c, 0x29,
	0x8c, 0xbc, 0x15, 0x2a, 0x4a, 0x29, 0x40, 0xfa, 0x73, 0xa8, 0x18, 0x09, 0x79, 0xda, 0x49, 0xcb,
	0x70, 0xea, 0x43, 0xb3, 0x4d, 0xbc, 0x4b, 0x87, 0xba, 0x72, 0xdb, 0xa9, 0x2a, 0xeb, 0xae, 0xbd,
	0x7a, 0x0a, 0x0f, 0x2c, 0xe9, 0x23, 0x7b, 0x6f, 0x11, 0x3b, 0x62, 0xe0, 0x5a, 0xd2, 0xd0, 0x26,
	0x36, 0xd6, 0xff, 0x05, 0xf5, 0x43, 0x42, 0x87, 0x84, 0x9d, 0xab, 0xed, 0xbc, 0x33, 0xb6, 0xfe,
	0x03, 0xac, 0xa9, 0x7c, 0xee, 0x85, 0xff, 0x4b, 0xb9, 0xf0, 0x4e, 0x7b, 0xf8, 0xa6, 0x1f, 0x0f,
	0x9a, 0xea, 0xb4, 0x87, 0x6f, 0xa2, 0xc5, 0xf4, 0x8f, 0x50, 0x6f, 0x5f, 0x99, 0xde, 0x10, 0xa7,
	0x97, 0x7f, 0x04, 0x15, 0x32, 0xb2, 0x6f, 0x7d, 0xd5, 0xc5, 0x41, 0x46, 0x76, 0x84, 0x9c, 0x0a,
	0x9f, 0x9f, 0x0e, 0xbf, 0x0f, 0x48, 0x86, 0xef, 0xf2, 0xec, 0xa3, 0xd8, 0x1b, 0xb0, 0xc8, 0x1d,
	0x93, 0xe5, 0x95, 0x3c, 0x7c, 0x23, 0x30, 0xfa, 0x07, 0x58, 0x7f, 0xef, 0x73, 0x1a, 0x49, 0x90,
	0xb4, 0xf2, 0x7b, 0x09, 0xcb, 0x7c, 0x2e, 0xfb, 0x09, 0x76, 0xd7, 0xee, 0xa4, 0x90, 0x6a, 0x38,
	0x41, 0x80, 0xfa, 0x47, 0x58, 0x51, 0xdd, 0x9e, 0xc8, 0x67, 0x07, 0x6a, 0xed, 0x54, 0xef, 0x54,
	0x5a, 0x53, 0x7a, 0x7e, 0x70, 0xcf, 0x46, 0x76, 0x37, 0x71, 0x45, 0xc5, 0xb2, 0xde, 0x83, 0xd5,
	0x43, 0xcc, 0xac, 0xab, 0x96, 0x25, 0xbe, 0x44, 0xe2, 0xbc, 0x5f, 0x00, 0x9f, 0x6e, 0xae, 0xea,
	0x45, 0x77, 0x7a, 0xf5, 0xa0, 0x19, 0xe7, 0x3c, 0xe1, 0xc3, 0x11, 0x46, 0x12, 0xae, 0xef, 0x43,
	0x3d, 0x15, 0x55, 0xb1, 0x42, 0x03, 0x16, 0x5a, 0xf1, 0xb5, 0x3e, 0xc7, 0xbf, 0x07, 0x94, 0xb8,
	0xd3, 0x81, 0x7a, 0x26, 0x0b, 0xa2, 0x1a, 0x54, 0x4e, 0xcf, 0x7a, 0xfd, 0x73, 0xe3, 0xec, 0xe2,
	0xa4, 0xd3, 0x35, 0x6a, 0x39, 0x54, 0x86, 0x85, 0xf3, 0xee, 0x69, 0xe7, 0xe4, 0xf4, 0xa8, 0xa6,
	0xa1, 0x0a, 0x94, 0x62, 0x53, 0x7e, 0xe7, 0x05, 0xc0, 0xed, 0xed, 0x8a, 0xaa, 0x00, 0xed, 0xb3,
	0xd3, 0xc3, 0x13, 0xe3, 0x2d, 0xc7, 0xe6, 0xd0, 0x12, 0x2c, 0x2a, 0xb9, 0xdb, 0xa9, 0x69, 0x68,
	0x19, 0xca, 0x9d, 0x6e, 0xab, 0xdd, 0x3b, 0xb9, 0x68, 0xf5, 0xba, 0x9d, 0x5a, 0x7e, 0xe7, 0x47,
	0x0d, 0x1e, 0x4c, 0x55, 0x86, 0x1a, 0xa9, 0x16, 0xbd, 0xf7, 0x3e, 0x7b, 0xe4, 0xc6, 0xab, 0xe5,
	0xd0, 0xdf, 0x52, 0x65, 0x76, 0xd9, 0x15, 0xa6, 0x38, 0x74, 0x6b, 0x1a, 0xda, 0x82, 0x8d, 0x09,
	0x53, 0xa7, 0xdd, 0x3e, 0xed, 0x61, 0xcf, 0xc6, 0xd4, 0x75, 0x3c, 0x56, 0xcb, 0x4f, 0x45, 0x7d,
	0xe5, 0x78, 0xa6, 0x67, 0xe1, 0xda, 0xdc, 0xc1, 0xcf, 0x00, 0x0b, 0xbc, 0x88, 0xb7, 0x43, 0x8a,
	0xbe, 0x82, 0x52, 0xc4, 0xf5, 0xa8, 0x11, 0x77, 0x3f, 0x45, 0xff, 0xcd, 0x95, 0xc9, 0x4f, 0x97,
	0xae, 0xeb, 0xb3, 0xb1, 0x9e, 0x43, 0xff, 0x83, 0xa2, 0xe0, 0x64, 0x54, 0x8f, 0x3d, 0x93, 0x34,
	0xdf, 0x5c, 0x4b, 0xab, 0xe5, 0x26, 0xe9, 0x39, 0xf4, 0x1f, 0x98, 0x7f, 0x43, 0x86, 0x24, 0x64,
	0x09, 0xd7, 0x24, 0x71, 0xcd, 0x5a, 0xf1, 0x18, 0xaa, 0x0a, 0xf6, 0x0e, 0x07, 0x01, 0xa7, 0xd5,
	0x19, 0xfe, 0x77, 0xd3, 0xbf, 0x9e, 0x43, 0xdf, 0xc4, 0x63, 0x9f, 0x24, 0x3d, 0xf4, 0xf8, 0xf6,
	0xca, 0x9c, 0x49, 0x89, 0xb3, 0x92, 0x3b, 0x82, 0xea, 0x24, 0xcd, 0xa1, 0xdb, 0x0b, 0x38, 0x93,
	0xff, 0x66, 0x05, 0x3a, 0x81, 0xe5, 0x14, 0x01, 0xa2, 0xad, 0x74, 0x5e, 0xf7, 0x0c, 0x75, 0x04,
	0xd5, 0x49, 0x2e, 0x4b, 0xe4, 0x94, 0x49, 0x72, 0xb3, 0x02, 0x75, 0xa1, 0x96, 0xa6, 0x20, 0xb4,
	0x7d, 0x4b, 0x31, 0xd9, 0xec, 0xd4, 0x9c, 0xbc, 0x42, 0xf5, 0x1c, 0x6a, 0x41, 0x39, 0x41, 0x7e,
	0x68, 0x23, 0x95, 0x4c, 0x92, 0x82, 0x66, 0x65, 0xf2, 0x12, 0x1e, 0x5c, 0x60, 0xea, 0x5c, 0x8e,
	0x5b, 0x89, 0xdb, 0x31, 0x0b, 0x3b, 0x2b, 0x40, 0x1b, 0x2a, 0x49, 0xc6, 0x43, 0x7f, 0x4f, 0xf7,
	0xf6, 0x3e, 0x59, 0xf4, 0x60, 0xa9, 0xcd, 0xbf, 0xfa, 0xa2, 0xc7, 0x45, 0x62, 0x87, 0xb2, 0x9f,
	0x2f, 0xcd, 0xed, 0xd9, 0x80, 0xf8, 0x5c, 0x1c, 0x43, 0x75, 0xf2, 0x3d, 0x91, 0x5d, 0xd8, 0xed,
	0x5a, 0xd9, 0xaf, 0x0f, 0x31, 0xdf, 0x4b, 0x13, 0xcf, 0x37, 0x74, 0x7b, 0x22, 0xb2, 0x9e, 0x75,
	0xf7, 0x09, 0x79, 0x20, 0xb9, 0xaf, 0x83, 0x19, 0xef, 0x5a, 0x66, 0x62, 0x53, 0xfb, 0x7d, 0x0c,
	0x45, 0xc1, 0x42, 0x89, 0xe5, 0xb3, 0xae, 0x83, 0xe6, 0xe6, 0x2c, 0x73, 0xbc, 0xfa, 0xb7, 0xd0,
	0x14, 0x2f, 0xec, 0x57, 0xd8, 0x22, 0x2e, 0x4e, 0x51, 0x39, 0xfa, 0xc7, 0xac, 0x4f, 0xdd, 0xe4,
	0xab, 0x7c, 0xc6, 0x5e, 0x0e, 0xe6, 0x85, 0xf8, 0xfc, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0x28, 0xac, 0x97, 0x34, 0x10, 0x00, 0x00,
}
