// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appmgr/v1/micro/appmgr.proto

package appmgr

import (
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NamespaceCountResponse struct {
	Namespace            uint64   `protobuf:"varint,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamespaceCountResponse) Reset()         { *m = NamespaceCountResponse{} }
func (m *NamespaceCountResponse) String() string { return proto.CompactTextString(m) }
func (*NamespaceCountResponse) ProtoMessage()    {}
func (*NamespaceCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{0}
}

func (m *NamespaceCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceCountResponse.Unmarshal(m, b)
}
func (m *NamespaceCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceCountResponse.Marshal(b, m, deterministic)
}
func (m *NamespaceCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceCountResponse.Merge(m, src)
}
func (m *NamespaceCountResponse) XXX_Size() int {
	return xxx_messageInfo_NamespaceCountResponse.Size(m)
}
func (m *NamespaceCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceCountResponse proto.InternalMessageInfo

func (m *NamespaceCountResponse) GetNamespace() uint64 {
	if m != nil {
		return m.Namespace
	}
	return 0
}

// The dccn client request message containing the user's token
type CreateAppRequest struct {
	App                  *common.App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{1}
}

func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetApp() *common.App {
	if m != nil {
		return m.App
	}
	return nil
}

type CreateAppResponse struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppResponse) Reset()         { *m = CreateAppResponse{} }
func (m *CreateAppResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAppResponse) ProtoMessage()    {}
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{2}
}

func (m *CreateAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppResponse.Unmarshal(m, b)
}
func (m *CreateAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppResponse.Marshal(b, m, deterministic)
}
func (m *CreateAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppResponse.Merge(m, src)
}
func (m *CreateAppResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAppResponse.Size(m)
}
func (m *CreateAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppResponse proto.InternalMessageInfo

func (m *CreateAppResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type AppListResponse struct {
	AppReports           []*common.AppReport `protobuf:"bytes,1,rep,name=app_reports,json=appReports,proto3" json:"app_reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AppListResponse) Reset()         { *m = AppListResponse{} }
func (m *AppListResponse) String() string { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()    {}
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{3}
}

func (m *AppListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListResponse.Unmarshal(m, b)
}
func (m *AppListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListResponse.Marshal(b, m, deterministic)
}
func (m *AppListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListResponse.Merge(m, src)
}
func (m *AppListResponse) XXX_Size() int {
	return xxx_messageInfo_AppListResponse.Size(m)
}
func (m *AppListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppListResponse proto.InternalMessageInfo

func (m *AppListResponse) GetAppReports() []*common.AppReport {
	if m != nil {
		return m.AppReports
	}
	return nil
}

type AppDetailResponse struct {
	AppReport            *common.AppReport `protobuf:"bytes,1,opt,name=app_report,json=appReport,proto3" json:"app_report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppDetailResponse) Reset()         { *m = AppDetailResponse{} }
func (m *AppDetailResponse) String() string { return proto.CompactTextString(m) }
func (*AppDetailResponse) ProtoMessage()    {}
func (*AppDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{4}
}

func (m *AppDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppDetailResponse.Unmarshal(m, b)
}
func (m *AppDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppDetailResponse.Marshal(b, m, deterministic)
}
func (m *AppDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppDetailResponse.Merge(m, src)
}
func (m *AppDetailResponse) XXX_Size() int {
	return xxx_messageInfo_AppDetailResponse.Size(m)
}
func (m *AppDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppDetailResponse proto.InternalMessageInfo

func (m *AppDetailResponse) GetAppReport() *common.AppReport {
	if m != nil {
		return m.AppReport
	}
	return nil
}

type AppID struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppID) Reset()         { *m = AppID{} }
func (m *AppID) String() string { return proto.CompactTextString(m) }
func (*AppID) ProtoMessage()    {}
func (*AppID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{5}
}

func (m *AppID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppID.Unmarshal(m, b)
}
func (m *AppID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppID.Marshal(b, m, deterministic)
}
func (m *AppID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppID.Merge(m, src)
}
func (m *AppID) XXX_Size() int {
	return xxx_messageInfo_AppID.Size(m)
}
func (m *AppID) XXX_DiscardUnknown() {
	xxx_messageInfo_AppID.DiscardUnknown(m)
}

var xxx_messageInfo_AppID proto.InternalMessageInfo

func (m *AppID) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type UpdateAppRequest struct {
	AppDeployment        *common.AppDeployment `protobuf:"bytes,1,opt,name=app_deployment,json=appDeployment,proto3" json:"app_deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateAppRequest) Reset()         { *m = UpdateAppRequest{} }
func (m *UpdateAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppRequest) ProtoMessage()    {}
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{6}
}

func (m *UpdateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppRequest.Unmarshal(m, b)
}
func (m *UpdateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppRequest.Merge(m, src)
}
func (m *UpdateAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppRequest.Size(m)
}
func (m *UpdateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppRequest proto.InternalMessageInfo

func (m *UpdateAppRequest) GetAppDeployment() *common.AppDeployment {
	if m != nil {
		return m.AppDeployment
	}
	return nil
}

type AppOverviewResponse struct {
	ClusterCount         uint32   `protobuf:"varint,1,opt,name=cluster_count,json=clusterCount,proto3" json:"cluster_count,omitempty"`
	NamespaceCount       uint32   `protobuf:"varint,2,opt,name=namespace_count,json=namespaceCount,proto3" json:"namespace_count,omitempty"`
	NetworkCount         uint32   `protobuf:"varint,3,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	TotalAppCount        uint32   `protobuf:"varint,4,opt,name=total_app_count,json=totalAppCount,proto3" json:"total_app_count,omitempty"`
	CpuTotal             float32  `protobuf:"fixed32,5,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUsage             float32  `protobuf:"fixed32,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemTotal             float32  `protobuf:"fixed32,7,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsage             float32  `protobuf:"fixed32,8,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	StorageTotal         float32  `protobuf:"fixed32,9,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	StorageUsage         float32  `protobuf:"fixed32,10,opt,name=storage_usage,json=storageUsage,proto3" json:"storage_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppOverviewResponse) Reset()         { *m = AppOverviewResponse{} }
func (m *AppOverviewResponse) String() string { return proto.CompactTextString(m) }
func (*AppOverviewResponse) ProtoMessage()    {}
func (*AppOverviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{7}
}

func (m *AppOverviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppOverviewResponse.Unmarshal(m, b)
}
func (m *AppOverviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppOverviewResponse.Marshal(b, m, deterministic)
}
func (m *AppOverviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppOverviewResponse.Merge(m, src)
}
func (m *AppOverviewResponse) XXX_Size() int {
	return xxx_messageInfo_AppOverviewResponse.Size(m)
}
func (m *AppOverviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppOverviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppOverviewResponse proto.InternalMessageInfo

func (m *AppOverviewResponse) GetClusterCount() uint32 {
	if m != nil {
		return m.ClusterCount
	}
	return 0
}

func (m *AppOverviewResponse) GetNamespaceCount() uint32 {
	if m != nil {
		return m.NamespaceCount
	}
	return 0
}

func (m *AppOverviewResponse) GetNetworkCount() uint32 {
	if m != nil {
		return m.NetworkCount
	}
	return 0
}

func (m *AppOverviewResponse) GetTotalAppCount() uint32 {
	if m != nil {
		return m.TotalAppCount
	}
	return 0
}

func (m *AppOverviewResponse) GetCpuTotal() float32 {
	if m != nil {
		return m.CpuTotal
	}
	return 0
}

func (m *AppOverviewResponse) GetCpuUsage() float32 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *AppOverviewResponse) GetMemTotal() float32 {
	if m != nil {
		return m.MemTotal
	}
	return 0
}

func (m *AppOverviewResponse) GetMemUsage() float32 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *AppOverviewResponse) GetStorageTotal() float32 {
	if m != nil {
		return m.StorageTotal
	}
	return 0
}

func (m *AppOverviewResponse) GetStorageUsage() float32 {
	if m != nil {
		return m.StorageUsage
	}
	return 0
}

type AppCountRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ClusterId            string   `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppCountRequest) Reset()         { *m = AppCountRequest{} }
func (m *AppCountRequest) String() string { return proto.CompactTextString(m) }
func (*AppCountRequest) ProtoMessage()    {}
func (*AppCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{8}
}

func (m *AppCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppCountRequest.Unmarshal(m, b)
}
func (m *AppCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppCountRequest.Marshal(b, m, deterministic)
}
func (m *AppCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCountRequest.Merge(m, src)
}
func (m *AppCountRequest) XXX_Size() int {
	return xxx_messageInfo_AppCountRequest.Size(m)
}
func (m *AppCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppCountRequest proto.InternalMessageInfo

func (m *AppCountRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *AppCountRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type AppCountResponse struct {
	AppCount             uint32   `protobuf:"varint,1,opt,name=app_count,json=appCount,proto3" json:"app_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppCountResponse) Reset()         { *m = AppCountResponse{} }
func (m *AppCountResponse) String() string { return proto.CompactTextString(m) }
func (*AppCountResponse) ProtoMessage()    {}
func (*AppCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{9}
}

func (m *AppCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppCountResponse.Unmarshal(m, b)
}
func (m *AppCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppCountResponse.Marshal(b, m, deterministic)
}
func (m *AppCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCountResponse.Merge(m, src)
}
func (m *AppCountResponse) XXX_Size() int {
	return xxx_messageInfo_AppCountResponse.Size(m)
}
func (m *AppCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppCountResponse proto.InternalMessageInfo

func (m *AppCountResponse) GetAppCount() uint32 {
	if m != nil {
		return m.AppCount
	}
	return 0
}

type UploadChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartFile            []byte   `protobuf:"bytes,4,opt,name=chart_file,json=chartFile,proto3" json:"chart_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadChartRequest) Reset()         { *m = UploadChartRequest{} }
func (m *UploadChartRequest) String() string { return proto.CompactTextString(m) }
func (*UploadChartRequest) ProtoMessage()    {}
func (*UploadChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{10}
}

func (m *UploadChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChartRequest.Unmarshal(m, b)
}
func (m *UploadChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChartRequest.Marshal(b, m, deterministic)
}
func (m *UploadChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChartRequest.Merge(m, src)
}
func (m *UploadChartRequest) XXX_Size() int {
	return xxx_messageInfo_UploadChartRequest.Size(m)
}
func (m *UploadChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChartRequest proto.InternalMessageInfo

func (m *UploadChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *UploadChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *UploadChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *UploadChartRequest) GetChartFile() []byte {
	if m != nil {
		return m.ChartFile
	}
	return nil
}

type SaveAsChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	SaveRepo             string   `protobuf:"bytes,4,opt,name=save_repo,json=saveRepo,proto3" json:"save_repo,omitempty"`
	SaveVer              string   `protobuf:"bytes,5,opt,name=save_ver,json=saveVer,proto3" json:"save_ver,omitempty"`
	SaveName             string   `protobuf:"bytes,6,opt,name=save_name,json=saveName,proto3" json:"save_name,omitempty"`
	ValuesYaml           []byte   `protobuf:"bytes,7,opt,name=values_yaml,json=valuesYaml,proto3" json:"values_yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveAsChartRequest) Reset()         { *m = SaveAsChartRequest{} }
func (m *SaveAsChartRequest) String() string { return proto.CompactTextString(m) }
func (*SaveAsChartRequest) ProtoMessage()    {}
func (*SaveAsChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{11}
}

func (m *SaveAsChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveAsChartRequest.Unmarshal(m, b)
}
func (m *SaveAsChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveAsChartRequest.Marshal(b, m, deterministic)
}
func (m *SaveAsChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveAsChartRequest.Merge(m, src)
}
func (m *SaveAsChartRequest) XXX_Size() int {
	return xxx_messageInfo_SaveAsChartRequest.Size(m)
}
func (m *SaveAsChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveAsChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveAsChartRequest proto.InternalMessageInfo

func (m *SaveAsChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *SaveAsChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *SaveAsChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *SaveAsChartRequest) GetSaveRepo() string {
	if m != nil {
		return m.SaveRepo
	}
	return ""
}

func (m *SaveAsChartRequest) GetSaveVer() string {
	if m != nil {
		return m.SaveVer
	}
	return ""
}

func (m *SaveAsChartRequest) GetSaveName() string {
	if m != nil {
		return m.SaveName
	}
	return ""
}

func (m *SaveAsChartRequest) GetValuesYaml() []byte {
	if m != nil {
		return m.ValuesYaml
	}
	return nil
}

type ChartListRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartListRequest) Reset()         { *m = ChartListRequest{} }
func (m *ChartListRequest) String() string { return proto.CompactTextString(m) }
func (*ChartListRequest) ProtoMessage()    {}
func (*ChartListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{12}
}

func (m *ChartListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListRequest.Unmarshal(m, b)
}
func (m *ChartListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListRequest.Marshal(b, m, deterministic)
}
func (m *ChartListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListRequest.Merge(m, src)
}
func (m *ChartListRequest) XXX_Size() int {
	return xxx_messageInfo_ChartListRequest.Size(m)
}
func (m *ChartListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListRequest proto.InternalMessageInfo

func (m *ChartListRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

type ChartListResponse struct {
	Charts               []*common.Chart `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChartListResponse) Reset()         { *m = ChartListResponse{} }
func (m *ChartListResponse) String() string { return proto.CompactTextString(m) }
func (*ChartListResponse) ProtoMessage()    {}
func (*ChartListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{13}
}

func (m *ChartListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListResponse.Unmarshal(m, b)
}
func (m *ChartListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListResponse.Marshal(b, m, deterministic)
}
func (m *ChartListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListResponse.Merge(m, src)
}
func (m *ChartListResponse) XXX_Size() int {
	return xxx_messageInfo_ChartListResponse.Size(m)
}
func (m *ChartListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListResponse proto.InternalMessageInfo

func (m *ChartListResponse) GetCharts() []*common.Chart {
	if m != nil {
		return m.Charts
	}
	return nil
}

type ChartDetailRequest struct {
	Chart                *common.Chart `protobuf:"bytes,1,opt,name=chart,proto3" json:"chart,omitempty"`
	ShowVersion          string        `protobuf:"bytes,2,opt,name=show_version,json=showVersion,proto3" json:"show_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChartDetailRequest) Reset()         { *m = ChartDetailRequest{} }
func (m *ChartDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ChartDetailRequest) ProtoMessage()    {}
func (*ChartDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{14}
}

func (m *ChartDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailRequest.Unmarshal(m, b)
}
func (m *ChartDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailRequest.Marshal(b, m, deterministic)
}
func (m *ChartDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailRequest.Merge(m, src)
}
func (m *ChartDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ChartDetailRequest.Size(m)
}
func (m *ChartDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailRequest proto.InternalMessageInfo

func (m *ChartDetailRequest) GetChart() *common.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *ChartDetailRequest) GetShowVersion() string {
	if m != nil {
		return m.ShowVersion
	}
	return ""
}

type ChartDetailResponse struct {
	ChartName            string                       `protobuf:"bytes,1,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartRepo            string                       `protobuf:"bytes,2,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartDescription     string                       `protobuf:"bytes,3,opt,name=chart_description,json=chartDescription,proto3" json:"chart_description,omitempty"`
	ChartVersionDetails  []*common.ChartVersionDetail `protobuf:"bytes,4,rep,name=chart_version_details,json=chartVersionDetails,proto3" json:"chart_version_details,omitempty"`
	ReadmeMd             string                       `protobuf:"bytes,5,opt,name=readme_md,json=readmeMd,proto3" json:"readme_md,omitempty"`
	ValuesYaml           string                       `protobuf:"bytes,6,opt,name=values_yaml,json=valuesYaml,proto3" json:"values_yaml,omitempty"`
	CustomValues         []*common.CustomValue        `protobuf:"bytes,7,rep,name=custom_values,json=customValues,proto3" json:"custom_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ChartDetailResponse) Reset()         { *m = ChartDetailResponse{} }
func (m *ChartDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ChartDetailResponse) ProtoMessage()    {}
func (*ChartDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{15}
}

func (m *ChartDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailResponse.Unmarshal(m, b)
}
func (m *ChartDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailResponse.Marshal(b, m, deterministic)
}
func (m *ChartDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailResponse.Merge(m, src)
}
func (m *ChartDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ChartDetailResponse.Size(m)
}
func (m *ChartDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailResponse proto.InternalMessageInfo

func (m *ChartDetailResponse) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *ChartDetailResponse) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *ChartDetailResponse) GetChartDescription() string {
	if m != nil {
		return m.ChartDescription
	}
	return ""
}

func (m *ChartDetailResponse) GetChartVersionDetails() []*common.ChartVersionDetail {
	if m != nil {
		return m.ChartVersionDetails
	}
	return nil
}

func (m *ChartDetailResponse) GetReadmeMd() string {
	if m != nil {
		return m.ReadmeMd
	}
	return ""
}

func (m *ChartDetailResponse) GetValuesYaml() string {
	if m != nil {
		return m.ValuesYaml
	}
	return ""
}

func (m *ChartDetailResponse) GetCustomValues() []*common.CustomValue {
	if m != nil {
		return m.CustomValues
	}
	return nil
}

type DownloadChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadChartRequest) Reset()         { *m = DownloadChartRequest{} }
func (m *DownloadChartRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadChartRequest) ProtoMessage()    {}
func (*DownloadChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{16}
}

func (m *DownloadChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadChartRequest.Unmarshal(m, b)
}
func (m *DownloadChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadChartRequest.Marshal(b, m, deterministic)
}
func (m *DownloadChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadChartRequest.Merge(m, src)
}
func (m *DownloadChartRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadChartRequest.Size(m)
}
func (m *DownloadChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadChartRequest proto.InternalMessageInfo

func (m *DownloadChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *DownloadChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *DownloadChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type DownloadChartResponse struct {
	ChartFile            []byte   `protobuf:"bytes,1,opt,name=chart_file,json=chartFile,proto3" json:"chart_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadChartResponse) Reset()         { *m = DownloadChartResponse{} }
func (m *DownloadChartResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadChartResponse) ProtoMessage()    {}
func (*DownloadChartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{17}
}

func (m *DownloadChartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadChartResponse.Unmarshal(m, b)
}
func (m *DownloadChartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadChartResponse.Marshal(b, m, deterministic)
}
func (m *DownloadChartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadChartResponse.Merge(m, src)
}
func (m *DownloadChartResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadChartResponse.Size(m)
}
func (m *DownloadChartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadChartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadChartResponse proto.InternalMessageInfo

func (m *DownloadChartResponse) GetChartFile() []byte {
	if m != nil {
		return m.ChartFile
	}
	return nil
}

type DeleteChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteChartRequest) Reset()         { *m = DeleteChartRequest{} }
func (m *DeleteChartRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteChartRequest) ProtoMessage()    {}
func (*DeleteChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{18}
}

func (m *DeleteChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteChartRequest.Unmarshal(m, b)
}
func (m *DeleteChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteChartRequest.Marshal(b, m, deterministic)
}
func (m *DeleteChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteChartRequest.Merge(m, src)
}
func (m *DeleteChartRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteChartRequest.Size(m)
}
func (m *DeleteChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteChartRequest proto.InternalMessageInfo

func (m *DeleteChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *DeleteChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *DeleteChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type CreateNamespaceRequest struct {
	Namespace            *common.Namespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{19}
}

func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(m, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetNamespace() *common.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type CreateNamespaceResponse struct {
	NsId                 string   `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{20}
}

func (m *CreateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceResponse.Unmarshal(m, b)
}
func (m *CreateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceResponse.Merge(m, src)
}
func (m *CreateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceResponse.Size(m)
}
func (m *CreateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceResponse proto.InternalMessageInfo

func (m *CreateNamespaceResponse) GetNsId() string {
	if m != nil {
		return m.NsId
	}
	return ""
}

type NamespaceListResponse struct {
	NamespaceReports     []*common.NamespaceReport `protobuf:"bytes,1,rep,name=namespace_reports,json=namespaceReports,proto3" json:"namespace_reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NamespaceListResponse) Reset()         { *m = NamespaceListResponse{} }
func (m *NamespaceListResponse) String() string { return proto.CompactTextString(m) }
func (*NamespaceListResponse) ProtoMessage()    {}
func (*NamespaceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{21}
}

func (m *NamespaceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceListResponse.Unmarshal(m, b)
}
func (m *NamespaceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceListResponse.Marshal(b, m, deterministic)
}
func (m *NamespaceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceListResponse.Merge(m, src)
}
func (m *NamespaceListResponse) XXX_Size() int {
	return xxx_messageInfo_NamespaceListResponse.Size(m)
}
func (m *NamespaceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceListResponse proto.InternalMessageInfo

func (m *NamespaceListResponse) GetNamespaceReports() []*common.NamespaceReport {
	if m != nil {
		return m.NamespaceReports
	}
	return nil
}

type UpdateNamespaceRequest struct {
	Namespace            *common.Namespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateNamespaceRequest) Reset()         { *m = UpdateNamespaceRequest{} }
func (m *UpdateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceRequest) ProtoMessage()    {}
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{22}
}

func (m *UpdateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceRequest.Unmarshal(m, b)
}
func (m *UpdateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceRequest.Merge(m, src)
}
func (m *UpdateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceRequest.Size(m)
}
func (m *UpdateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceRequest proto.InternalMessageInfo

func (m *UpdateNamespaceRequest) GetNamespace() *common.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type DeleteNamespaceRequest struct {
	NsId                 string   `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1cb3715215941c, []int{23}
}

func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(m, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetNsId() string {
	if m != nil {
		return m.NsId
	}
	return ""
}

func init() {
	proto.RegisterType((*NamespaceCountResponse)(nil), "appmgr.NamespaceCountResponse")
	proto.RegisterType((*CreateAppRequest)(nil), "appmgr.CreateAppRequest")
	proto.RegisterType((*CreateAppResponse)(nil), "appmgr.CreateAppResponse")
	proto.RegisterType((*AppListResponse)(nil), "appmgr.AppListResponse")
	proto.RegisterType((*AppDetailResponse)(nil), "appmgr.AppDetailResponse")
	proto.RegisterType((*AppID)(nil), "appmgr.AppID")
	proto.RegisterType((*UpdateAppRequest)(nil), "appmgr.UpdateAppRequest")
	proto.RegisterType((*AppOverviewResponse)(nil), "appmgr.AppOverviewResponse")
	proto.RegisterType((*AppCountRequest)(nil), "appmgr.AppCountRequest")
	proto.RegisterType((*AppCountResponse)(nil), "appmgr.AppCountResponse")
	proto.RegisterType((*UploadChartRequest)(nil), "appmgr.UploadChartRequest")
	proto.RegisterType((*SaveAsChartRequest)(nil), "appmgr.SaveAsChartRequest")
	proto.RegisterType((*ChartListRequest)(nil), "appmgr.ChartListRequest")
	proto.RegisterType((*ChartListResponse)(nil), "appmgr.ChartListResponse")
	proto.RegisterType((*ChartDetailRequest)(nil), "appmgr.ChartDetailRequest")
	proto.RegisterType((*ChartDetailResponse)(nil), "appmgr.ChartDetailResponse")
	proto.RegisterType((*DownloadChartRequest)(nil), "appmgr.DownloadChartRequest")
	proto.RegisterType((*DownloadChartResponse)(nil), "appmgr.DownloadChartResponse")
	proto.RegisterType((*DeleteChartRequest)(nil), "appmgr.DeleteChartRequest")
	proto.RegisterType((*CreateNamespaceRequest)(nil), "appmgr.CreateNamespaceRequest")
	proto.RegisterType((*CreateNamespaceResponse)(nil), "appmgr.CreateNamespaceResponse")
	proto.RegisterType((*NamespaceListResponse)(nil), "appmgr.NamespaceListResponse")
	proto.RegisterType((*UpdateNamespaceRequest)(nil), "appmgr.UpdateNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "appmgr.DeleteNamespaceRequest")
}

func init() { proto.RegisterFile("appmgr/v1/micro/appmgr.proto", fileDescriptor_4a1cb3715215941c) }

var fileDescriptor_4a1cb3715215941c = []byte{
	// 1223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdb, 0x6e, 0x23, 0x45,
	0x13, 0xb6, 0xb3, 0xb1, 0xe3, 0x29, 0xdb, 0xb1, 0xdd, 0xfe, 0x93, 0x38, 0xce, 0x61, 0xf3, 0x77,
	0x24, 0x08, 0xac, 0x48, 0x48, 0x10, 0x59, 0x90, 0x10, 0xc4, 0x1b, 0x2f, 0xac, 0x59, 0x76, 0x17,
	0x0d, 0x49, 0x24, 0xae, 0xac, 0xde, 0x99, 0x26, 0x6b, 0xe1, 0x99, 0xe9, 0x9d, 0x1e, 0x3b, 0xca,
	0x03, 0x70, 0xcb, 0xd3, 0xf1, 0x0a, 0xdc, 0xf2, 0x0c, 0xa8, 0x0f, 0x73, 0x9e, 0x91, 0xf6, 0x02,
	0xe5, 0x2a, 0xee, 0xaa, 0xaf, 0xbe, 0xaa, 0xae, 0xea, 0xa9, 0xaa, 0xc0, 0x2e, 0x61, 0xcc, 0xb9,
	0xf5, 0x4f, 0x96, 0xa7, 0x27, 0xce, 0xcc, 0xf2, 0xbd, 0x13, 0x75, 0x3e, 0x66, 0xbe, 0x17, 0x78,
	0xa8, 0xae, 0x4e, 0xc3, 0xbe, 0xe5, 0x39, 0x8e, 0xe7, 0x9e, 0xa8, 0x3f, 0x4a, 0x89, 0xcf, 0x61,
	0xf3, 0x35, 0x71, 0x28, 0x67, 0xc4, 0xa2, 0x97, 0xde, 0xc2, 0x0d, 0x4c, 0xca, 0x99, 0xe7, 0x72,
	0x8a, 0x76, 0xc1, 0x70, 0x43, 0xcd, 0xa0, 0x7a, 0x50, 0x3d, 0x5a, 0x35, 0x63, 0x01, 0x7e, 0x0a,
	0xdd, 0x4b, 0x9f, 0x92, 0x80, 0x8e, 0x18, 0x33, 0xe9, 0xfb, 0x05, 0xe5, 0x01, 0x3a, 0x84, 0x47,
	0x84, 0x31, 0x89, 0x6d, 0x9e, 0xf5, 0x8e, 0x93, 0x7e, 0x8e, 0x05, 0x4c, 0x68, 0xf1, 0xa7, 0xd0,
	0x4b, 0x18, 0x6a, 0x5f, 0x1b, 0x20, 0x82, 0x9c, 0xce, 0x6c, 0x69, 0x6c, 0x98, 0x35, 0xc2, 0xd8,
	0xc4, 0xc6, 0x2f, 0xa1, 0x33, 0x62, 0xec, 0xa7, 0x19, 0x8f, 0xa3, 0xfa, 0x0a, 0x9a, 0x02, 0xe9,
	0x53, 0xe6, 0xf9, 0x01, 0x1f, 0x54, 0x0f, 0x1e, 0x1d, 0x35, 0xcf, 0xb6, 0xf2, 0xbe, 0xa4, 0xde,
	0x04, 0x12, 0xfe, 0xe4, 0xf8, 0x25, 0xf4, 0x46, 0x8c, 0x8d, 0x69, 0x40, 0x66, 0xf3, 0x88, 0xee,
	0x1c, 0x20, 0xa6, 0xd3, 0x91, 0x97, 0xb2, 0x19, 0x11, 0x1b, 0xde, 0x87, 0xda, 0x88, 0xb1, 0xc9,
	0xb8, 0x2c, 0xf2, 0x1b, 0xe8, 0x5e, 0x33, 0x3b, 0x9d, 0x9e, 0x67, 0xb0, 0x2e, 0xa0, 0x36, 0x65,
	0x73, 0xef, 0xde, 0xa1, 0x6e, 0xe8, 0x6f, 0x27, 0xe7, 0x6f, 0x1c, 0x41, 0xcc, 0x36, 0x49, 0x1e,
	0xf1, 0x3f, 0x2b, 0xd0, 0x1f, 0x31, 0xf6, 0x66, 0x49, 0xfd, 0xe5, 0x8c, 0xde, 0x45, 0xf7, 0x38,
	0x84, 0xb6, 0x35, 0x5f, 0xf0, 0x80, 0xfa, 0x53, 0x4b, 0x54, 0x51, 0x52, 0xb7, 0xcd, 0x96, 0x16,
	0xca, 0xca, 0xa2, 0x8f, 0xa1, 0x13, 0x15, 0x50, 0xc3, 0x56, 0x24, 0x6c, 0xdd, 0x4d, 0x3d, 0x01,
	0xc1, 0xe6, 0xd2, 0xe0, 0xce, 0xf3, 0x7f, 0xd7, 0xb0, 0x47, 0x8a, 0x4d, 0x0b, 0x15, 0xe8, 0x23,
	0xe8, 0x04, 0x5e, 0x40, 0xe6, 0x53, 0x71, 0x29, 0x05, 0x5b, 0x95, 0xb0, 0xb6, 0x14, 0x8f, 0x18,
	0x53, 0xb8, 0x1d, 0x30, 0x2c, 0xb6, 0x98, 0x4a, 0xe1, 0xa0, 0x76, 0x50, 0x3d, 0x5a, 0x31, 0x1b,
	0x16, 0x5b, 0x5c, 0x89, 0x73, 0xa8, 0x5c, 0x70, 0x72, 0x4b, 0x07, 0xf5, 0x48, 0x79, 0x2d, 0xce,
	0x42, 0xe9, 0x50, 0x47, 0x5b, 0xae, 0x29, 0xa5, 0x43, 0x9d, 0xc8, 0x52, 0x28, 0x95, 0x65, 0x23,
	0x52, 0x2a, 0xcb, 0x43, 0x68, 0xf3, 0xc0, 0xf3, 0xc9, 0x2d, 0xd5, 0xd6, 0x86, 0x04, 0xb4, 0xb4,
	0x50, 0x31, 0x24, 0x40, 0x8a, 0x05, 0x52, 0x20, 0xc9, 0x84, 0x27, 0xf2, 0x09, 0xea, 0x2f, 0x43,
	0xd5, 0x71, 0x0b, 0xd6, 0x02, 0x4a, 0x9c, 0xb8, 0xe6, 0x75, 0x71, 0x9c, 0xd8, 0x68, 0x0f, 0x20,
	0x2c, 0xc2, 0xcc, 0x96, 0xa9, 0x35, 0x4c, 0x43, 0x4b, 0x26, 0x36, 0x3e, 0x81, 0x6e, 0x4c, 0xa5,
	0xeb, 0xb6, 0x03, 0x46, 0x9c, 0x3e, 0x55, 0xb3, 0x06, 0xd1, 0x20, 0xfc, 0x67, 0x15, 0xd0, 0x35,
	0x9b, 0x7b, 0xc4, 0xbe, 0x7c, 0x47, 0xfc, 0xc8, 0xbf, 0x70, 0x23, 0xce, 0xf2, 0xd5, 0xea, 0x10,
	0x0c, 0x4b, 0x21, 0x98, 0x27, 0x53, 0x2a, 0xd5, 0x4b, 0xea, 0xeb, 0x20, 0x1a, 0x52, 0x70, 0x43,
	0xfd, 0xd8, 0x56, 0x54, 0x5c, 0x96, 0x35, 0xb4, 0x15, 0x5d, 0x20, 0x56, 0xff, 0x36, 0x9b, 0x53,
	0x59, 0xce, 0x96, 0x56, 0x7f, 0x3f, 0x9b, 0x53, 0xfc, 0x77, 0x15, 0xd0, 0x2f, 0x64, 0x49, 0x47,
	0xfc, 0xa1, 0x02, 0xda, 0x01, 0x83, 0x93, 0x25, 0x55, 0xcc, 0xab, 0xca, 0x56, 0x08, 0x24, 0xf1,
	0x36, 0xc8, 0xdf, 0x92, 0xb7, 0x26, 0x75, 0x6b, 0xe2, 0x2c, 0x68, 0x43, 0x3b, 0xc9, 0x5a, 0x8f,
	0xed, 0x24, 0xe9, 0x63, 0x68, 0x2e, 0xc9, 0x7c, 0x41, 0xf9, 0xf4, 0x9e, 0x38, 0xea, 0x65, 0xb5,
	0x4c, 0x50, 0xa2, 0x5f, 0x89, 0x33, 0xc7, 0xa7, 0xd0, 0x95, 0x17, 0x54, 0x9d, 0xe7, 0x43, 0x2e,
	0x89, 0x2f, 0xa0, 0x97, 0x30, 0xd1, 0xd5, 0x7d, 0x02, 0x75, 0x89, 0x08, 0xfb, 0x54, 0x3f, 0xfd,
	0xa5, 0xab, 0x24, 0x6a, 0x08, 0x7e, 0x0b, 0x48, 0x0a, 0xc2, 0x0e, 0xa5, 0xdc, 0x7e, 0x02, 0x35,
	0xa9, 0xd7, 0xbd, 0xa2, 0x90, 0x41, 0x21, 0xd0, 0xff, 0xa1, 0xc5, 0xdf, 0x79, 0x77, 0x22, 0x1d,
	0x7c, 0xe6, 0xb9, 0x3a, 0xd5, 0x4d, 0x21, 0xbb, 0x51, 0x22, 0xfc, 0xd7, 0x0a, 0xf4, 0x53, 0x4e,
	0x74, 0xa0, 0xe9, 0x2a, 0x54, 0x4b, 0x9f, 0x85, 0xbc, 0xfb, 0x4a, 0xb6, 0xc0, 0x4f, 0xa0, 0xa7,
	0xd4, 0x36, 0xe5, 0x96, 0x3f, 0x63, 0x81, 0xf0, 0xae, 0x4a, 0xd9, 0xb5, 0x94, 0xb7, 0x48, 0x8e,
	0xae, 0x60, 0x23, 0x7a, 0x0d, 0x22, 0xa6, 0xa9, 0x2d, 0x43, 0xe1, 0x83, 0x55, 0x99, 0xa2, 0x83,
	0x82, 0x0b, 0xea, 0xe8, 0x75, 0xcc, 0x7d, 0x2b, 0x27, 0xe3, 0xa2, 0xde, 0x3e, 0x25, 0xb6, 0x43,
	0xa7, 0x8e, 0xad, 0xdf, 0x42, 0x43, 0x09, 0x5e, 0xd9, 0xd9, 0x7a, 0xab, 0xe7, 0x90, 0xa8, 0x37,
	0xfa, 0x16, 0xda, 0xd6, 0x82, 0x07, 0x9e, 0x33, 0x55, 0xc2, 0xc1, 0x9a, 0x8c, 0x65, 0x3b, 0x13,
	0x8b, 0x84, 0xdc, 0x08, 0x84, 0xd9, 0xb2, 0xe2, 0x03, 0xc7, 0xef, 0xe1, 0x7f, 0x63, 0xef, 0xce,
	0x7d, 0xc0, 0x2f, 0x15, 0x9f, 0xc3, 0x46, 0xc6, 0x65, 0xb6, 0x94, 0xf2, 0x13, 0xae, 0x66, 0x3f,
	0x61, 0x0f, 0xd0, 0x98, 0xce, 0x69, 0x40, 0x1f, 0x2a, 0xd0, 0x37, 0xb0, 0xa9, 0xe6, 0x7d, 0xb4,
	0x66, 0x84, 0x4e, 0xbf, 0xcc, 0x2e, 0x18, 0xb9, 0xd1, 0x1b, 0x9b, 0x24, 0x36, 0x8f, 0x63, 0xd8,
	0xca, 0x11, 0xea, 0xbb, 0xf7, 0xa1, 0xe6, 0xf2, 0xb8, 0x2f, 0xaf, 0xba, 0x7c, 0x62, 0x63, 0x0b,
	0x36, 0x22, 0x64, 0xea, 0xeb, 0xfc, 0x11, 0x7a, 0xf1, 0x38, 0x4c, 0x2f, 0x14, 0x7b, 0x65, 0x71,
	0xa8, 0x45, 0xa0, 0xeb, 0xa6, 0x05, 0x5c, 0xdc, 0x52, 0xcd, 0xfb, 0xff, 0xea, 0x96, 0x9f, 0xc1,
	0xa6, 0xaa, 0x53, 0x8e, 0xb0, 0xe8, 0x92, 0x67, 0x7f, 0x00, 0xd4, 0x47, 0x8c, 0xbd, 0xba, 0xf5,
	0xd1, 0x33, 0x30, 0xa2, 0x05, 0x0b, 0x0d, 0x8e, 0xf5, 0x2a, 0x98, 0x5d, 0xd6, 0x86, 0xdb, 0x05,
	0x1a, 0x95, 0x18, 0x5c, 0x41, 0x5f, 0xc3, 0x9a, 0x5e, 0xbc, 0x50, 0xa6, 0xe3, 0x3c, 0x77, 0x58,
	0x70, 0x3f, 0xdc, 0x0a, 0x8d, 0x33, 0xeb, 0x19, 0xae, 0xa0, 0xa7, 0x60, 0x44, 0x6b, 0x16, 0x6a,
	0x27, 0x70, 0x93, 0x71, 0xec, 0x33, 0xb7, 0x88, 0xe1, 0x0a, 0x3a, 0x05, 0xe3, 0x92, 0xb8, 0x16,
	0x15, 0x9b, 0x43, 0xd6, 0xb0, 0x28, 0x08, 0x5c, 0x41, 0x9f, 0x43, 0xe3, 0xe7, 0x85, 0x7f, 0x4b,
	0x3f, 0xdc, 0xe2, 0x1b, 0x30, 0xa2, 0xbd, 0x2c, 0x4e, 0x4e, 0x76, 0x55, 0x2b, 0xb3, 0x1e, 0x41,
	0x33, 0xb1, 0x7c, 0x15, 0xa7, 0x66, 0x27, 0x11, 0x47, 0x76, 0x4d, 0xc3, 0x15, 0x74, 0x01, 0xcd,
	0xc4, 0x48, 0x47, 0xc3, 0x38, 0x84, 0x6c, 0xf7, 0x28, 0x0b, 0xe2, 0x02, 0x9a, 0x89, 0x19, 0x1c,
	0x33, 0xe4, 0x07, 0x73, 0x19, 0x83, 0x78, 0x21, 0xe1, 0xac, 0x4a, 0xbc, 0x90, 0xcc, 0xc4, 0x4b,
	0xbc, 0x90, 0xec, 0x60, 0xc3, 0x15, 0xf4, 0x02, 0x9a, 0x89, 0x41, 0x12, 0x47, 0x91, 0x1f, 0x61,
	0x71, 0x46, 0x0a, 0x26, 0x0f, 0xae, 0xa0, 0xd7, 0xd0, 0x4e, 0x75, 0x32, 0xb4, 0x1b, 0xe2, 0x8b,
	0x7a, 0xea, 0x70, 0xaf, 0x44, 0x9b, 0xcc, 0x70, 0xa2, 0xc3, 0xc5, 0x91, 0xe5, 0xdb, 0x5e, 0x59,
	0x7e, 0xae, 0xa0, 0x93, 0xe9, 0x30, 0x68, 0x3f, 0xfd, 0xb5, 0x64, 0x3f, 0xca, 0xe1, 0xe3, 0x52,
	0x7d, 0x14, 0xd7, 0x73, 0x68, 0xa7, 0xfa, 0x50, 0xf1, 0xf3, 0x89, 0xae, 0x57, 0xd8, 0xb3, 0x64,
	0xe2, 0x3b, 0x99, 0x4e, 0x13, 0x07, 0x57, 0xdc, 0x82, 0xca, 0xae, 0xf9, 0x02, 0x3a, 0x99, 0x16,
	0x13, 0x33, 0x15, 0xf7, 0x9e, 0x32, 0xa6, 0xef, 0xa0, 0x11, 0xad, 0xfb, 0xc9, 0xd6, 0x90, 0x5c,
	0x9b, 0x87, 0x83, 0xbc, 0x22, 0xba, 0xd4, 0x0f, 0xb0, 0x9e, 0xfe, 0x2f, 0xb4, 0x38, 0x39, 0xfb,
	0xb9, 0xe4, 0x64, 0x88, 0xde, 0xd6, 0x25, 0xfc, 0x8b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3b,
	0x46, 0x25, 0x74, 0x12, 0x0f, 0x00, 0x00,
}
