// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api_order

package apiOrder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiOrderStatus int32

const (
	ApiOrderStatus_unknown       ApiOrderStatus = 0
	ApiOrderStatus_success       ApiOrderStatus = 1
	ApiOrderStatus_fail          ApiOrderStatus = 2
	ApiOrderStatus_request_error ApiOrderStatus = 3
)

var ApiOrderStatus_name = map[int32]string{
	0: "unknown",
	1: "success",
	2: "fail",
	3: "request_error",
}

var ApiOrderStatus_value = map[string]int32{
	"unknown":       0,
	"success":       1,
	"fail":          2,
	"request_error": 3,
}

func (x ApiOrderStatus) String() string {
	return proto.EnumName(ApiOrderStatus_name, int32(x))
}

func (ApiOrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b34dd0c9d3ed5285, []int{0}
}

type OperationType int32

const (
	OperationType_not_known OperationType = 0
	OperationType_insert    OperationType = 1
	OperationType_delete    OperationType = 2
	OperationType_update    OperationType = 3
)

var OperationType_name = map[int32]string{
	0: "not_known",
	1: "insert",
	2: "delete",
	3: "update",
}

var OperationType_value = map[string]int32{
	"not_known": 0,
	"insert":    1,
	"delete":    2,
	"update":    3,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b34dd0c9d3ed5285, []int{1}
}

type AuthorizationType int32

const (
	AuthorizationType_invalid AuthorizationType = 0
	AuthorizationType_pass    AuthorizationType = 1
	AuthorizationType_token   AuthorizationType = 2
)

var AuthorizationType_name = map[int32]string{
	0: "invalid",
	1: "pass",
	2: "token",
}

var AuthorizationType_value = map[string]int32{
	"invalid": 0,
	"pass":    1,
	"token":   2,
}

func (x AuthorizationType) String() string {
	return proto.EnumName(AuthorizationType_name, int32(x))
}

func (AuthorizationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b34dd0c9d3ed5285, []int{2}
}

type APIInfo struct {
	NodeTypeCode         string   `protobuf:"bytes,1,opt,name=node_type_code,json=nodeTypeCode,proto3" json:"node_type_code,omitempty"`
	NodeTypeDescribe     string   `protobuf:"bytes,2,opt,name=node_type_describe,json=nodeTypeDescribe,proto3" json:"node_type_describe,omitempty"`
	NodeApiUrl           string   `protobuf:"bytes,3,opt,name=node_api_url,json=nodeApiUrl,proto3" json:"node_api_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIInfo) Reset()         { *m = APIInfo{} }
func (m *APIInfo) String() string { return proto.CompactTextString(m) }
func (*APIInfo) ProtoMessage()    {}
func (*APIInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b34dd0c9d3ed5285, []int{0}
}

func (m *APIInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIInfo.Unmarshal(m, b)
}
func (m *APIInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIInfo.Marshal(b, m, deterministic)
}
func (m *APIInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIInfo.Merge(m, src)
}
func (m *APIInfo) XXX_Size() int {
	return xxx_messageInfo_APIInfo.Size(m)
}
func (m *APIInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_APIInfo.DiscardUnknown(m)
}

var xxx_messageInfo_APIInfo proto.InternalMessageInfo

func (m *APIInfo) GetNodeTypeCode() string {
	if m != nil {
		return m.NodeTypeCode
	}
	return ""
}

func (m *APIInfo) GetNodeTypeDescribe() string {
	if m != nil {
		return m.NodeTypeDescribe
	}
	return ""
}

func (m *APIInfo) GetNodeApiUrl() string {
	if m != nil {
		return m.NodeApiUrl
	}
	return ""
}

type ApiOrderResponseMessage struct {
	OrderId              string         `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AccessId             string         `protobuf:"bytes,2,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	RequestTime          string         `protobuf:"bytes,3,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	OpType               OperationType  `protobuf:"varint,4,opt,name=op_type,json=opType,proto3,enum=apiOrder.OperationType" json:"op_type,omitempty"`
	Status               ApiOrderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=apiOrder.ApiOrderStatus" json:"status,omitempty"`
	Api                  []*APIInfo     `protobuf:"bytes,6,rep,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApiOrderResponseMessage) Reset()         { *m = ApiOrderResponseMessage{} }
func (m *ApiOrderResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ApiOrderResponseMessage) ProtoMessage()    {}
func (*ApiOrderResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b34dd0c9d3ed5285, []int{1}
}

func (m *ApiOrderResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiOrderResponseMessage.Unmarshal(m, b)
}
func (m *ApiOrderResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiOrderResponseMessage.Marshal(b, m, deterministic)
}
func (m *ApiOrderResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiOrderResponseMessage.Merge(m, src)
}
func (m *ApiOrderResponseMessage) XXX_Size() int {
	return xxx_messageInfo_ApiOrderResponseMessage.Size(m)
}
func (m *ApiOrderResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiOrderResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApiOrderResponseMessage proto.InternalMessageInfo

func (m *ApiOrderResponseMessage) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ApiOrderResponseMessage) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *ApiOrderResponseMessage) GetRequestTime() string {
	if m != nil {
		return m.RequestTime
	}
	return ""
}

func (m *ApiOrderResponseMessage) GetOpType() OperationType {
	if m != nil {
		return m.OpType
	}
	return OperationType_not_known
}

func (m *ApiOrderResponseMessage) GetStatus() ApiOrderStatus {
	if m != nil {
		return m.Status
	}
	return ApiOrderStatus_unknown
}

func (m *ApiOrderResponseMessage) GetApi() []*APIInfo {
	if m != nil {
		return m.Api
	}
	return nil
}

type Authorization struct {
	AuthType             AuthorizationType `protobuf:"varint,1,opt,name=authType,proto3,enum=apiOrder.AuthorizationType" json:"authType,omitempty"`
	Username             string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string            `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Token                string            `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Authorization) Reset()         { *m = Authorization{} }
func (m *Authorization) String() string { return proto.CompactTextString(m) }
func (*Authorization) ProtoMessage()    {}
func (*Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_b34dd0c9d3ed5285, []int{2}
}

func (m *Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorization.Unmarshal(m, b)
}
func (m *Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorization.Marshal(b, m, deterministic)
}
func (m *Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorization.Merge(m, src)
}
func (m *Authorization) XXX_Size() int {
	return xxx_messageInfo_Authorization.Size(m)
}
func (m *Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_Authorization proto.InternalMessageInfo

func (m *Authorization) GetAuthType() AuthorizationType {
	if m != nil {
		return m.AuthType
	}
	return AuthorizationType_invalid
}

func (m *Authorization) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Authorization) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Authorization) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ApiOrderRequestMessage struct {
	OrderId              string         `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NodeType             string         `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	AccessId             string         `protobuf:"bytes,3,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	FlagPrefix           string         `protobuf:"bytes,4,opt,name=flag_prefix,json=flagPrefix,proto3" json:"flag_prefix,omitempty"`
	MaxReqDaily          int64          `protobuf:"varint,5,opt,name=max_req_daily,json=maxReqDaily,proto3" json:"max_req_daily,omitempty"`
	RateLimitSec         int64          `protobuf:"varint,6,opt,name=rate_limit_sec,json=rateLimitSec,proto3" json:"rate_limit_sec,omitempty"`
	RequestTime          string         `protobuf:"bytes,7,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	OpType               OperationType  `protobuf:"varint,8,opt,name=op_type,json=opType,proto3,enum=apiOrder.OperationType" json:"op_type,omitempty"`
	Uid                  string         `protobuf:"bytes,9,opt,name=uid,proto3" json:"uid,omitempty"`
	MaxReqMonthly        int64          `protobuf:"varint,10,opt,name=max_req_monthly,json=maxReqMonthly,proto3" json:"max_req_monthly,omitempty"`
	Auth                 *Authorization `protobuf:"bytes,11,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApiOrderRequestMessage) Reset()         { *m = ApiOrderRequestMessage{} }
func (m *ApiOrderRequestMessage) String() string { return proto.CompactTextString(m) }
func (*ApiOrderRequestMessage) ProtoMessage()    {}
func (*ApiOrderRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b34dd0c9d3ed5285, []int{3}
}

func (m *ApiOrderRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiOrderRequestMessage.Unmarshal(m, b)
}
func (m *ApiOrderRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiOrderRequestMessage.Marshal(b, m, deterministic)
}
func (m *ApiOrderRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiOrderRequestMessage.Merge(m, src)
}
func (m *ApiOrderRequestMessage) XXX_Size() int {
	return xxx_messageInfo_ApiOrderRequestMessage.Size(m)
}
func (m *ApiOrderRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiOrderRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApiOrderRequestMessage proto.InternalMessageInfo

func (m *ApiOrderRequestMessage) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ApiOrderRequestMessage) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *ApiOrderRequestMessage) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *ApiOrderRequestMessage) GetFlagPrefix() string {
	if m != nil {
		return m.FlagPrefix
	}
	return ""
}

func (m *ApiOrderRequestMessage) GetMaxReqDaily() int64 {
	if m != nil {
		return m.MaxReqDaily
	}
	return 0
}

func (m *ApiOrderRequestMessage) GetRateLimitSec() int64 {
	if m != nil {
		return m.RateLimitSec
	}
	return 0
}

func (m *ApiOrderRequestMessage) GetRequestTime() string {
	if m != nil {
		return m.RequestTime
	}
	return ""
}

func (m *ApiOrderRequestMessage) GetOpType() OperationType {
	if m != nil {
		return m.OpType
	}
	return OperationType_not_known
}

func (m *ApiOrderRequestMessage) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ApiOrderRequestMessage) GetMaxReqMonthly() int64 {
	if m != nil {
		return m.MaxReqMonthly
	}
	return 0
}

func (m *ApiOrderRequestMessage) GetAuth() *Authorization {
	if m != nil {
		return m.Auth
	}
	return nil
}

func init() {
	proto.RegisterEnum("apiOrder.ApiOrderStatus", ApiOrderStatus_name, ApiOrderStatus_value)
	proto.RegisterEnum("apiOrder.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("apiOrder.AuthorizationType", AuthorizationType_name, AuthorizationType_value)
	proto.RegisterType((*APIInfo)(nil), "apiOrder.APIInfo")
	proto.RegisterType((*ApiOrderResponseMessage)(nil), "apiOrder.ApiOrderResponseMessage")
	proto.RegisterType((*Authorization)(nil), "apiOrder.authorization")
	proto.RegisterType((*ApiOrderRequestMessage)(nil), "apiOrder.ApiOrderRequestMessage")
}

func init() {
	proto.RegisterFile("api_order", fileDescriptor_b34dd0c9d3ed5285)
}

var fileDescriptor_b34dd0c9d3ed5285 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x51, 0x4f, 0xdb, 0x3c,
	0x14, 0x25, 0x0d, 0xb4, 0xe9, 0x0d, 0xed, 0x17, 0xac, 0x4f, 0x23, 0x1b, 0x0f, 0xeb, 0xba, 0x69,
	0xaa, 0xd8, 0x84, 0x10, 0xd3, 0xb4, 0x67, 0x36, 0xa4, 0xa9, 0xd2, 0x10, 0x28, 0xb0, 0xe7, 0xc8,
	0xd4, 0xb7, 0x60, 0x91, 0xd8, 0xc6, 0x76, 0x06, 0xdd, 0xcb, 0xfe, 0xc4, 0xb4, 0x7f, 0x3b, 0x69,
	0xb2, 0x9b, 0x94, 0x76, 0x48, 0x13, 0x4f, 0xf1, 0x3d, 0x3e, 0xce, 0x3d, 0xf7, 0x9e, 0x03, 0x5d,
	0xaa, 0x78, 0x2e, 0x35, 0x43, 0x4d, 0x22, 0xaa, 0xf8, 0x89, 0x3b, 0x0d, 0x7f, 0x40, 0xe7, 0xf0,
	0x74, 0x3c, 0x16, 0x53, 0x49, 0x5e, 0x41, 0x5f, 0x48, 0x86, 0xb9, 0x9d, 0x29, 0xcc, 0x27, 0x92,
	0x61, 0x1a, 0x0c, 0x82, 0x51, 0x37, 0xdb, 0x74, 0xe8, 0xf9, 0x4c, 0xe1, 0x27, 0xc9, 0x90, 0xbc,
	0x05, 0x72, 0xcf, 0x62, 0x68, 0x26, 0x9a, 0x5f, 0x60, 0xda, 0xf2, 0xcc, 0xa4, 0x61, 0x1e, 0xd5,
	0x38, 0x19, 0x80, 0x7f, 0x9d, 0xbb, 0xd6, 0x95, 0x2e, 0xd2, 0xd0, 0xf3, 0xc0, 0x61, 0x87, 0x8a,
	0x7f, 0xd5, 0xc5, 0xf0, 0x77, 0x00, 0xdb, 0x87, 0xb5, 0x9a, 0x0c, 0x8d, 0x92, 0xc2, 0xe0, 0x31,
	0x1a, 0x43, 0x2f, 0x91, 0x3c, 0x85, 0xc8, 0xeb, 0xcd, 0x39, 0xab, 0xb5, 0x74, 0x7c, 0x3d, 0x66,
	0x64, 0x07, 0xba, 0x74, 0x32, 0x41, 0x63, 0xdc, 0xdd, 0xbc, 0x7b, 0x34, 0x07, 0xc6, 0x8c, 0xbc,
	0x80, 0x4d, 0x8d, 0x37, 0x15, 0x1a, 0x9b, 0x5b, 0x5e, 0x62, 0xdd, 0x35, 0xae, 0xb1, 0x73, 0x5e,
	0x22, 0xd9, 0x87, 0x8e, 0x54, 0x7e, 0x88, 0x74, 0x7d, 0x10, 0x8c, 0xfa, 0x07, 0xdb, 0x7b, 0xcd,
	0x4e, 0xf6, 0x4e, 0x14, 0x6a, 0x6a, 0xb9, 0x14, 0x6e, 0x94, 0xac, 0x2d, 0x95, 0xfb, 0x92, 0x7d,
	0x68, 0x1b, 0x4b, 0x6d, 0x65, 0xd2, 0x0d, 0xff, 0x20, 0xbd, 0x7f, 0xd0, 0xe8, 0x3f, 0xf3, 0xf7,
	0x59, 0xcd, 0x23, 0x2f, 0x21, 0xa4, 0x8a, 0xa7, 0xed, 0x41, 0x38, 0x8a, 0x0f, 0xb6, 0x96, 0xe8,
	0xf3, 0x85, 0x67, 0xee, 0x76, 0xf8, 0x2b, 0x80, 0x1e, 0xad, 0xec, 0x95, 0xd4, 0xfc, 0xbb, 0x6f,
	0x4a, 0x3e, 0x40, 0xe4, 0x00, 0xd7, 0xd4, 0x4f, 0xdd, 0x3f, 0xd8, 0x59, 0x7a, 0xbb, 0x4c, 0xf5,
	0xfa, 0x16, 0x64, 0xf2, 0x0c, 0xa2, 0xca, 0xa0, 0x16, 0xb4, 0x6c, 0x0c, 0x59, 0xd4, 0xee, 0x4e,
	0x51, 0x63, 0x6e, 0xa5, 0x66, 0xf5, 0x3a, 0x16, 0x35, 0xf9, 0x1f, 0x36, 0xac, 0xbc, 0x46, 0xe1,
	0x37, 0xd1, 0xcd, 0xe6, 0xc5, 0xf0, 0x67, 0x08, 0x4f, 0xee, 0x8d, 0xf1, 0x9b, 0x7b, 0x9c, 0x2f,
	0x8b, 0x78, 0x34, 0x22, 0x9a, 0x54, 0xac, 0x9a, 0x16, 0xfe, 0x65, 0xda, 0x73, 0x88, 0xa7, 0x05,
	0xbd, 0xcc, 0x95, 0xc6, 0x29, 0xbf, 0xab, 0xb5, 0x80, 0x83, 0x4e, 0x3d, 0x42, 0x86, 0xd0, 0x2b,
	0xe9, 0x5d, 0xae, 0xf1, 0x26, 0x67, 0x94, 0x17, 0x33, 0xef, 0x43, 0x98, 0xc5, 0x25, 0xbd, 0xcb,
	0xf0, 0xe6, 0xc8, 0x41, 0x2e, 0xc3, 0x9a, 0x5a, 0xcc, 0x0b, 0x5e, 0x72, 0x9b, 0x1b, 0x9c, 0xa4,
	0x6d, 0x4f, 0xda, 0x74, 0xe8, 0x17, 0x07, 0x9e, 0xe1, 0xe4, 0x41, 0x3e, 0x3a, 0xff, 0xcc, 0x47,
	0xf4, 0xb8, 0x7c, 0x24, 0x10, 0x56, 0x9c, 0xa5, 0x5d, 0xff, 0x2f, 0x77, 0x24, 0xaf, 0xe1, 0xbf,
	0x46, 0x70, 0x29, 0x85, 0xbd, 0x2a, 0x66, 0x29, 0x78, 0x35, 0xbd, 0xb9, 0xe4, 0xe3, 0x39, 0x48,
	0xde, 0xc0, 0xba, 0xf3, 0x30, 0x8d, 0x07, 0xc1, 0x28, 0x5e, 0x6e, 0xb4, 0x92, 0x8b, 0xcc, 0x93,
	0x76, 0x3f, 0x43, 0x7f, 0x35, 0x6e, 0x24, 0x86, 0x4e, 0x25, 0xae, 0x85, 0xbc, 0x15, 0xc9, 0x9a,
	0x2b, 0x4c, 0xe5, 0x57, 0x9a, 0x04, 0x24, 0x82, 0xf5, 0x29, 0xe5, 0x45, 0xd2, 0x22, 0x5b, 0xd0,
	0x6b, 0x26, 0x46, 0xad, 0xa5, 0x4e, 0xc2, 0xdd, 0x8f, 0xd0, 0x5b, 0x19, 0x84, 0xf4, 0x9c, 0x75,
	0x36, 0x6f, 0xfe, 0x04, 0xd0, 0xe6, 0xc2, 0xa0, 0xb6, 0x49, 0xe0, 0xce, 0x0c, 0x0b, 0xb4, 0x98,
	0xb4, 0xdc, 0xb9, 0x52, 0x8c, 0x5a, 0x4c, 0xc2, 0xdd, 0xf7, 0xb0, 0xf5, 0x20, 0x90, 0x4e, 0x02,
	0x17, 0xdf, 0x68, 0xc1, 0x59, 0xb2, 0xe6, 0x24, 0xb8, 0x9c, 0x25, 0x01, 0xe9, 0xd6, 0x29, 0x4b,
	0x5a, 0x17, 0x6d, 0xa5, 0xa5, 0x95, 0xef, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x54, 0xe7,
	0xca, 0x92, 0x04, 0x00, 0x00,
}
