// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payr/v1/payr.proto

package gwpayr

import (
	context "context"
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderStatus int32

const (
	OrderStatus_CONFIRMING  OrderStatus = 0
	OrderStatus_CONFIRMED   OrderStatus = 1
	OrderStatus_DEACTIVATED OrderStatus = 2
)

var OrderStatus_name = map[int32]string{
	0: "CONFIRMING",
	1: "CONFIRMED",
	2: "DEACTIVATED",
}

var OrderStatus_value = map[string]int32{
	"CONFIRMING":  0,
	"CONFIRMED":   1,
	"DEACTIVATED": 2,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{0}
}

type PlanStatus int32

const (
	PlanStatus_UNPAID  PlanStatus = 0
	PlanStatus_PAID    PlanStatus = 1
	PlanStatus_EXPRIED PlanStatus = 2
)

var PlanStatus_name = map[int32]string{
	0: "UNPAID",
	1: "PAID",
	2: "EXPRIED",
}

var PlanStatus_value = map[string]int32{
	"UNPAID":  0,
	"PAID":    1,
	"EXPRIED": 2,
}

func (x PlanStatus) String() string {
	return proto.EnumName(PlanStatus_name, int32(x))
}

func (PlanStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{1}
}

type Order struct {
	// order number
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Order type, marking the kind of currency using.
	OrderType string `protobuf:"bytes,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	// How much money left to pay.
	Balance              string      `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Status               OrderStatus `protobuf:"varint,4,opt,name=status,proto3,enum=gwpayr.OrderStatus" json:"status,omitempty"`
	IssuedAt             int64       `protobuf:"varint,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Expiration           int64       `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	TeamId               string      `protobuf:"bytes,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	PlanType             string      `protobuf:"bytes,8,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	Time                 string      `protobuf:"bytes,9,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string      `protobuf:"bytes,10,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	SubId                string      `protobuf:"bytes,11,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	AppId                string      `protobuf:"bytes,12,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_CONFIRMING
}

func (m *Order) GetIssuedAt() int64 {
	if m != nil {
		return m.IssuedAt
	}
	return 0
}

func (m *Order) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *Order) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *Order) GetPlanType() string {
	if m != nil {
		return m.PlanType
	}
	return ""
}

func (m *Order) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Order) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

func (m *Order) GetSubId() string {
	if m != nil {
		return m.SubId
	}
	return ""
}

func (m *Order) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type Subscription struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              string     `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PlanType             string     `protobuf:"bytes,3,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	TeamId               string     `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Status               PlanStatus `protobuf:"varint,5,opt,name=status,proto3,enum=gwpayr.PlanStatus" json:"status,omitempty"`
	IssuedAt             int64      `protobuf:"varint,6,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Time                 string     `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string     `protobuf:"bytes,8,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{1}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Subscription) GetPlanType() string {
	if m != nil {
		return m.PlanType
	}
	return ""
}

func (m *Subscription) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *Subscription) GetStatus() PlanStatus {
	if m != nil {
		return m.Status
	}
	return PlanStatus_UNPAID
}

func (m *Subscription) GetIssuedAt() int64 {
	if m != nil {
		return m.IssuedAt
	}
	return 0
}

func (m *Subscription) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Subscription) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

type PlanType struct {
	PlanType             string   `protobuf:"bytes,1,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	CpuNumber            string   `protobuf:"bytes,2,opt,name=cpu_number,json=cpuNumber,proto3" json:"cpu_number,omitempty"`
	MemoryNumber         string   `protobuf:"bytes,3,opt,name=memory_number,json=memoryNumber,proto3" json:"memory_number,omitempty"`
	StorageNumber        string   `protobuf:"bytes,4,opt,name=storage_number,json=storageNumber,proto3" json:"storage_number,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	PriceWeek            string   `protobuf:"bytes,6,opt,name=price_week,json=priceWeek,proto3" json:"price_week,omitempty"`
	PriceMonth           string   `protobuf:"bytes,7,opt,name=price_month,json=priceMonth,proto3" json:"price_month,omitempty"`
	PriceHour            string   `protobuf:"bytes,8,opt,name=price_hour,json=priceHour,proto3" json:"price_hour,omitempty"`
	PlanTitle            string   `protobuf:"bytes,9,opt,name=plan_title,json=planTitle,proto3" json:"plan_title,omitempty"`
	PlanSet              []string `protobuf:"bytes,10,rep,name=plan_set,json=planSet,proto3" json:"plan_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanType) Reset()         { *m = PlanType{} }
func (m *PlanType) String() string { return proto.CompactTextString(m) }
func (*PlanType) ProtoMessage()    {}
func (*PlanType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{2}
}

func (m *PlanType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanType.Unmarshal(m, b)
}
func (m *PlanType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanType.Marshal(b, m, deterministic)
}
func (m *PlanType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanType.Merge(m, src)
}
func (m *PlanType) XXX_Size() int {
	return xxx_messageInfo_PlanType.Size(m)
}
func (m *PlanType) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanType.DiscardUnknown(m)
}

var xxx_messageInfo_PlanType proto.InternalMessageInfo

func (m *PlanType) GetPlanType() string {
	if m != nil {
		return m.PlanType
	}
	return ""
}

func (m *PlanType) GetCpuNumber() string {
	if m != nil {
		return m.CpuNumber
	}
	return ""
}

func (m *PlanType) GetMemoryNumber() string {
	if m != nil {
		return m.MemoryNumber
	}
	return ""
}

func (m *PlanType) GetStorageNumber() string {
	if m != nil {
		return m.StorageNumber
	}
	return ""
}

func (m *PlanType) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PlanType) GetPriceWeek() string {
	if m != nil {
		return m.PriceWeek
	}
	return ""
}

func (m *PlanType) GetPriceMonth() string {
	if m != nil {
		return m.PriceMonth
	}
	return ""
}

func (m *PlanType) GetPriceHour() string {
	if m != nil {
		return m.PriceHour
	}
	return ""
}

func (m *PlanType) GetPlanTitle() string {
	if m != nil {
		return m.PlanTitle
	}
	return ""
}

func (m *PlanType) GetPlanSet() []string {
	if m != nil {
		return m.PlanSet
	}
	return nil
}

type ListSubsRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubsRequest) Reset()         { *m = ListSubsRequest{} }
func (m *ListSubsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubsRequest) ProtoMessage()    {}
func (*ListSubsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{3}
}

func (m *ListSubsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubsRequest.Unmarshal(m, b)
}
func (m *ListSubsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubsRequest.Merge(m, src)
}
func (m *ListSubsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubsRequest.Size(m)
}
func (m *ListSubsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubsRequest proto.InternalMessageInfo

func (m *ListSubsRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type ListSubsResponse struct {
	Subs                 []*Subscription `protobuf:"bytes,1,rep,name=subs,proto3" json:"subs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSubsResponse) Reset()         { *m = ListSubsResponse{} }
func (m *ListSubsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubsResponse) ProtoMessage()    {}
func (*ListSubsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{4}
}

func (m *ListSubsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubsResponse.Unmarshal(m, b)
}
func (m *ListSubsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubsResponse.Merge(m, src)
}
func (m *ListSubsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubsResponse.Size(m)
}
func (m *ListSubsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubsResponse proto.InternalMessageInfo

func (m *ListSubsResponse) GetSubs() []*Subscription {
	if m != nil {
		return m.Subs
	}
	return nil
}

type ListPlanResponse struct {
	Plans                []*PlanType `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPlanResponse) Reset()         { *m = ListPlanResponse{} }
func (m *ListPlanResponse) String() string { return proto.CompactTextString(m) }
func (*ListPlanResponse) ProtoMessage()    {}
func (*ListPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{5}
}

func (m *ListPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanResponse.Unmarshal(m, b)
}
func (m *ListPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanResponse.Marshal(b, m, deterministic)
}
func (m *ListPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanResponse.Merge(m, src)
}
func (m *ListPlanResponse) XXX_Size() int {
	return xxx_messageInfo_ListPlanResponse.Size(m)
}
func (m *ListPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanResponse proto.InternalMessageInfo

func (m *ListPlanResponse) GetPlans() []*PlanType {
	if m != nil {
		return m.Plans
	}
	return nil
}

type CollectFeeRequest struct {
	CpuNumber            string   `protobuf:"bytes,1,opt,name=cpu_number,json=cpuNumber,proto3" json:"cpu_number,omitempty"`
	MemoryNumber         string   `protobuf:"bytes,2,opt,name=memory_number,json=memoryNumber,proto3" json:"memory_number,omitempty"`
	StorageNumber        string   `protobuf:"bytes,3,opt,name=storage_number,json=storageNumber,proto3" json:"storage_number,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string   `protobuf:"bytes,5,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectFeeRequest) Reset()         { *m = CollectFeeRequest{} }
func (m *CollectFeeRequest) String() string { return proto.CompactTextString(m) }
func (*CollectFeeRequest) ProtoMessage()    {}
func (*CollectFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{6}
}

func (m *CollectFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectFeeRequest.Unmarshal(m, b)
}
func (m *CollectFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectFeeRequest.Marshal(b, m, deterministic)
}
func (m *CollectFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectFeeRequest.Merge(m, src)
}
func (m *CollectFeeRequest) XXX_Size() int {
	return xxx_messageInfo_CollectFeeRequest.Size(m)
}
func (m *CollectFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectFeeRequest proto.InternalMessageInfo

func (m *CollectFeeRequest) GetCpuNumber() string {
	if m != nil {
		return m.CpuNumber
	}
	return ""
}

func (m *CollectFeeRequest) GetMemoryNumber() string {
	if m != nil {
		return m.MemoryNumber
	}
	return ""
}

func (m *CollectFeeRequest) GetStorageNumber() string {
	if m != nil {
		return m.StorageNumber
	}
	return ""
}

func (m *CollectFeeRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *CollectFeeRequest) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

type PlanFeeRequest struct {
	Plan                 string   `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string   `protobuf:"bytes,3,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	TeamId               string   `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanFeeRequest) Reset()         { *m = PlanFeeRequest{} }
func (m *PlanFeeRequest) String() string { return proto.CompactTextString(m) }
func (*PlanFeeRequest) ProtoMessage()    {}
func (*PlanFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{7}
}

func (m *PlanFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanFeeRequest.Unmarshal(m, b)
}
func (m *PlanFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanFeeRequest.Marshal(b, m, deterministic)
}
func (m *PlanFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanFeeRequest.Merge(m, src)
}
func (m *PlanFeeRequest) XXX_Size() int {
	return xxx_messageInfo_PlanFeeRequest.Size(m)
}
func (m *PlanFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlanFeeRequest proto.InternalMessageInfo

func (m *PlanFeeRequest) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *PlanFeeRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *PlanFeeRequest) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

func (m *PlanFeeRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type CollectFeeResponse struct {
	Plan                 string   `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Fee                  string   `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectFeeResponse) Reset()         { *m = CollectFeeResponse{} }
func (m *CollectFeeResponse) String() string { return proto.CompactTextString(m) }
func (*CollectFeeResponse) ProtoMessage()    {}
func (*CollectFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{8}
}

func (m *CollectFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectFeeResponse.Unmarshal(m, b)
}
func (m *CollectFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectFeeResponse.Marshal(b, m, deterministic)
}
func (m *CollectFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectFeeResponse.Merge(m, src)
}
func (m *CollectFeeResponse) XXX_Size() int {
	return xxx_messageInfo_CollectFeeResponse.Size(m)
}
func (m *CollectFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectFeeResponse proto.InternalMessageInfo

func (m *CollectFeeResponse) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *CollectFeeResponse) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

type NewOrderRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Plan                 string   `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string   `protobuf:"bytes,5,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderRequest) Reset()         { *m = NewOrderRequest{} }
func (m *NewOrderRequest) String() string { return proto.CompactTextString(m) }
func (*NewOrderRequest) ProtoMessage()    {}
func (*NewOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{9}
}

func (m *NewOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderRequest.Unmarshal(m, b)
}
func (m *NewOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderRequest.Marshal(b, m, deterministic)
}
func (m *NewOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderRequest.Merge(m, src)
}
func (m *NewOrderRequest) XXX_Size() int {
	return xxx_messageInfo_NewOrderRequest.Size(m)
}
func (m *NewOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderRequest proto.InternalMessageInfo

func (m *NewOrderRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *NewOrderRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewOrderRequest) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *NewOrderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *NewOrderRequest) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

type NewOrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Expiration           int64    `protobuf:"varint,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderResponse) Reset()         { *m = NewOrderResponse{} }
func (m *NewOrderResponse) String() string { return proto.CompactTextString(m) }
func (*NewOrderResponse) ProtoMessage()    {}
func (*NewOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{10}
}

func (m *NewOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderResponse.Unmarshal(m, b)
}
func (m *NewOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderResponse.Marshal(b, m, deterministic)
}
func (m *NewOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderResponse.Merge(m, src)
}
func (m *NewOrderResponse) XXX_Size() int {
	return xxx_messageInfo_NewOrderResponse.Size(m)
}
func (m *NewOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderResponse proto.InternalMessageInfo

func (m *NewOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *NewOrderResponse) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type TeamID struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamID) Reset()         { *m = TeamID{} }
func (m *TeamID) String() string { return proto.CompactTextString(m) }
func (*TeamID) ProtoMessage()    {}
func (*TeamID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{11}
}

func (m *TeamID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamID.Unmarshal(m, b)
}
func (m *TeamID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamID.Marshal(b, m, deterministic)
}
func (m *TeamID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamID.Merge(m, src)
}
func (m *TeamID) XXX_Size() int {
	return xxx_messageInfo_TeamID.Size(m)
}
func (m *TeamID) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamID.DiscardUnknown(m)
}

var xxx_messageInfo_TeamID proto.InternalMessageInfo

func (m *TeamID) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type OrderStatusResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatusResponse) Reset()         { *m = OrderStatusResponse{} }
func (m *OrderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*OrderStatusResponse) ProtoMessage()    {}
func (*OrderStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{12}
}

func (m *OrderStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusResponse.Unmarshal(m, b)
}
func (m *OrderStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusResponse.Marshal(b, m, deterministic)
}
func (m *OrderStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusResponse.Merge(m, src)
}
func (m *OrderStatusResponse) XXX_Size() int {
	return xxx_messageInfo_OrderStatusResponse.Size(m)
}
func (m *OrderStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusResponse proto.InternalMessageInfo

func (m *OrderStatusResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GenerateAddressRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Purpose              string   `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressRequest) Reset()         { *m = GenerateAddressRequest{} }
func (m *GenerateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressRequest) ProtoMessage()    {}
func (*GenerateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{13}
}

func (m *GenerateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressRequest.Unmarshal(m, b)
}
func (m *GenerateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressRequest.Marshal(b, m, deterministic)
}
func (m *GenerateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressRequest.Merge(m, src)
}
func (m *GenerateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressRequest.Size(m)
}
func (m *GenerateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressRequest proto.InternalMessageInfo

func (m *GenerateAddressRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GenerateAddressRequest) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

type GenerateAddressResponse struct {
	Typeaddress          string   `protobuf:"bytes,1,opt,name=typeaddress,proto3" json:"typeaddress,omitempty"`
	Purposeaddress       string   `protobuf:"bytes,2,opt,name=purposeaddress,proto3" json:"purposeaddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressResponse) Reset()         { *m = GenerateAddressResponse{} }
func (m *GenerateAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressResponse) ProtoMessage()    {}
func (*GenerateAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c0d16023c4b7d8, []int{14}
}

func (m *GenerateAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressResponse.Unmarshal(m, b)
}
func (m *GenerateAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressResponse.Marshal(b, m, deterministic)
}
func (m *GenerateAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressResponse.Merge(m, src)
}
func (m *GenerateAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressResponse.Size(m)
}
func (m *GenerateAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressResponse proto.InternalMessageInfo

func (m *GenerateAddressResponse) GetTypeaddress() string {
	if m != nil {
		return m.Typeaddress
	}
	return ""
}

func (m *GenerateAddressResponse) GetPurposeaddress() string {
	if m != nil {
		return m.Purposeaddress
	}
	return ""
}

func init() {
	proto.RegisterEnum("gwpayr.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterEnum("gwpayr.PlanStatus", PlanStatus_name, PlanStatus_value)
	proto.RegisterType((*Order)(nil), "gwpayr.Order")
	proto.RegisterType((*Subscription)(nil), "gwpayr.Subscription")
	proto.RegisterType((*PlanType)(nil), "gwpayr.PlanType")
	proto.RegisterType((*ListSubsRequest)(nil), "gwpayr.ListSubsRequest")
	proto.RegisterType((*ListSubsResponse)(nil), "gwpayr.ListSubsResponse")
	proto.RegisterType((*ListPlanResponse)(nil), "gwpayr.ListPlanResponse")
	proto.RegisterType((*CollectFeeRequest)(nil), "gwpayr.CollectFeeRequest")
	proto.RegisterType((*PlanFeeRequest)(nil), "gwpayr.PlanFeeRequest")
	proto.RegisterType((*CollectFeeResponse)(nil), "gwpayr.CollectFeeResponse")
	proto.RegisterType((*NewOrderRequest)(nil), "gwpayr.NewOrderRequest")
	proto.RegisterType((*NewOrderResponse)(nil), "gwpayr.NewOrderResponse")
	proto.RegisterType((*TeamID)(nil), "gwpayr.TeamID")
	proto.RegisterType((*OrderStatusResponse)(nil), "gwpayr.OrderStatusResponse")
	proto.RegisterType((*GenerateAddressRequest)(nil), "gwpayr.GenerateAddressRequest")
	proto.RegisterType((*GenerateAddressResponse)(nil), "gwpayr.GenerateAddressResponse")
}

func init() { proto.RegisterFile("payr/v1/payr.proto", fileDescriptor_b0c0d16023c4b7d8) }

var fileDescriptor_b0c0d16023c4b7d8 = []byte{
	// 1090 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0xa9, 0xff, 0xa1, 0x25, 0xab, 0x6b, 0x27, 0x66, 0x94, 0xa6, 0x75, 0x37, 0x68, 0x60,
	0xb8, 0x80, 0x89, 0xba, 0x37, 0xa3, 0x3d, 0x18, 0xb6, 0x9c, 0x0a, 0x88, 0x15, 0x85, 0x56, 0xda,
	0xde, 0x04, 0x8a, 0xdc, 0x38, 0x44, 0x24, 0x92, 0xe5, 0x2e, 0xeb, 0xea, 0xda, 0x3e, 0x42, 0x1f,
	0xa4, 0xcf, 0xd0, 0x27, 0xe8, 0xa1, 0x40, 0x9f, 0xa0, 0x97, 0xbe, 0x45, 0xb1, 0xb3, 0x5c, 0x8b,
	0xa2, 0xa5, 0xc6, 0x27, 0x72, 0x67, 0x76, 0xbe, 0xfd, 0xe6, 0x9b, 0xe1, 0x2c, 0x81, 0x24, 0xde,
	0x22, 0x75, 0x7e, 0xfa, 0xd2, 0x91, 0xcf, 0xa3, 0x24, 0x8d, 0x45, 0x4c, 0xea, 0xd7, 0x37, 0x72,
	0xd5, 0xdb, 0xf1, 0xe3, 0xf9, 0x3c, 0x8e, 0x1c, 0xf5, 0x50, 0xce, 0xde, 0xc7, 0xd7, 0x71, 0x7c,
	0x3d, 0x63, 0x8e, 0x97, 0x84, 0x8e, 0x17, 0x45, 0xb1, 0xf0, 0x44, 0x18, 0x47, 0x5c, 0x79, 0xe9,
	0x9f, 0x26, 0xd4, 0x5e, 0xa5, 0x01, 0x4b, 0x49, 0x07, 0xcc, 0x30, 0xb0, 0x8d, 0x7d, 0xe3, 0xa0,
	0xe5, 0x9a, 0x61, 0x40, 0x9e, 0x02, 0xc4, 0xd2, 0x31, 0x11, 0x8b, 0x84, 0xd9, 0x26, 0xda, 0x5b,
	0x68, 0x19, 0x2f, 0x12, 0x46, 0x6c, 0x68, 0x4c, 0xbd, 0x99, 0x17, 0xf9, 0xcc, 0xae, 0xa0, 0x4f,
	0x2f, 0xc9, 0x17, 0x50, 0xe7, 0xc2, 0x13, 0x19, 0xb7, 0xab, 0xfb, 0xc6, 0x41, 0xe7, 0x78, 0xe7,
	0x48, 0xd1, 0x3b, 0xc2, 0x73, 0xae, 0xd0, 0xe5, 0xe6, 0x5b, 0xc8, 0x13, 0x68, 0x85, 0x9c, 0x67,
	0x2c, 0x98, 0x78, 0xc2, 0xae, 0xed, 0x1b, 0x07, 0x15, 0xb7, 0xa9, 0x0c, 0xa7, 0x82, 0x7c, 0x02,
	0xc0, 0x7e, 0x4e, 0xc2, 0x14, 0x19, 0xdb, 0x75, 0xf4, 0x16, 0x2c, 0x64, 0x0f, 0x1a, 0x82, 0x79,
	0xf3, 0x49, 0x18, 0xd8, 0x0d, 0xe4, 0x50, 0x97, 0xcb, 0x41, 0x20, 0x51, 0x93, 0x99, 0x17, 0x29,
	0xea, 0x4d, 0x74, 0x35, 0xa5, 0x01, 0x99, 0x13, 0xa8, 0x8a, 0x70, 0xce, 0xec, 0x16, 0xda, 0xf1,
	0x5d, 0x06, 0xc8, 0xe7, 0x24, 0x8b, 0x42, 0x61, 0x83, 0x0a, 0x90, 0x86, 0x37, 0x51, 0x28, 0xc8,
	0x43, 0xa8, 0xf3, 0x6c, 0x2a, 0x4f, 0xb1, 0xd0, 0x53, 0xe3, 0xd9, 0x74, 0x10, 0x48, 0xb3, 0x97,
	0x24, 0xd2, 0xbc, 0xa5, 0xcc, 0x5e, 0x92, 0x0c, 0x02, 0xfa, 0xaf, 0x01, 0x5b, 0x57, 0xd9, 0x94,
	0xfb, 0x69, 0x98, 0x20, 0xcb, 0xb2, 0xb0, 0x8f, 0xa1, 0xa9, 0x84, 0x0d, 0x83, 0x5c, 0xd6, 0x06,
	0xae, 0xcb, 0xbc, 0x2b, 0x25, 0xde, 0x85, 0x6c, 0xab, 0x2b, 0xd9, 0x1e, 0xde, 0x0a, 0x5e, 0x43,
	0xc1, 0x89, 0x16, 0x7c, 0x34, 0xf3, 0xa2, 0xff, 0xd3, 0xbb, 0x5e, 0xd2, 0x5b, 0x2b, 0xd3, 0xd8,
	0xa4, 0x4c, 0x73, 0x55, 0x19, 0xfa, 0x87, 0x09, 0xcd, 0x91, 0xe6, 0xb7, 0x42, 0xde, 0x28, 0x91,
	0x7f, 0x0a, 0xe0, 0x27, 0xd9, 0x24, 0xca, 0xe6, 0x53, 0x96, 0xea, 0x6e, 0xf2, 0x93, 0x6c, 0x88,
	0x06, 0xf2, 0x0c, 0xda, 0x73, 0x36, 0x8f, 0xd3, 0x85, 0xde, 0xa1, 0x92, 0xdf, 0x52, 0xc6, 0x7c,
	0xd3, 0xe7, 0xd0, 0xe1, 0x22, 0x4e, 0xbd, 0x6b, 0xa6, 0x77, 0x29, 0x1d, 0xda, 0xb9, 0x35, 0xdf,
	0xb6, 0x0b, 0xb5, 0x24, 0x0d, 0x7d, 0x86, 0x6a, 0xb4, 0x5c, 0xb5, 0x90, 0x04, 0xf0, 0x65, 0x72,
	0xc3, 0xd8, 0x7b, 0xcc, 0xbc, 0xe5, 0xb6, 0xd0, 0xf2, 0x3d, 0x63, 0xef, 0xc9, 0xa7, 0x60, 0x29,
	0xf7, 0x3c, 0x8e, 0xc4, 0xbb, 0x5c, 0x01, 0x15, 0x71, 0x29, 0x2d, 0xcb, 0xf8, 0x77, 0x71, 0x96,
	0xe6, 0x42, 0xa8, 0xf8, 0x6f, 0xe3, 0x2c, 0x45, 0x37, 0x26, 0x1f, 0x8a, 0x99, 0x6e, 0x2d, 0x94,
	0x63, 0x2c, 0x0d, 0xb2, 0xe6, 0xe8, 0xe6, 0x4c, 0xb6, 0x57, 0x45, 0xd6, 0x5c, 0xae, 0xaf, 0x98,
	0xa0, 0x87, 0xb0, 0xfd, 0x32, 0xe4, 0x42, 0xb6, 0x8c, 0xcb, 0x7e, 0xcc, 0x18, 0x17, 0xc5, 0x4a,
	0x1b, 0xc5, 0x4a, 0xd3, 0xaf, 0xa1, 0xbb, 0xdc, 0xcb, 0x93, 0x38, 0xe2, 0x8c, 0x1c, 0x40, 0x95,
	0x67, 0x53, 0x6e, 0x1b, 0xfb, 0x95, 0x03, 0xeb, 0x78, 0x57, 0xd7, 0xbe, 0xd8, 0x82, 0x2e, 0xee,
	0xa0, 0x27, 0x2a, 0x5a, 0x16, 0xec, 0x36, 0xfa, 0x39, 0xd4, 0x24, 0x11, 0x1d, 0xde, 0x2d, 0xb6,
	0x8e, 0x2c, 0x9c, 0xab, 0xdc, 0xf4, 0x77, 0x03, 0x3e, 0x3a, 0x8b, 0x67, 0x33, 0xe6, 0x8b, 0x0b,
	0xc6, 0x34, 0xd1, 0xd5, 0xaa, 0x1a, 0x1f, 0xac, 0xaa, 0x79, 0xaf, 0xaa, 0x56, 0xd6, 0x55, 0x55,
	0xf7, 0x66, 0x75, 0x53, 0x6f, 0xd6, 0x4a, 0xbd, 0x19, 0x41, 0x47, 0x26, 0x51, 0x60, 0x4b, 0xa0,
	0x2a, 0x93, 0xc9, 0x79, 0xe2, 0xfb, 0x2d, 0xac, 0xb9, 0x09, 0xb6, 0x52, 0x1a, 0x06, 0x9b, 0xbe,
	0x42, 0x7a, 0x02, 0xa4, 0x28, 0x50, 0xae, 0xef, 0xba, 0x33, 0xbb, 0x50, 0x79, 0xcb, 0xf4, 0x91,
	0xf2, 0x95, 0xfe, 0x6a, 0xc0, 0xf6, 0x90, 0xdd, 0xe0, 0x80, 0xfc, 0x50, 0x13, 0x20, 0xe5, 0xe5,
	0x48, 0xc6, 0xf7, 0xdb, 0x63, 0x2a, 0x6b, 0x52, 0xbb, 0xb7, 0x62, 0x97, 0xd0, 0x5d, 0x92, 0xc8,
	0xf9, 0x17, 0x87, 0x95, 0xb1, 0x3a, 0xac, 0x56, 0xa7, 0xb3, 0x59, 0x9e, 0xce, 0xf4, 0x33, 0xa8,
	0x8f, 0x25, 0xe3, 0xf3, 0xcd, 0xfd, 0x7c, 0x02, 0x3b, 0xc5, 0x4b, 0x41, 0x1f, 0xfa, 0x0c, 0x6a,
	0x78, 0x08, 0xee, 0xb6, 0x8e, 0xdb, 0x2b, 0x17, 0x88, 0xab, 0x7c, 0xf4, 0x02, 0x1e, 0xbd, 0x60,
	0x11, 0x4b, 0x3d, 0xc1, 0x4e, 0x83, 0x20, 0x65, 0x9c, 0x17, 0xea, 0x5c, 0x98, 0x41, 0x4a, 0x20,
	0x1b, 0x1a, 0x49, 0x96, 0x26, 0x31, 0xd7, 0xba, 0xe9, 0x25, 0xf5, 0x61, 0xef, 0x0e, 0x4e, 0xce,
	0x63, 0x1f, 0x2c, 0x19, 0xec, 0x29, 0x73, 0x8e, 0x57, 0x34, 0x91, 0xe7, 0xd0, 0xc9, 0x71, 0xf4,
	0x26, 0x85, 0x5e, 0xb2, 0x1e, 0x7e, 0x03, 0x56, 0x21, 0x51, 0xd2, 0x01, 0x38, 0x7b, 0x35, 0xbc,
	0x18, 0xb8, 0x97, 0x83, 0xe1, 0x8b, 0xee, 0x03, 0xd2, 0x86, 0x56, 0xbe, 0xee, 0x9f, 0x77, 0x0d,
	0xb2, 0x0d, 0xd6, 0x79, 0xff, 0xf4, 0x6c, 0x3c, 0xf8, 0xee, 0x74, 0xdc, 0x3f, 0xef, 0x9a, 0x87,
	0x0e, 0xc0, 0x72, 0x96, 0x13, 0x80, 0xfa, 0x9b, 0xe1, 0xe8, 0x74, 0x70, 0xde, 0x7d, 0x40, 0x9a,
	0x50, 0xc5, 0x37, 0x83, 0x58, 0xd0, 0xe8, 0xff, 0x30, 0x72, 0x07, 0x32, 0xe0, 0xf8, 0xef, 0x2a,
	0x54, 0x47, 0xde, 0x22, 0x25, 0x13, 0x80, 0x65, 0x57, 0x92, 0xc7, 0x5a, 0xc9, 0x3b, 0x9f, 0x72,
	0xaf, 0xb7, 0xce, 0xa5, 0x74, 0xa0, 0xbd, 0x5f, 0xfe, 0xfa, 0xe7, 0x37, 0x73, 0x97, 0x6e, 0x3b,
	0x6f, 0x19, 0x73, 0x7c, 0xb5, 0x21, 0x8c, 0xa3, 0x13, 0xe3, 0x90, 0x5c, 0x41, 0x23, 0xff, 0xcc,
	0xc8, 0xa3, 0xe2, 0xf0, 0xb8, 0x27, 0xf4, 0x2e, 0x42, 0x77, 0x68, 0x0b, 0xa1, 0x65, 0xdf, 0x4a,
	0xd0, 0x31, 0x34, 0x75, 0x27, 0x92, 0x3d, 0x1d, 0x5d, 0xfa, 0x40, 0x7a, 0xf6, 0x5d, 0x47, 0x0e,
	0xfa, 0x10, 0x41, 0xb7, 0x29, 0x38, 0xd8, 0x2a, 0x4e, 0xc4, 0x6e, 0x24, 0xea, 0xeb, 0x52, 0x11,
	0x74, 0xbc, 0xea, 0xd2, 0xde, 0x93, 0x75, 0xff, 0x29, 0x25, 0x48, 0xd2, 0xce, 0x21, 0xf3, 0xeb,
	0xf4, 0x25, 0x58, 0x67, 0xf2, 0xa7, 0x67, 0x96, 0xff, 0x43, 0x95, 0x20, 0x77, 0x8e, 0x8a, 0xbf,
	0x62, 0x47, 0xfd, 0x79, 0x22, 0x16, 0xd4, 0x46, 0x28, 0x42, 0x35, 0x94, 0x8f, 0x00, 0x92, 0xe0,
	0x10, 0x9a, 0x7a, 0x40, 0x93, 0x75, 0xa1, 0xcb, 0x94, 0xcb, 0x73, 0x9c, 0xee, 0x20, 0x68, 0x9b,
	0x58, 0xa8, 0x21, 0x77, 0x66, 0x21, 0x17, 0xe4, 0xb5, 0xc2, 0x93, 0x57, 0xc1, 0x52, 0xc6, 0xd2,
	0x65, 0xb3, 0x8a, 0x59, 0xbc, 0x59, 0x28, 0x41, 0xcc, 0x2d, 0x02, 0x8e, 0xbc, 0x3e, 0x10, 0x72,
	0x5a, 0x47, 0x3a, 0x5f, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x06, 0x5b, 0x49, 0x2f, 0x87, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayrClient is the client API for Payr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayrClient interface {
	CollectFee(ctx context.Context, in *CollectFeeRequest, opts ...grpc.CallOption) (*CollectFeeResponse, error)
	PlanFee(ctx context.Context, in *PlanFeeRequest, opts ...grpc.CallOption) (*CollectFeeResponse, error)
	NewOrder(ctx context.Context, in *NewOrderRequest, opts ...grpc.CallOption) (*NewOrderResponse, error)
	OrderStatus(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*OrderStatusResponse, error)
	CancelOrder(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*common.Empty, error)
	ListPlan(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListPlanResponse, error)
	ListSubs(ctx context.Context, in *ListSubsRequest, opts ...grpc.CallOption) (*ListSubsResponse, error)
}

type payrClient struct {
	cc *grpc.ClientConn
}

func NewPayrClient(cc *grpc.ClientConn) PayrClient {
	return &payrClient{cc}
}

func (c *payrClient) CollectFee(ctx context.Context, in *CollectFeeRequest, opts ...grpc.CallOption) (*CollectFeeResponse, error) {
	out := new(CollectFeeResponse)
	err := c.cc.Invoke(ctx, "/gwpayr.Payr/CollectFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrClient) PlanFee(ctx context.Context, in *PlanFeeRequest, opts ...grpc.CallOption) (*CollectFeeResponse, error) {
	out := new(CollectFeeResponse)
	err := c.cc.Invoke(ctx, "/gwpayr.Payr/PlanFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrClient) NewOrder(ctx context.Context, in *NewOrderRequest, opts ...grpc.CallOption) (*NewOrderResponse, error) {
	out := new(NewOrderResponse)
	err := c.cc.Invoke(ctx, "/gwpayr.Payr/NewOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrClient) OrderStatus(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*OrderStatusResponse, error) {
	out := new(OrderStatusResponse)
	err := c.cc.Invoke(ctx, "/gwpayr.Payr/OrderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrClient) CancelOrder(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwpayr.Payr/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrClient) ListPlan(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListPlanResponse, error) {
	out := new(ListPlanResponse)
	err := c.cc.Invoke(ctx, "/gwpayr.Payr/ListPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrClient) ListSubs(ctx context.Context, in *ListSubsRequest, opts ...grpc.CallOption) (*ListSubsResponse, error) {
	out := new(ListSubsResponse)
	err := c.cc.Invoke(ctx, "/gwpayr.Payr/ListSubs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayrServer is the server API for Payr service.
type PayrServer interface {
	CollectFee(context.Context, *CollectFeeRequest) (*CollectFeeResponse, error)
	PlanFee(context.Context, *PlanFeeRequest) (*CollectFeeResponse, error)
	NewOrder(context.Context, *NewOrderRequest) (*NewOrderResponse, error)
	OrderStatus(context.Context, *TeamID) (*OrderStatusResponse, error)
	CancelOrder(context.Context, *TeamID) (*common.Empty, error)
	ListPlan(context.Context, *common.Empty) (*ListPlanResponse, error)
	ListSubs(context.Context, *ListSubsRequest) (*ListSubsResponse, error)
}

// UnimplementedPayrServer can be embedded to have forward compatible implementations.
type UnimplementedPayrServer struct {
}

func (*UnimplementedPayrServer) CollectFee(ctx context.Context, req *CollectFeeRequest) (*CollectFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectFee not implemented")
}
func (*UnimplementedPayrServer) PlanFee(ctx context.Context, req *PlanFeeRequest) (*CollectFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanFee not implemented")
}
func (*UnimplementedPayrServer) NewOrder(ctx context.Context, req *NewOrderRequest) (*NewOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOrder not implemented")
}
func (*UnimplementedPayrServer) OrderStatus(ctx context.Context, req *TeamID) (*OrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderStatus not implemented")
}
func (*UnimplementedPayrServer) CancelOrder(ctx context.Context, req *TeamID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (*UnimplementedPayrServer) ListPlan(ctx context.Context, req *common.Empty) (*ListPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlan not implemented")
}
func (*UnimplementedPayrServer) ListSubs(ctx context.Context, req *ListSubsRequest) (*ListSubsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubs not implemented")
}

func RegisterPayrServer(s *grpc.Server, srv PayrServer) {
	s.RegisterService(&_Payr_serviceDesc, srv)
}

func _Payr_CollectFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrServer).CollectFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwpayr.Payr/CollectFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrServer).CollectFee(ctx, req.(*CollectFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payr_PlanFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrServer).PlanFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwpayr.Payr/PlanFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrServer).PlanFee(ctx, req.(*PlanFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payr_NewOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrServer).NewOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwpayr.Payr/NewOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrServer).NewOrder(ctx, req.(*NewOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payr_OrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrServer).OrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwpayr.Payr/OrderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrServer).OrderStatus(ctx, req.(*TeamID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payr_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwpayr.Payr/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrServer).CancelOrder(ctx, req.(*TeamID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payr_ListPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrServer).ListPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwpayr.Payr/ListPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrServer).ListPlan(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payr_ListSubs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrServer).ListSubs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwpayr.Payr/ListSubs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrServer).ListSubs(ctx, req.(*ListSubsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gwpayr.Payr",
	HandlerType: (*PayrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectFee",
			Handler:    _Payr_CollectFee_Handler,
		},
		{
			MethodName: "PlanFee",
			Handler:    _Payr_PlanFee_Handler,
		},
		{
			MethodName: "NewOrder",
			Handler:    _Payr_NewOrder_Handler,
		},
		{
			MethodName: "OrderStatus",
			Handler:    _Payr_OrderStatus_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Payr_CancelOrder_Handler,
		},
		{
			MethodName: "ListPlan",
			Handler:    _Payr_ListPlan_Handler,
		},
		{
			MethodName: "ListSubs",
			Handler:    _Payr_ListSubs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payr/v1/payr.proto",
}
