// Code generated by protoc-gen-go. DO NOT EDIT.
// source: teammgr/v1/teammgr.proto

package gwteammgr

import (
	context "context"
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamMemberStatus int32

const (
	TeamMemberStatus_INVITED   TeamMemberStatus = 0
	TeamMemberStatus_CONFIRMED TeamMemberStatus = 1
)

var TeamMemberStatus_name = map[int32]string{
	0: "INVITED",
	1: "CONFIRMED",
}

var TeamMemberStatus_value = map[string]int32{
	"INVITED":   0,
	"CONFIRMED": 1,
}

func (x TeamMemberStatus) String() string {
	return proto.EnumName(TeamMemberStatus_name, int32(x))
}

func (TeamMemberStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{0}
}

type CreateTeamRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTeamRequest) Reset()         { *m = CreateTeamRequest{} }
func (m *CreateTeamRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTeamRequest) ProtoMessage()    {}
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{0}
}

func (m *CreateTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamRequest.Unmarshal(m, b)
}
func (m *CreateTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamRequest.Marshal(b, m, deterministic)
}
func (m *CreateTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamRequest.Merge(m, src)
}
func (m *CreateTeamRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTeamRequest.Size(m)
}
func (m *CreateTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamRequest proto.InternalMessageInfo

func (m *CreateTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Team struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{1}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TeamID struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamID) Reset()         { *m = TeamID{} }
func (m *TeamID) String() string { return proto.CompactTextString(m) }
func (*TeamID) ProtoMessage()    {}
func (*TeamID) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{2}
}

func (m *TeamID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamID.Unmarshal(m, b)
}
func (m *TeamID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamID.Marshal(b, m, deterministic)
}
func (m *TeamID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamID.Merge(m, src)
}
func (m *TeamID) XXX_Size() int {
	return xxx_messageInfo_TeamID.Size(m)
}
func (m *TeamID) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamID.DiscardUnknown(m)
}

var xxx_messageInfo_TeamID proto.InternalMessageInfo

func (m *TeamID) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type UserTeamInfo struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName             string   `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleId               string   `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Current              bool     `protobuf:"varint,5,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTeamInfo) Reset()         { *m = UserTeamInfo{} }
func (m *UserTeamInfo) String() string { return proto.CompactTextString(m) }
func (*UserTeamInfo) ProtoMessage()    {}
func (*UserTeamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{3}
}

func (m *UserTeamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTeamInfo.Unmarshal(m, b)
}
func (m *UserTeamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTeamInfo.Marshal(b, m, deterministic)
}
func (m *UserTeamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTeamInfo.Merge(m, src)
}
func (m *UserTeamInfo) XXX_Size() int {
	return xxx_messageInfo_UserTeamInfo.Size(m)
}
func (m *UserTeamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTeamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserTeamInfo proto.InternalMessageInfo

func (m *UserTeamInfo) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *UserTeamInfo) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *UserTeamInfo) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UserTeamInfo) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *UserTeamInfo) GetCurrent() bool {
	if m != nil {
		return m.Current
	}
	return false
}

type ListUserTeamsResponse struct {
	Teams                []*UserTeamInfo `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUserTeamsResponse) Reset()         { *m = ListUserTeamsResponse{} }
func (m *ListUserTeamsResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserTeamsResponse) ProtoMessage()    {}
func (*ListUserTeamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{4}
}

func (m *ListUserTeamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserTeamsResponse.Unmarshal(m, b)
}
func (m *ListUserTeamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserTeamsResponse.Marshal(b, m, deterministic)
}
func (m *ListUserTeamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserTeamsResponse.Merge(m, src)
}
func (m *ListUserTeamsResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserTeamsResponse.Size(m)
}
func (m *ListUserTeamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserTeamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserTeamsResponse proto.InternalMessageInfo

func (m *ListUserTeamsResponse) GetTeams() []*UserTeamInfo {
	if m != nil {
		return m.Teams
	}
	return nil
}

type InviteTeamMemberRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteTeamMemberRequest) Reset()         { *m = InviteTeamMemberRequest{} }
func (m *InviteTeamMemberRequest) String() string { return proto.CompactTextString(m) }
func (*InviteTeamMemberRequest) ProtoMessage()    {}
func (*InviteTeamMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{5}
}

func (m *InviteTeamMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteTeamMemberRequest.Unmarshal(m, b)
}
func (m *InviteTeamMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteTeamMemberRequest.Marshal(b, m, deterministic)
}
func (m *InviteTeamMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteTeamMemberRequest.Merge(m, src)
}
func (m *InviteTeamMemberRequest) XXX_Size() int {
	return xxx_messageInfo_InviteTeamMemberRequest.Size(m)
}
func (m *InviteTeamMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteTeamMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteTeamMemberRequest proto.InternalMessageInfo

func (m *InviteTeamMemberRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteTeamMemberRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type ConfirmTeamMemberRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmTeamMemberRequest) Reset()         { *m = ConfirmTeamMemberRequest{} }
func (m *ConfirmTeamMemberRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmTeamMemberRequest) ProtoMessage()    {}
func (*ConfirmTeamMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{6}
}

func (m *ConfirmTeamMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmTeamMemberRequest.Unmarshal(m, b)
}
func (m *ConfirmTeamMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmTeamMemberRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmTeamMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmTeamMemberRequest.Merge(m, src)
}
func (m *ConfirmTeamMemberRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmTeamMemberRequest.Size(m)
}
func (m *ConfirmTeamMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmTeamMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmTeamMemberRequest proto.InternalMessageInfo

func (m *ConfirmTeamMemberRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *ConfirmTeamMemberRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type TeamMember struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string           `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string           `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	RoleName             string           `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleId               string           `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status               TeamMemberStatus `protobuf:"varint,6,opt,name=status,proto3,enum=gwteammgr.TeamMemberStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TeamMember) Reset()         { *m = TeamMember{} }
func (m *TeamMember) String() string { return proto.CompactTextString(m) }
func (*TeamMember) ProtoMessage()    {}
func (*TeamMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{7}
}

func (m *TeamMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamMember.Unmarshal(m, b)
}
func (m *TeamMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamMember.Marshal(b, m, deterministic)
}
func (m *TeamMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamMember.Merge(m, src)
}
func (m *TeamMember) XXX_Size() int {
	return xxx_messageInfo_TeamMember.Size(m)
}
func (m *TeamMember) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamMember.DiscardUnknown(m)
}

var xxx_messageInfo_TeamMember proto.InternalMessageInfo

func (m *TeamMember) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TeamMember) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *TeamMember) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TeamMember) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *TeamMember) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *TeamMember) GetStatus() TeamMemberStatus {
	if m != nil {
		return m.Status
	}
	return TeamMemberStatus_INVITED
}

type ListTeamMembersResponse struct {
	Members              []*TeamMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListTeamMembersResponse) Reset()         { *m = ListTeamMembersResponse{} }
func (m *ListTeamMembersResponse) String() string { return proto.CompactTextString(m) }
func (*ListTeamMembersResponse) ProtoMessage()    {}
func (*ListTeamMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{8}
}

func (m *ListTeamMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTeamMembersResponse.Unmarshal(m, b)
}
func (m *ListTeamMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTeamMembersResponse.Marshal(b, m, deterministic)
}
func (m *ListTeamMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTeamMembersResponse.Merge(m, src)
}
func (m *ListTeamMembersResponse) XXX_Size() int {
	return xxx_messageInfo_ListTeamMembersResponse.Size(m)
}
func (m *ListTeamMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTeamMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTeamMembersResponse proto.InternalMessageInfo

func (m *ListTeamMembersResponse) GetMembers() []*TeamMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type DeleteTeamMemberRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTeamMemberRequest) Reset()         { *m = DeleteTeamMemberRequest{} }
func (m *DeleteTeamMemberRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTeamMemberRequest) ProtoMessage()    {}
func (*DeleteTeamMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{9}
}

func (m *DeleteTeamMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeamMemberRequest.Unmarshal(m, b)
}
func (m *DeleteTeamMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeamMemberRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTeamMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeamMemberRequest.Merge(m, src)
}
func (m *DeleteTeamMemberRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTeamMemberRequest.Size(m)
}
func (m *DeleteTeamMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeamMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeamMemberRequest proto.InternalMessageInfo

func (m *DeleteTeamMemberRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DeleteTeamMemberRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type CreateRoleRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Privileges           []string `protobuf:"bytes,3,rep,name=privileges,proto3" json:"privileges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{10}
}

func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(m, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *CreateRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CreateRoleRequest) GetPrivileges() []string {
	if m != nil {
		return m.Privileges
	}
	return nil
}

type RoleID struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleID) Reset()         { *m = RoleID{} }
func (m *RoleID) String() string { return proto.CompactTextString(m) }
func (*RoleID) ProtoMessage()    {}
func (*RoleID) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{11}
}

func (m *RoleID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleID.Unmarshal(m, b)
}
func (m *RoleID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleID.Marshal(b, m, deterministic)
}
func (m *RoleID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleID.Merge(m, src)
}
func (m *RoleID) XXX_Size() int {
	return xxx_messageInfo_RoleID.Size(m)
}
func (m *RoleID) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleID.DiscardUnknown(m)
}

var xxx_messageInfo_RoleID proto.InternalMessageInfo

func (m *RoleID) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Privileges           []string `protobuf:"bytes,3,rep,name=privileges,proto3" json:"privileges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{12}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetPrivileges() []string {
	if m != nil {
		return m.Privileges
	}
	return nil
}

type GetUserRoleResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Role                 *Role    `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRoleResponse) Reset()         { *m = GetUserRoleResponse{} }
func (m *GetUserRoleResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserRoleResponse) ProtoMessage()    {}
func (*GetUserRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{13}
}

func (m *GetUserRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRoleResponse.Unmarshal(m, b)
}
func (m *GetUserRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRoleResponse.Marshal(b, m, deterministic)
}
func (m *GetUserRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRoleResponse.Merge(m, src)
}
func (m *GetUserRoleResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserRoleResponse.Size(m)
}
func (m *GetUserRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRoleResponse proto.InternalMessageInfo

func (m *GetUserRoleResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetUserRoleResponse) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *GetUserRoleResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type UpdateTeamMemberRoleRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RoleId               string   `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTeamMemberRoleRequest) Reset()         { *m = UpdateTeamMemberRoleRequest{} }
func (m *UpdateTeamMemberRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamMemberRoleRequest) ProtoMessage()    {}
func (*UpdateTeamMemberRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{14}
}

func (m *UpdateTeamMemberRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamMemberRoleRequest.Unmarshal(m, b)
}
func (m *UpdateTeamMemberRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamMemberRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTeamMemberRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamMemberRoleRequest.Merge(m, src)
}
func (m *UpdateTeamMemberRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamMemberRoleRequest.Size(m)
}
func (m *UpdateTeamMemberRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamMemberRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamMemberRoleRequest proto.InternalMessageInfo

func (m *UpdateTeamMemberRoleRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateTeamMemberRoleRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *UpdateTeamMemberRoleRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type SetUserCurrentTeamRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserCurrentTeamRequest) Reset()         { *m = SetUserCurrentTeamRequest{} }
func (m *SetUserCurrentTeamRequest) String() string { return proto.CompactTextString(m) }
func (*SetUserCurrentTeamRequest) ProtoMessage()    {}
func (*SetUserCurrentTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{15}
}

func (m *SetUserCurrentTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserCurrentTeamRequest.Unmarshal(m, b)
}
func (m *SetUserCurrentTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserCurrentTeamRequest.Marshal(b, m, deterministic)
}
func (m *SetUserCurrentTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserCurrentTeamRequest.Merge(m, src)
}
func (m *SetUserCurrentTeamRequest) XXX_Size() int {
	return xxx_messageInfo_SetUserCurrentTeamRequest.Size(m)
}
func (m *SetUserCurrentTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserCurrentTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserCurrentTeamRequest proto.InternalMessageInfo

func (m *SetUserCurrentTeamRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SetUserCurrentTeamRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type CheckUserAccessRequest struct {
	Resource             string   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserAccessRequest) Reset()         { *m = CheckUserAccessRequest{} }
func (m *CheckUserAccessRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUserAccessRequest) ProtoMessage()    {}
func (*CheckUserAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{16}
}

func (m *CheckUserAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserAccessRequest.Unmarshal(m, b)
}
func (m *CheckUserAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserAccessRequest.Marshal(b, m, deterministic)
}
func (m *CheckUserAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserAccessRequest.Merge(m, src)
}
func (m *CheckUserAccessRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUserAccessRequest.Size(m)
}
func (m *CheckUserAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserAccessRequest proto.InternalMessageInfo

func (m *CheckUserAccessRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *CheckUserAccessRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type CheckUserAccessResponse struct {
	Accessible           bool     `protobuf:"varint,1,opt,name=accessible,proto3" json:"accessible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserAccessResponse) Reset()         { *m = CheckUserAccessResponse{} }
func (m *CheckUserAccessResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUserAccessResponse) ProtoMessage()    {}
func (*CheckUserAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c4b0d2adf8260a, []int{17}
}

func (m *CheckUserAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserAccessResponse.Unmarshal(m, b)
}
func (m *CheckUserAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserAccessResponse.Marshal(b, m, deterministic)
}
func (m *CheckUserAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserAccessResponse.Merge(m, src)
}
func (m *CheckUserAccessResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUserAccessResponse.Size(m)
}
func (m *CheckUserAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserAccessResponse proto.InternalMessageInfo

func (m *CheckUserAccessResponse) GetAccessible() bool {
	if m != nil {
		return m.Accessible
	}
	return false
}

func init() {
	proto.RegisterEnum("gwteammgr.TeamMemberStatus", TeamMemberStatus_name, TeamMemberStatus_value)
	proto.RegisterType((*CreateTeamRequest)(nil), "gwteammgr.CreateTeamRequest")
	proto.RegisterType((*Team)(nil), "gwteammgr.Team")
	proto.RegisterType((*TeamID)(nil), "gwteammgr.TeamID")
	proto.RegisterType((*UserTeamInfo)(nil), "gwteammgr.UserTeamInfo")
	proto.RegisterType((*ListUserTeamsResponse)(nil), "gwteammgr.ListUserTeamsResponse")
	proto.RegisterType((*InviteTeamMemberRequest)(nil), "gwteammgr.InviteTeamMemberRequest")
	proto.RegisterType((*ConfirmTeamMemberRequest)(nil), "gwteammgr.ConfirmTeamMemberRequest")
	proto.RegisterType((*TeamMember)(nil), "gwteammgr.TeamMember")
	proto.RegisterType((*ListTeamMembersResponse)(nil), "gwteammgr.ListTeamMembersResponse")
	proto.RegisterType((*DeleteTeamMemberRequest)(nil), "gwteammgr.DeleteTeamMemberRequest")
	proto.RegisterType((*CreateRoleRequest)(nil), "gwteammgr.CreateRoleRequest")
	proto.RegisterType((*RoleID)(nil), "gwteammgr.RoleID")
	proto.RegisterType((*Role)(nil), "gwteammgr.Role")
	proto.RegisterType((*GetUserRoleResponse)(nil), "gwteammgr.GetUserRoleResponse")
	proto.RegisterType((*UpdateTeamMemberRoleRequest)(nil), "gwteammgr.UpdateTeamMemberRoleRequest")
	proto.RegisterType((*SetUserCurrentTeamRequest)(nil), "gwteammgr.SetUserCurrentTeamRequest")
	proto.RegisterType((*CheckUserAccessRequest)(nil), "gwteammgr.CheckUserAccessRequest")
	proto.RegisterType((*CheckUserAccessResponse)(nil), "gwteammgr.CheckUserAccessResponse")
}

func init() { proto.RegisterFile("teammgr/v1/teammgr.proto", fileDescriptor_74c4b0d2adf8260a) }

var fileDescriptor_74c4b0d2adf8260a = []byte{
	// 975 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x25, 0x59, 0xb2, 0xc6, 0x76, 0x2c, 0x8d, 0x93, 0x90, 0x95, 0x53, 0x43, 0xd9, 0x14,
	0xad, 0x60, 0xa0, 0x22, 0xea, 0x14, 0x05, 0xd2, 0x97, 0xa2, 0x90, 0x6c, 0x97, 0x69, 0xec, 0x02,
	0xcc, 0xcf, 0x43, 0x5e, 0x0a, 0x8a, 0xda, 0xa8, 0x4c, 0x45, 0x52, 0xe5, 0x52, 0x2e, 0xfa, 0xda,
	0x2b, 0xb4, 0xc7, 0xe9, 0x2d, 0x72, 0x85, 0x1e, 0x24, 0xd8, 0x5d, 0x52, 0x5c, 0xfe, 0x21, 0xf6,
	0x93, 0xb8, 0xbb, 0x33, 0xdf, 0xec, 0x7c, 0xb3, 0xf3, 0x8d, 0xc0, 0x88, 0xa9, 0xe3, 0xfb, 0xcb,
	0xc8, 0xbc, 0xf9, 0xc6, 0x4c, 0x3e, 0x27, 0xeb, 0x28, 0x8c, 0x43, 0xec, 0x2d, 0xff, 0x4c, 0x36,
	0x86, 0x8f, 0x96, 0x61, 0xb8, 0x5c, 0x51, 0xd3, 0x59, 0x7b, 0xa6, 0x13, 0x04, 0x61, 0xec, 0xc4,
	0x5e, 0x18, 0x30, 0x69, 0x38, 0x3c, 0x72, 0x43, 0xdf, 0x0f, 0x03, 0x53, 0xfe, 0xc8, 0x4d, 0xf2,
	0x15, 0x0c, 0xa6, 0x11, 0x75, 0x62, 0xfa, 0x8a, 0x3a, 0xbe, 0x4d, 0xff, 0xd8, 0x50, 0x16, 0x23,
	0x42, 0x3b, 0x70, 0x7c, 0x6a, 0x68, 0x23, 0x6d, 0xdc, 0xb3, 0xc5, 0x37, 0x39, 0x85, 0x36, 0x37,
	0xc1, 0x7b, 0xd0, 0xf4, 0x16, 0xc9, 0x49, 0xd3, 0x5b, 0x6c, 0x6d, 0x9b, 0x8a, 0xed, 0x63, 0xe8,
	0x70, 0x5b, 0x6b, 0x86, 0x3a, 0x74, 0xf9, 0xe5, 0x7e, 0xdd, 0xba, 0x74, 0xf8, 0xd2, 0x5a, 0x90,
	0x7f, 0x35, 0xd8, 0x7f, 0xcd, 0x68, 0x24, 0xec, 0x82, 0x77, 0x61, 0xad, 0x25, 0x1e, 0x43, 0x4f,
	0x1c, 0x28, 0x51, 0x76, 0xf9, 0xc6, 0xb5, 0xe3, 0x53, 0x7e, 0x18, 0x85, 0x2b, 0x2a, 0x0f, 0x5b,
	0xf2, 0x90, 0x6f, 0x88, 0x43, 0x1d, 0xba, 0xe2, 0xd0, 0x5b, 0x18, 0x6d, 0x09, 0xc9, 0x97, 0xd6,
	0x02, 0x0d, 0xe8, 0xba, 0x9b, 0x28, 0xa2, 0x41, 0x6c, 0xec, 0x8c, 0xb4, 0xf1, 0xae, 0x9d, 0x2e,
	0xc9, 0x05, 0x3c, 0x78, 0xe1, 0xb1, 0x38, 0xbd, 0x19, 0xb3, 0x29, 0x5b, 0x87, 0x01, 0xa3, 0xf8,
	0x35, 0xec, 0xf0, 0xa0, 0xcc, 0xd0, 0x46, 0xad, 0xf1, 0xde, 0x99, 0x3e, 0xd9, 0xb2, 0x3e, 0x51,
	0xd3, 0xb0, 0xa5, 0x15, 0xf9, 0x09, 0x74, 0x2b, 0xb8, 0xf1, 0x24, 0xad, 0x57, 0xd4, 0x9f, 0xd3,
	0x28, 0x25, 0xf7, 0x3e, 0xec, 0x50, 0xdf, 0xf1, 0x56, 0x49, 0x9a, 0x72, 0xa1, 0xa6, 0xdf, 0xcc,
	0x11, 0x75, 0x09, 0xc6, 0x34, 0x0c, 0xde, 0x79, 0x91, 0x5f, 0x86, 0xaa, 0xe5, 0x0c, 0xa1, 0xed,
	0x86, 0x8b, 0x6d, 0x51, 0xf8, 0x37, 0xf9, 0x4f, 0x03, 0xc8, 0x20, 0xb0, 0x0f, 0xad, 0xcd, 0xd6,
	0x8f, 0x7f, 0x66, 0x17, 0x6b, 0xaa, 0x17, 0x3b, 0x86, 0xde, 0x86, 0xd1, 0x28, 0xc7, 0x30, 0xdf,
	0x28, 0xd3, 0xdf, 0xae, 0xa7, 0x7f, 0x27, 0x47, 0xff, 0x53, 0xe8, 0xb0, 0xd8, 0x89, 0x37, 0xcc,
	0xe8, 0x8c, 0xb4, 0xf1, 0xbd, 0xb3, 0x63, 0x85, 0xcc, 0xec, 0x86, 0x2f, 0x85, 0x89, 0x9d, 0x98,
	0x92, 0xe7, 0xa0, 0xf3, 0xca, 0x64, 0xe7, 0x59, 0x6d, 0x4c, 0xe8, 0xfa, 0x72, 0x2b, 0xa9, 0xce,
	0x83, 0x4a, 0x40, 0x3b, 0xb5, 0x22, 0x33, 0xd0, 0x67, 0x74, 0x45, 0xab, 0xaa, 0x53, 0xa6, 0xa5,
	0xb6, 0x32, 0x5e, 0xda, 0x3a, 0x76, 0xb8, 0xa2, 0x9f, 0x2c, 0x49, 0x8e, 0xaa, 0x66, 0x81, 0xaa,
	0x13, 0x80, 0x75, 0xe4, 0xdd, 0x78, 0x2b, 0xba, 0xa4, 0xcc, 0x68, 0x8d, 0x5a, 0xe3, 0x9e, 0xad,
	0xec, 0xf0, 0x86, 0xe2, 0x41, 0x64, 0x43, 0xa5, 0xa4, 0x6a, 0x2a, 0xa9, 0xe4, 0x39, 0xb4, 0xb9,
	0xc9, 0x6d, 0xfa, 0xf3, 0x93, 0xe1, 0x28, 0x1c, 0x5d, 0x52, 0xd1, 0x04, 0x32, 0xb5, 0x84, 0xe7,
	0xdb, 0x73, 0x83, 0x4f, 0xa0, 0xcd, 0xef, 0x25, 0x1e, 0xcc, 0xde, 0xd9, 0xa1, 0x52, 0x0f, 0x81,
	0x28, 0x0e, 0x89, 0x03, 0xc7, 0xaf, 0xd7, 0x0b, 0x27, 0x57, 0x06, 0x85, 0xca, 0x3b, 0x84, 0x53,
	0x58, 0x69, 0xe5, 0x58, 0xb9, 0x80, 0xcf, 0x5e, 0xca, 0x4c, 0xa6, 0xb2, 0xc3, 0x55, 0x99, 0xbb,
	0x43, 0xad, 0x5f, 0xc0, 0xc3, 0xe9, 0x6f, 0xd4, 0xfd, 0x9d, 0x23, 0xfd, 0xe8, 0xba, 0x94, 0xb1,
	0x14, 0x64, 0x08, 0xbb, 0x11, 0x65, 0xe1, 0x26, 0x72, 0x53, 0xbd, 0xdc, 0xae, 0xf1, 0x21, 0x74,
	0x1c, 0x97, 0x4b, 0x70, 0x8a, 0x26, 0x57, 0xe4, 0x19, 0xe8, 0x25, 0xb4, 0x84, 0xe3, 0x13, 0x00,
	0x47, 0xec, 0x78, 0xf3, 0x95, 0x04, 0xdc, 0xb5, 0x95, 0x9d, 0xd3, 0x09, 0xf4, 0x8b, 0x2d, 0x82,
	0x7b, 0xd0, 0xb5, 0xae, 0xdf, 0x58, 0xaf, 0xce, 0x67, 0xfd, 0x06, 0x1e, 0x40, 0x6f, 0xfa, 0xcb,
	0xf5, 0x85, 0x65, 0x5f, 0x9d, 0xcf, 0xfa, 0xda, 0xd9, 0x07, 0x80, 0xae, 0x70, 0x58, 0x46, 0xf8,
	0x06, 0x20, 0xd3, 0x7a, 0x7c, 0xa4, 0x14, 0xa5, 0x34, 0x02, 0x86, 0x83, 0x42, 0x0b, 0x59, 0x33,
	0xa2, 0xff, 0xfd, 0xe1, 0xff, 0x7f, 0x9a, 0x03, 0xb2, 0x2f, 0x06, 0x90, 0xe9, 0x0a, 0x9f, 0xef,
	0xb5, 0x53, 0xbc, 0x02, 0xc8, 0xda, 0x09, 0xcb, 0x9e, 0xc3, 0xa3, 0x89, 0x3a, 0x73, 0x26, 0xe7,
	0xfe, 0x3a, 0xfe, 0xab, 0x08, 0xb7, 0x10, 0x08, 0x1c, 0xee, 0x67, 0x80, 0xec, 0x59, 0xe0, 0x61,
	0x01, 0xee, 0x56, 0x60, 0x1b, 0xe1, 0xcf, 0xc1, 0xde, 0xc2, 0x41, 0x4e, 0xd0, 0xb1, 0xca, 0x7d,
	0x38, 0x52, 0x82, 0x54, 0xea, 0x3f, 0x41, 0x11, 0x60, 0x1f, 0x41, 0x06, 0x58, 0x79, 0x2c, 0xc6,
	0xf7, 0xd0, 0x2f, 0x8a, 0x3c, 0x12, 0x05, 0xa9, 0x66, 0x02, 0x54, 0x67, 0xf0, 0xb9, 0x08, 0xa0,
	0x13, 0x94, 0xe3, 0x5d, 0x38, 0x98, 0x9e, 0x40, 0xe0, 0x79, 0xf8, 0x30, 0x28, 0x8d, 0x01, 0x7c,
	0xa2, 0x96, 0xb0, 0x66, 0x48, 0x54, 0x47, 0x3b, 0x11, 0xd1, 0x0c, 0x72, 0xa4, 0x46, 0x73, 0x25,
	0x04, 0x0f, 0xf7, 0x1e, 0xfa, 0x45, 0x85, 0xcc, 0xa5, 0x56, 0x23, 0x9f, 0x77, 0x48, 0x2d, 0xab,
	0x77, 0x04, 0xf7, 0xab, 0x64, 0x00, 0xbf, 0x54, 0x67, 0x6c, 0xbd, 0x4e, 0xdc, 0x21, 0x66, 0xf6,
	0x2c, 0xe6, 0x70, 0x58, 0x98, 0x26, 0x55, 0xef, 0x96, 0x14, 0x9e, 0x45, 0xc5, 0xf0, 0x21, 0x86,
	0x08, 0x84, 0xd8, 0x57, 0x03, 0x89, 0xe7, 0xf1, 0x43, 0xda, 0x6e, 0x22, 0x9b, 0x72, 0xbb, 0xa9,
	0x39, 0x0c, 0x0a, 0x0a, 0x69, 0xcd, 0x48, 0x03, 0xbf, 0x4b, 0xfb, 0x4a, 0x00, 0x94, 0x4d, 0xaa,
	0x33, 0x6f, 0xe0, 0xb7, 0x69, 0x03, 0x09, 0xbf, 0xa2, 0xf8, 0xd6, 0x79, 0x99, 0xd0, 0xbd, 0xa4,
	0x71, 0x5d, 0xa8, 0x22, 0x0a, 0x69, 0xe0, 0x1c, 0xb0, 0xac, 0xad, 0xf8, 0x85, 0x62, 0x58, 0x2b,
	0xbd, 0xd5, 0x77, 0x18, 0x08, 0x2a, 0xf7, 0xb0, 0x27, 0x7b, 0x8c, 0xd1, 0x18, 0x9f, 0xc1, 0x41,
	0x32, 0x89, 0x92, 0x3f, 0x94, 0x95, 0xed, 0x5b, 0x21, 0x56, 0x0d, 0x7c, 0x0b, 0x87, 0x05, 0x91,
	0xc5, 0xc7, 0x6a, 0x0d, 0x2a, 0xe5, 0x3c, 0x57, 0xf2, 0x1a, 0x8d, 0x26, 0x8d, 0x79, 0x47, 0x44,
	0x7f, 0xfa, 0x31, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x2f, 0x8b, 0x09, 0x96, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeamMgrClient is the client API for TeamMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeamMgrClient interface {
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*TeamID, error)
	DeleteTeam(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateTeam(ctx context.Context, in *Team, opts ...grpc.CallOption) (*common.Empty, error)
	ListUserTeams(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListUserTeamsResponse, error)
	InviteTeamMember(ctx context.Context, in *InviteTeamMemberRequest, opts ...grpc.CallOption) (*common.Empty, error)
	ConfirmTeamMember(ctx context.Context, in *ConfirmTeamMemberRequest, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteTeamMember(ctx context.Context, in *DeleteTeamMemberRequest, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateTeamMemberRole(ctx context.Context, in *UpdateTeamMemberRoleRequest, opts ...grpc.CallOption) (*common.Empty, error)
	ListTeamMembers(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*ListTeamMembersResponse, error)
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*RoleID, error)
	DeleteRole(ctx context.Context, in *RoleID, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*common.Empty, error)
	GetRole(ctx context.Context, in *RoleID, opts ...grpc.CallOption) (*Role, error)
	SetUserCurrentTeam(ctx context.Context, in *SetUserCurrentTeamRequest, opts ...grpc.CallOption) (*common.Empty, error)
	GetUserTeamID(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*TeamID, error)
	CheckUserAccess(ctx context.Context, in *CheckUserAccessRequest, opts ...grpc.CallOption) (*CheckUserAccessResponse, error)
}

type teamMgrClient struct {
	cc *grpc.ClientConn
}

func NewTeamMgrClient(cc *grpc.ClientConn) TeamMgrClient {
	return &teamMgrClient{cc}
}

func (c *teamMgrClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*TeamID, error) {
	out := new(TeamID)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) DeleteTeam(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) UpdateTeam(ctx context.Context, in *Team, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/UpdateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) ListUserTeams(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListUserTeamsResponse, error) {
	out := new(ListUserTeamsResponse)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/ListUserTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) InviteTeamMember(ctx context.Context, in *InviteTeamMemberRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/InviteTeamMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) ConfirmTeamMember(ctx context.Context, in *ConfirmTeamMemberRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/ConfirmTeamMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) DeleteTeamMember(ctx context.Context, in *DeleteTeamMemberRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/DeleteTeamMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) UpdateTeamMemberRole(ctx context.Context, in *UpdateTeamMemberRoleRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/UpdateTeamMemberRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) ListTeamMembers(ctx context.Context, in *TeamID, opts ...grpc.CallOption) (*ListTeamMembersResponse, error) {
	out := new(ListTeamMembersResponse)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/ListTeamMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*RoleID, error) {
	out := new(RoleID)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) DeleteRole(ctx context.Context, in *RoleID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/DeleteRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) UpdateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/UpdateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) GetRole(ctx context.Context, in *RoleID, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) SetUserCurrentTeam(ctx context.Context, in *SetUserCurrentTeamRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/SetUserCurrentTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) GetUserTeamID(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*TeamID, error) {
	out := new(TeamID)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/GetUserTeamID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamMgrClient) CheckUserAccess(ctx context.Context, in *CheckUserAccessRequest, opts ...grpc.CallOption) (*CheckUserAccessResponse, error) {
	out := new(CheckUserAccessResponse)
	err := c.cc.Invoke(ctx, "/gwteammgr.TeamMgr/CheckUserAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamMgrServer is the server API for TeamMgr service.
type TeamMgrServer interface {
	CreateTeam(context.Context, *CreateTeamRequest) (*TeamID, error)
	DeleteTeam(context.Context, *TeamID) (*common.Empty, error)
	UpdateTeam(context.Context, *Team) (*common.Empty, error)
	ListUserTeams(context.Context, *common.Empty) (*ListUserTeamsResponse, error)
	InviteTeamMember(context.Context, *InviteTeamMemberRequest) (*common.Empty, error)
	ConfirmTeamMember(context.Context, *ConfirmTeamMemberRequest) (*common.Empty, error)
	DeleteTeamMember(context.Context, *DeleteTeamMemberRequest) (*common.Empty, error)
	UpdateTeamMemberRole(context.Context, *UpdateTeamMemberRoleRequest) (*common.Empty, error)
	ListTeamMembers(context.Context, *TeamID) (*ListTeamMembersResponse, error)
	CreateRole(context.Context, *CreateRoleRequest) (*RoleID, error)
	DeleteRole(context.Context, *RoleID) (*common.Empty, error)
	UpdateRole(context.Context, *Role) (*common.Empty, error)
	GetRole(context.Context, *RoleID) (*Role, error)
	SetUserCurrentTeam(context.Context, *SetUserCurrentTeamRequest) (*common.Empty, error)
	GetUserTeamID(context.Context, *common.Empty) (*TeamID, error)
	CheckUserAccess(context.Context, *CheckUserAccessRequest) (*CheckUserAccessResponse, error)
}

// UnimplementedTeamMgrServer can be embedded to have forward compatible implementations.
type UnimplementedTeamMgrServer struct {
}

func (*UnimplementedTeamMgrServer) CreateTeam(ctx context.Context, req *CreateTeamRequest) (*TeamID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (*UnimplementedTeamMgrServer) DeleteTeam(ctx context.Context, req *TeamID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (*UnimplementedTeamMgrServer) UpdateTeam(ctx context.Context, req *Team) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (*UnimplementedTeamMgrServer) ListUserTeams(ctx context.Context, req *common.Empty) (*ListUserTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserTeams not implemented")
}
func (*UnimplementedTeamMgrServer) InviteTeamMember(ctx context.Context, req *InviteTeamMemberRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteTeamMember not implemented")
}
func (*UnimplementedTeamMgrServer) ConfirmTeamMember(ctx context.Context, req *ConfirmTeamMemberRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTeamMember not implemented")
}
func (*UnimplementedTeamMgrServer) DeleteTeamMember(ctx context.Context, req *DeleteTeamMemberRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeamMember not implemented")
}
func (*UnimplementedTeamMgrServer) UpdateTeamMemberRole(ctx context.Context, req *UpdateTeamMemberRoleRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeamMemberRole not implemented")
}
func (*UnimplementedTeamMgrServer) ListTeamMembers(ctx context.Context, req *TeamID) (*ListTeamMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeamMembers not implemented")
}
func (*UnimplementedTeamMgrServer) CreateRole(ctx context.Context, req *CreateRoleRequest) (*RoleID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (*UnimplementedTeamMgrServer) DeleteRole(ctx context.Context, req *RoleID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (*UnimplementedTeamMgrServer) UpdateRole(ctx context.Context, req *Role) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (*UnimplementedTeamMgrServer) GetRole(ctx context.Context, req *RoleID) (*Role, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (*UnimplementedTeamMgrServer) SetUserCurrentTeam(ctx context.Context, req *SetUserCurrentTeamRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserCurrentTeam not implemented")
}
func (*UnimplementedTeamMgrServer) GetUserTeamID(ctx context.Context, req *common.Empty) (*TeamID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTeamID not implemented")
}
func (*UnimplementedTeamMgrServer) CheckUserAccess(ctx context.Context, req *CheckUserAccessRequest) (*CheckUserAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserAccess not implemented")
}

func RegisterTeamMgrServer(s *grpc.Server, srv TeamMgrServer) {
	s.RegisterService(&_TeamMgr_serviceDesc, srv)
}

func _TeamMgr_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).DeleteTeam(ctx, req.(*TeamID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Team)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/UpdateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).UpdateTeam(ctx, req.(*Team))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_ListUserTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).ListUserTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/ListUserTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).ListUserTeams(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_InviteTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).InviteTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/InviteTeamMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).InviteTeamMember(ctx, req.(*InviteTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_ConfirmTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).ConfirmTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/ConfirmTeamMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).ConfirmTeamMember(ctx, req.(*ConfirmTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_DeleteTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).DeleteTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/DeleteTeamMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).DeleteTeamMember(ctx, req.(*DeleteTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_UpdateTeamMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).UpdateTeamMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/UpdateTeamMemberRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).UpdateTeamMemberRole(ctx, req.(*UpdateTeamMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_ListTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).ListTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/ListTeamMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).ListTeamMembers(ctx, req.(*TeamID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/DeleteRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).DeleteRole(ctx, req.(*RoleID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).UpdateRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).GetRole(ctx, req.(*RoleID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_SetUserCurrentTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserCurrentTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).SetUserCurrentTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/SetUserCurrentTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).SetUserCurrentTeam(ctx, req.(*SetUserCurrentTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_GetUserTeamID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).GetUserTeamID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/GetUserTeamID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).GetUserTeamID(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamMgr_CheckUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamMgrServer).CheckUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwteammgr.TeamMgr/CheckUserAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamMgrServer).CheckUserAccess(ctx, req.(*CheckUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeamMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gwteammgr.TeamMgr",
	HandlerType: (*TeamMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTeam",
			Handler:    _TeamMgr_CreateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _TeamMgr_DeleteTeam_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _TeamMgr_UpdateTeam_Handler,
		},
		{
			MethodName: "ListUserTeams",
			Handler:    _TeamMgr_ListUserTeams_Handler,
		},
		{
			MethodName: "InviteTeamMember",
			Handler:    _TeamMgr_InviteTeamMember_Handler,
		},
		{
			MethodName: "ConfirmTeamMember",
			Handler:    _TeamMgr_ConfirmTeamMember_Handler,
		},
		{
			MethodName: "DeleteTeamMember",
			Handler:    _TeamMgr_DeleteTeamMember_Handler,
		},
		{
			MethodName: "UpdateTeamMemberRole",
			Handler:    _TeamMgr_UpdateTeamMemberRole_Handler,
		},
		{
			MethodName: "ListTeamMembers",
			Handler:    _TeamMgr_ListTeamMembers_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _TeamMgr_CreateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _TeamMgr_DeleteRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _TeamMgr_UpdateRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _TeamMgr_GetRole_Handler,
		},
		{
			MethodName: "SetUserCurrentTeam",
			Handler:    _TeamMgr_SetUserCurrentTeam_Handler,
		},
		{
			MethodName: "GetUserTeamID",
			Handler:    _TeamMgr_GetUserTeamID_Handler,
		},
		{
			MethodName: "CheckUserAccess",
			Handler:    _TeamMgr_CheckUserAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teammgr/v1/teammgr.proto",
}
