// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcmgr/v1/micro/dcmgr.proto

package dcmgr

import (
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetClusterCertificateRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterCertificateRequest) Reset()         { *m = GetClusterCertificateRequest{} }
func (m *GetClusterCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterCertificateRequest) ProtoMessage()    {}
func (*GetClusterCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{0}
}

func (m *GetClusterCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterCertificateRequest.Unmarshal(m, b)
}
func (m *GetClusterCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterCertificateRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterCertificateRequest.Merge(m, src)
}
func (m *GetClusterCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterCertificateRequest.Size(m)
}
func (m *GetClusterCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterCertificateRequest proto.InternalMessageInfo

func (m *GetClusterCertificateRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type GetClusterCertificateResponse struct {
	ClientCsrCert        string   `protobuf:"bytes,1,opt,name=client_csr_cert,json=clientCsrCert,proto3" json:"client_csr_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterCertificateResponse) Reset()         { *m = GetClusterCertificateResponse{} }
func (m *GetClusterCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterCertificateResponse) ProtoMessage()    {}
func (*GetClusterCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{1}
}

func (m *GetClusterCertificateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterCertificateResponse.Unmarshal(m, b)
}
func (m *GetClusterCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterCertificateResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterCertificateResponse.Merge(m, src)
}
func (m *GetClusterCertificateResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterCertificateResponse.Size(m)
}
func (m *GetClusterCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterCertificateResponse proto.InternalMessageInfo

func (m *GetClusterCertificateResponse) GetClientCsrCert() string {
	if m != nil {
		return m.ClientCsrCert
	}
	return ""
}

type MyDataCenterRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyDataCenterRequest) Reset()         { *m = MyDataCenterRequest{} }
func (m *MyDataCenterRequest) String() string { return proto.CompactTextString(m) }
func (*MyDataCenterRequest) ProtoMessage()    {}
func (*MyDataCenterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{2}
}

func (m *MyDataCenterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyDataCenterRequest.Unmarshal(m, b)
}
func (m *MyDataCenterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyDataCenterRequest.Marshal(b, m, deterministic)
}
func (m *MyDataCenterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyDataCenterRequest.Merge(m, src)
}
func (m *MyDataCenterRequest) XXX_Size() int {
	return xxx_messageInfo_MyDataCenterRequest.Size(m)
}
func (m *MyDataCenterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MyDataCenterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MyDataCenterRequest proto.InternalMessageInfo

func (m *MyDataCenterRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RegisterDataCenterRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDataCenterRequest) Reset()         { *m = RegisterDataCenterRequest{} }
func (m *RegisterDataCenterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterDataCenterRequest) ProtoMessage()    {}
func (*RegisterDataCenterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{3}
}

func (m *RegisterDataCenterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDataCenterRequest.Unmarshal(m, b)
}
func (m *RegisterDataCenterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDataCenterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterDataCenterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDataCenterRequest.Merge(m, src)
}
func (m *RegisterDataCenterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterDataCenterRequest.Size(m)
}
func (m *RegisterDataCenterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDataCenterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDataCenterRequest proto.InternalMessageInfo

func (m *RegisterDataCenterRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RegisterDataCenterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type DataCenterListWithFilterRequest struct {
	DclistFilter         *common.DataCenterListFilter `protobuf:"bytes,1,opt,name=dclist_filter,json=dclistFilter,proto3" json:"dclist_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DataCenterListWithFilterRequest) Reset()         { *m = DataCenterListWithFilterRequest{} }
func (m *DataCenterListWithFilterRequest) String() string { return proto.CompactTextString(m) }
func (*DataCenterListWithFilterRequest) ProtoMessage()    {}
func (*DataCenterListWithFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{4}
}

func (m *DataCenterListWithFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListWithFilterRequest.Unmarshal(m, b)
}
func (m *DataCenterListWithFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListWithFilterRequest.Marshal(b, m, deterministic)
}
func (m *DataCenterListWithFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListWithFilterRequest.Merge(m, src)
}
func (m *DataCenterListWithFilterRequest) XXX_Size() int {
	return xxx_messageInfo_DataCenterListWithFilterRequest.Size(m)
}
func (m *DataCenterListWithFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListWithFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListWithFilterRequest proto.InternalMessageInfo

func (m *DataCenterListWithFilterRequest) GetDclistFilter() *common.DataCenterListFilter {
	if m != nil {
		return m.DclistFilter
	}
	return nil
}

type RegisterDataCenterResponse struct {
	ClientKey            string   `protobuf:"bytes,1,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	ClientCsrCert        string   `protobuf:"bytes,2,opt,name=client_csr_cert,json=clientCsrCert,proto3" json:"client_csr_cert,omitempty"`
	CaCert               string   `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	ClusterId            string   `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClusterName          string   `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Configmap            string   `protobuf:"bytes,6,opt,name=configmap,proto3" json:"configmap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDataCenterResponse) Reset()         { *m = RegisterDataCenterResponse{} }
func (m *RegisterDataCenterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterDataCenterResponse) ProtoMessage()    {}
func (*RegisterDataCenterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{5}
}

func (m *RegisterDataCenterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDataCenterResponse.Unmarshal(m, b)
}
func (m *RegisterDataCenterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDataCenterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterDataCenterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDataCenterResponse.Merge(m, src)
}
func (m *RegisterDataCenterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterDataCenterResponse.Size(m)
}
func (m *RegisterDataCenterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDataCenterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDataCenterResponse proto.InternalMessageInfo

func (m *RegisterDataCenterResponse) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetClientCsrCert() string {
	if m != nil {
		return m.ClientCsrCert
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetConfigmap() string {
	if m != nil {
		return m.Configmap
	}
	return ""
}

type ClusterRecord struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	ClientCsrCert        string   `protobuf:"bytes,4,opt,name=client_csr_cert,json=clientCsrCert,proto3" json:"client_csr_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterRecord) Reset()         { *m = ClusterRecord{} }
func (m *ClusterRecord) String() string { return proto.CompactTextString(m) }
func (*ClusterRecord) ProtoMessage()    {}
func (*ClusterRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{6}
}

func (m *ClusterRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRecord.Unmarshal(m, b)
}
func (m *ClusterRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRecord.Marshal(b, m, deterministic)
}
func (m *ClusterRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRecord.Merge(m, src)
}
func (m *ClusterRecord) XXX_Size() int {
	return xxx_messageInfo_ClusterRecord.Size(m)
}
func (m *ClusterRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRecord proto.InternalMessageInfo

func (m *ClusterRecord) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ClusterRecord) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterRecord) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ClusterRecord) GetClientCsrCert() string {
	if m != nil {
		return m.ClientCsrCert
	}
	return ""
}

type DataCenterListResponse struct {
	DcList               []*common.DataCenterStatus `protobuf:"bytes,1,rep,name=dcList,proto3" json:"dcList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DataCenterListResponse) Reset()         { *m = DataCenterListResponse{} }
func (m *DataCenterListResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListResponse) ProtoMessage()    {}
func (*DataCenterListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{7}
}

func (m *DataCenterListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListResponse.Unmarshal(m, b)
}
func (m *DataCenterListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListResponse.Merge(m, src)
}
func (m *DataCenterListResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListResponse.Size(m)
}
func (m *DataCenterListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListResponse proto.InternalMessageInfo

func (m *DataCenterListResponse) GetDcList() []*common.DataCenterStatus {
	if m != nil {
		return m.DcList
	}
	return nil
}

type DataCenterListWithCertificationResponse struct {
	Certification        string           `protobuf:"bytes,1,opt,name=certification,proto3" json:"certification,omitempty"`
	Host                 string           `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	List                 []*ClusterRecord `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DataCenterListWithCertificationResponse) Reset() {
	*m = DataCenterListWithCertificationResponse{}
}
func (m *DataCenterListWithCertificationResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListWithCertificationResponse) ProtoMessage()    {}
func (*DataCenterListWithCertificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{8}
}

func (m *DataCenterListWithCertificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListWithCertificationResponse.Unmarshal(m, b)
}
func (m *DataCenterListWithCertificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListWithCertificationResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterListWithCertificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListWithCertificationResponse.Merge(m, src)
}
func (m *DataCenterListWithCertificationResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListWithCertificationResponse.Size(m)
}
func (m *DataCenterListWithCertificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListWithCertificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListWithCertificationResponse proto.InternalMessageInfo

func (m *DataCenterListWithCertificationResponse) GetCertification() string {
	if m != nil {
		return m.Certification
	}
	return ""
}

func (m *DataCenterListWithCertificationResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DataCenterListWithCertificationResponse) GetList() []*ClusterRecord {
	if m != nil {
		return m.List
	}
	return nil
}

type NetworkInfoResponse struct {
	UserCount            int32    `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	HostCount            int32    `protobuf:"varint,2,opt,name=host_count,json=hostCount,proto3" json:"host_count,omitempty"`
	NsCount              int32    `protobuf:"varint,3,opt,name=ns_count,json=nsCount,proto3" json:"ns_count,omitempty"`
	ContainerCount       int32    `protobuf:"varint,4,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	Traffic              int32    `protobuf:"varint,5,opt,name=traffic,proto3" json:"traffic,omitempty"`
	CpuTotal             string   `protobuf:"bytes,6,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUsed              string   `protobuf:"bytes,7,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used,omitempty"`
	MemoryTotal          string   `protobuf:"bytes,8,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed           string   `protobuf:"bytes,9,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	StorageTotal         string   `protobuf:"bytes,10,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	StorageUsed          string   `protobuf:"bytes,11,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	NetworkCount         int32    `protobuf:"varint,12,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	NodeportCount        uint32   `protobuf:"varint,13,opt,name=nodeport_count,json=nodeportCount,proto3" json:"nodeport_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInfoResponse) Reset()         { *m = NetworkInfoResponse{} }
func (m *NetworkInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkInfoResponse) ProtoMessage()    {}
func (*NetworkInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{9}
}

func (m *NetworkInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfoResponse.Unmarshal(m, b)
}
func (m *NetworkInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfoResponse.Marshal(b, m, deterministic)
}
func (m *NetworkInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfoResponse.Merge(m, src)
}
func (m *NetworkInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkInfoResponse.Size(m)
}
func (m *NetworkInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfoResponse proto.InternalMessageInfo

func (m *NetworkInfoResponse) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetHostCount() int32 {
	if m != nil {
		return m.HostCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetNsCount() int32 {
	if m != nil {
		return m.NsCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetContainerCount() int32 {
	if m != nil {
		return m.ContainerCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetTraffic() int32 {
	if m != nil {
		return m.Traffic
	}
	return 0
}

func (m *NetworkInfoResponse) GetCpuTotal() string {
	if m != nil {
		return m.CpuTotal
	}
	return ""
}

func (m *NetworkInfoResponse) GetCpuUsed() string {
	if m != nil {
		return m.CpuUsed
	}
	return ""
}

func (m *NetworkInfoResponse) GetMemoryTotal() string {
	if m != nil {
		return m.MemoryTotal
	}
	return ""
}

func (m *NetworkInfoResponse) GetMemoryUsed() string {
	if m != nil {
		return m.MemoryUsed
	}
	return ""
}

func (m *NetworkInfoResponse) GetStorageTotal() string {
	if m != nil {
		return m.StorageTotal
	}
	return ""
}

func (m *NetworkInfoResponse) GetStorageUsed() string {
	if m != nil {
		return m.StorageUsed
	}
	return ""
}

func (m *NetworkInfoResponse) GetNetworkCount() int32 {
	if m != nil {
		return m.NetworkCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetNodeportCount() uint32 {
	if m != nil {
		return m.NodeportCount
	}
	return 0
}

type DCOverviewRequest struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCOverviewRequest) Reset()         { *m = DCOverviewRequest{} }
func (m *DCOverviewRequest) String() string { return proto.CompactTextString(m) }
func (*DCOverviewRequest) ProtoMessage()    {}
func (*DCOverviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{10}
}

func (m *DCOverviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCOverviewRequest.Unmarshal(m, b)
}
func (m *DCOverviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCOverviewRequest.Marshal(b, m, deterministic)
}
func (m *DCOverviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCOverviewRequest.Merge(m, src)
}
func (m *DCOverviewRequest) XXX_Size() int {
	return xxx_messageInfo_DCOverviewRequest.Size(m)
}
func (m *DCOverviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCOverviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCOverviewRequest proto.InternalMessageInfo

func (m *DCOverviewRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type DCOverviewResponse struct {
	ClusterId            string                   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Status               *common.DataCenterStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            string                   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RSignature           string                   `protobuf:"bytes,4,opt,name=r_signature,json=rSignature,proto3" json:"r_signature,omitempty"`
	SSignature           string                   `protobuf:"bytes,5,opt,name=s_signature,json=sSignature,proto3" json:"s_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DCOverviewResponse) Reset()         { *m = DCOverviewResponse{} }
func (m *DCOverviewResponse) String() string { return proto.CompactTextString(m) }
func (*DCOverviewResponse) ProtoMessage()    {}
func (*DCOverviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{11}
}

func (m *DCOverviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCOverviewResponse.Unmarshal(m, b)
}
func (m *DCOverviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCOverviewResponse.Marshal(b, m, deterministic)
}
func (m *DCOverviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCOverviewResponse.Merge(m, src)
}
func (m *DCOverviewResponse) XXX_Size() int {
	return xxx_messageInfo_DCOverviewResponse.Size(m)
}
func (m *DCOverviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DCOverviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DCOverviewResponse proto.InternalMessageInfo

func (m *DCOverviewResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *DCOverviewResponse) GetStatus() *common.DataCenterStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DCOverviewResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DCOverviewResponse) GetRSignature() string {
	if m != nil {
		return m.RSignature
	}
	return ""
}

func (m *DCOverviewResponse) GetSSignature() string {
	if m != nil {
		return m.SSignature
	}
	return ""
}

type DashBoardRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashBoardRequest) Reset()         { *m = DashBoardRequest{} }
func (m *DashBoardRequest) String() string { return proto.CompactTextString(m) }
func (*DashBoardRequest) ProtoMessage()    {}
func (*DashBoardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{12}
}

func (m *DashBoardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashBoardRequest.Unmarshal(m, b)
}
func (m *DashBoardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashBoardRequest.Marshal(b, m, deterministic)
}
func (m *DashBoardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashBoardRequest.Merge(m, src)
}
func (m *DashBoardRequest) XXX_Size() int {
	return xxx_messageInfo_DashBoardRequest.Size(m)
}
func (m *DashBoardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DashBoardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DashBoardRequest proto.InternalMessageInfo

type DashBoardResponse struct {
	TotalIncome          int32     `protobuf:"varint,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	CurrentUsage         *Usage    `protobuf:"bytes,2,opt,name=current_usage,json=currentUsage,proto3" json:"current_usage,omitempty"`
	Week                 []*Income `protobuf:"bytes,3,rep,name=week,proto3" json:"week,omitempty"`
	Month                []*Income `protobuf:"bytes,4,rep,name=month,proto3" json:"month,omitempty"`
	Year                 []*Income `protobuf:"bytes,5,rep,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DashBoardResponse) Reset()         { *m = DashBoardResponse{} }
func (m *DashBoardResponse) String() string { return proto.CompactTextString(m) }
func (*DashBoardResponse) ProtoMessage()    {}
func (*DashBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{13}
}

func (m *DashBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashBoardResponse.Unmarshal(m, b)
}
func (m *DashBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashBoardResponse.Marshal(b, m, deterministic)
}
func (m *DashBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashBoardResponse.Merge(m, src)
}
func (m *DashBoardResponse) XXX_Size() int {
	return xxx_messageInfo_DashBoardResponse.Size(m)
}
func (m *DashBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DashBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DashBoardResponse proto.InternalMessageInfo

func (m *DashBoardResponse) GetTotalIncome() int32 {
	if m != nil {
		return m.TotalIncome
	}
	return 0
}

func (m *DashBoardResponse) GetCurrentUsage() *Usage {
	if m != nil {
		return m.CurrentUsage
	}
	return nil
}

func (m *DashBoardResponse) GetWeek() []*Income {
	if m != nil {
		return m.Week
	}
	return nil
}

func (m *DashBoardResponse) GetMonth() []*Income {
	if m != nil {
		return m.Month
	}
	return nil
}

func (m *DashBoardResponse) GetYear() []*Income {
	if m != nil {
		return m.Year
	}
	return nil
}

type Income struct {
	Income               int32                `protobuf:"varint,1,opt,name=income,proto3" json:"income,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Usage                *Usage               `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Income) Reset()         { *m = Income{} }
func (m *Income) String() string { return proto.CompactTextString(m) }
func (*Income) ProtoMessage()    {}
func (*Income) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{14}
}

func (m *Income) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Income.Unmarshal(m, b)
}
func (m *Income) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Income.Marshal(b, m, deterministic)
}
func (m *Income) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Income.Merge(m, src)
}
func (m *Income) XXX_Size() int {
	return xxx_messageInfo_Income.Size(m)
}
func (m *Income) XXX_DiscardUnknown() {
	xxx_messageInfo_Income.DiscardUnknown(m)
}

var xxx_messageInfo_Income proto.InternalMessageInfo

func (m *Income) GetIncome() int32 {
	if m != nil {
		return m.Income
	}
	return 0
}

func (m *Income) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Income) GetUsage() *Usage {
	if m != nil {
		return m.Usage
	}
	return nil
}

type Usage struct {
	CpuTotal             int32    `protobuf:"varint,1,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUsed              int32    `protobuf:"varint,2,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used,omitempty"`
	MemoryTotal          int32    `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed           int32    `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	StorageTotal         int32    `protobuf:"varint,5,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	StorageUsed          int32    `protobuf:"varint,6,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Usage) Reset()         { *m = Usage{} }
func (m *Usage) String() string { return proto.CompactTextString(m) }
func (*Usage) ProtoMessage()    {}
func (*Usage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{15}
}

func (m *Usage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Usage.Unmarshal(m, b)
}
func (m *Usage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Usage.Marshal(b, m, deterministic)
}
func (m *Usage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Usage.Merge(m, src)
}
func (m *Usage) XXX_Size() int {
	return xxx_messageInfo_Usage.Size(m)
}
func (m *Usage) XXX_DiscardUnknown() {
	xxx_messageInfo_Usage.DiscardUnknown(m)
}

var xxx_messageInfo_Usage proto.InternalMessageInfo

func (m *Usage) GetCpuTotal() int32 {
	if m != nil {
		return m.CpuTotal
	}
	return 0
}

func (m *Usage) GetCpuUsed() int32 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *Usage) GetMemoryTotal() int32 {
	if m != nil {
		return m.MemoryTotal
	}
	return 0
}

func (m *Usage) GetMemoryUsed() int32 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *Usage) GetStorageTotal() int32 {
	if m != nil {
		return m.StorageTotal
	}
	return 0
}

func (m *Usage) GetStorageUsed() int32 {
	if m != nil {
		return m.StorageUsed
	}
	return 0
}

type InvoiceDetailRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InvoiceId            string   `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceDetailRequest) Reset()         { *m = InvoiceDetailRequest{} }
func (m *InvoiceDetailRequest) String() string { return proto.CompactTextString(m) }
func (*InvoiceDetailRequest) ProtoMessage()    {}
func (*InvoiceDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{16}
}

func (m *InvoiceDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceDetailRequest.Unmarshal(m, b)
}
func (m *InvoiceDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceDetailRequest.Marshal(b, m, deterministic)
}
func (m *InvoiceDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceDetailRequest.Merge(m, src)
}
func (m *InvoiceDetailRequest) XXX_Size() int {
	return xxx_messageInfo_InvoiceDetailRequest.Size(m)
}
func (m *InvoiceDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceDetailRequest proto.InternalMessageInfo

func (m *InvoiceDetailRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *InvoiceDetailRequest) GetInvoiceId() string {
	if m != nil {
		return m.InvoiceId
	}
	return ""
}

type HistoryFeesRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryFeesRequest) Reset()         { *m = HistoryFeesRequest{} }
func (m *HistoryFeesRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryFeesRequest) ProtoMessage()    {}
func (*HistoryFeesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{17}
}

func (m *HistoryFeesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryFeesRequest.Unmarshal(m, b)
}
func (m *HistoryFeesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryFeesRequest.Marshal(b, m, deterministic)
}
func (m *HistoryFeesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryFeesRequest.Merge(m, src)
}
func (m *HistoryFeesRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryFeesRequest.Size(m)
}
func (m *HistoryFeesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryFeesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryFeesRequest proto.InternalMessageInfo

func (m *HistoryFeesRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *HistoryFeesRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *HistoryFeesRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type MonthRecord struct {
	PaymentDate          string   `protobuf:"bytes,1,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	PaymentStatus        string   `protobuf:"bytes,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Invoice              string   `protobuf:"bytes,5,opt,name=invoice,proto3" json:"invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonthRecord) Reset()         { *m = MonthRecord{} }
func (m *MonthRecord) String() string { return proto.CompactTextString(m) }
func (*MonthRecord) ProtoMessage()    {}
func (*MonthRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{18}
}

func (m *MonthRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonthRecord.Unmarshal(m, b)
}
func (m *MonthRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonthRecord.Marshal(b, m, deterministic)
}
func (m *MonthRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonthRecord.Merge(m, src)
}
func (m *MonthRecord) XXX_Size() int {
	return xxx_messageInfo_MonthRecord.Size(m)
}
func (m *MonthRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MonthRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MonthRecord proto.InternalMessageInfo

func (m *MonthRecord) GetPaymentDate() string {
	if m != nil {
		return m.PaymentDate
	}
	return ""
}

func (m *MonthRecord) GetPaymentStatus() string {
	if m != nil {
		return m.PaymentStatus
	}
	return ""
}

func (m *MonthRecord) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *MonthRecord) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MonthRecord) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

type HistoryFeesResponse struct {
	Records              []*MonthRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HistoryFeesResponse) Reset()         { *m = HistoryFeesResponse{} }
func (m *HistoryFeesResponse) String() string { return proto.CompactTextString(m) }
func (*HistoryFeesResponse) ProtoMessage()    {}
func (*HistoryFeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{19}
}

func (m *HistoryFeesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryFeesResponse.Unmarshal(m, b)
}
func (m *HistoryFeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryFeesResponse.Marshal(b, m, deterministic)
}
func (m *HistoryFeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryFeesResponse.Merge(m, src)
}
func (m *HistoryFeesResponse) XXX_Size() int {
	return xxx_messageInfo_HistoryFeesResponse.Size(m)
}
func (m *HistoryFeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryFeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryFeesResponse proto.InternalMessageInfo

func (m *HistoryFeesResponse) GetRecords() []*MonthRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type FeesDetailRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Month                string   `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeesDetailRequest) Reset()         { *m = FeesDetailRequest{} }
func (m *FeesDetailRequest) String() string { return proto.CompactTextString(m) }
func (*FeesDetailRequest) ProtoMessage()    {}
func (*FeesDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{20}
}

func (m *FeesDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeesDetailRequest.Unmarshal(m, b)
}
func (m *FeesDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeesDetailRequest.Marshal(b, m, deterministic)
}
func (m *FeesDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeesDetailRequest.Merge(m, src)
}
func (m *FeesDetailRequest) XXX_Size() int {
	return xxx_messageInfo_FeesDetailRequest.Size(m)
}
func (m *FeesDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeesDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeesDetailRequest proto.InternalMessageInfo

func (m *FeesDetailRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *FeesDetailRequest) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

type NamespaceFees struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Charge               int32    `protobuf:"varint,2,opt,name=charge,proto3" json:"charge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamespaceFees) Reset()         { *m = NamespaceFees{} }
func (m *NamespaceFees) String() string { return proto.CompactTextString(m) }
func (*NamespaceFees) ProtoMessage()    {}
func (*NamespaceFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{21}
}

func (m *NamespaceFees) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceFees.Unmarshal(m, b)
}
func (m *NamespaceFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceFees.Marshal(b, m, deterministic)
}
func (m *NamespaceFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceFees.Merge(m, src)
}
func (m *NamespaceFees) XXX_Size() int {
	return xxx_messageInfo_NamespaceFees.Size(m)
}
func (m *NamespaceFees) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceFees.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceFees proto.InternalMessageInfo

func (m *NamespaceFees) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamespaceFees) GetCharge() int32 {
	if m != nil {
		return m.Charge
	}
	return 0
}

type FeesDetailResponse struct {
	Account              string           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Attn                 string           `protobuf:"bytes,2,opt,name=attn,proto3" json:"attn,omitempty"`
	InvoiceNumber        string           `protobuf:"bytes,3,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Total                int32            `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	IssueDate            string           `protobuf:"bytes,5,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	Start                string           `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	End                  string           `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	Charges              int32            `protobuf:"varint,8,opt,name=charges,proto3" json:"charges,omitempty"`
	Credits              int32            `protobuf:"varint,9,opt,name=credits,proto3" json:"credits,omitempty"`
	Tax                  int32            `protobuf:"varint,10,opt,name=tax,proto3" json:"tax,omitempty"`
	NsFees               []*NamespaceFees `protobuf:"bytes,11,rep,name=ns_fees,json=nsFees,proto3" json:"ns_fees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FeesDetailResponse) Reset()         { *m = FeesDetailResponse{} }
func (m *FeesDetailResponse) String() string { return proto.CompactTextString(m) }
func (*FeesDetailResponse) ProtoMessage()    {}
func (*FeesDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{22}
}

func (m *FeesDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeesDetailResponse.Unmarshal(m, b)
}
func (m *FeesDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeesDetailResponse.Marshal(b, m, deterministic)
}
func (m *FeesDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeesDetailResponse.Merge(m, src)
}
func (m *FeesDetailResponse) XXX_Size() int {
	return xxx_messageInfo_FeesDetailResponse.Size(m)
}
func (m *FeesDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeesDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeesDetailResponse proto.InternalMessageInfo

func (m *FeesDetailResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *FeesDetailResponse) GetAttn() string {
	if m != nil {
		return m.Attn
	}
	return ""
}

func (m *FeesDetailResponse) GetInvoiceNumber() string {
	if m != nil {
		return m.InvoiceNumber
	}
	return ""
}

func (m *FeesDetailResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *FeesDetailResponse) GetIssueDate() string {
	if m != nil {
		return m.IssueDate
	}
	return ""
}

func (m *FeesDetailResponse) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *FeesDetailResponse) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *FeesDetailResponse) GetCharges() int32 {
	if m != nil {
		return m.Charges
	}
	return 0
}

func (m *FeesDetailResponse) GetCredits() int32 {
	if m != nil {
		return m.Credits
	}
	return 0
}

func (m *FeesDetailResponse) GetTax() int32 {
	if m != nil {
		return m.Tax
	}
	return 0
}

func (m *FeesDetailResponse) GetNsFees() []*NamespaceFees {
	if m != nil {
		return m.NsFees
	}
	return nil
}

func init() {
	proto.RegisterType((*GetClusterCertificateRequest)(nil), "dcmgr.GetClusterCertificateRequest")
	proto.RegisterType((*GetClusterCertificateResponse)(nil), "dcmgr.GetClusterCertificateResponse")
	proto.RegisterType((*MyDataCenterRequest)(nil), "dcmgr.MyDataCenterRequest")
	proto.RegisterType((*RegisterDataCenterRequest)(nil), "dcmgr.RegisterDataCenterRequest")
	proto.RegisterType((*DataCenterListWithFilterRequest)(nil), "dcmgr.DataCenterListWithFilterRequest")
	proto.RegisterType((*RegisterDataCenterResponse)(nil), "dcmgr.RegisterDataCenterResponse")
	proto.RegisterType((*ClusterRecord)(nil), "dcmgr.ClusterRecord")
	proto.RegisterType((*DataCenterListResponse)(nil), "dcmgr.DataCenterListResponse")
	proto.RegisterType((*DataCenterListWithCertificationResponse)(nil), "dcmgr.DataCenterListWithCertificationResponse")
	proto.RegisterType((*NetworkInfoResponse)(nil), "dcmgr.NetworkInfoResponse")
	proto.RegisterType((*DCOverviewRequest)(nil), "dcmgr.DCOverviewRequest")
	proto.RegisterType((*DCOverviewResponse)(nil), "dcmgr.DCOverviewResponse")
	proto.RegisterType((*DashBoardRequest)(nil), "dcmgr.DashBoardRequest")
	proto.RegisterType((*DashBoardResponse)(nil), "dcmgr.DashBoardResponse")
	proto.RegisterType((*Income)(nil), "dcmgr.Income")
	proto.RegisterType((*Usage)(nil), "dcmgr.Usage")
	proto.RegisterType((*InvoiceDetailRequest)(nil), "dcmgr.InvoiceDetailRequest")
	proto.RegisterType((*HistoryFeesRequest)(nil), "dcmgr.HistoryFeesRequest")
	proto.RegisterType((*MonthRecord)(nil), "dcmgr.MonthRecord")
	proto.RegisterType((*HistoryFeesResponse)(nil), "dcmgr.HistoryFeesResponse")
	proto.RegisterType((*FeesDetailRequest)(nil), "dcmgr.FeesDetailRequest")
	proto.RegisterType((*NamespaceFees)(nil), "dcmgr.NamespaceFees")
	proto.RegisterType((*FeesDetailResponse)(nil), "dcmgr.FeesDetailResponse")
}

func init() { proto.RegisterFile("dcmgr/v1/micro/dcmgr.proto", fileDescriptor_1750e4d9ba65142d) }

var fileDescriptor_1750e4d9ba65142d = []byte{
	// 1599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcb, 0x6e, 0x1b, 0x37,
	0x17, 0x96, 0xac, 0x9b, 0x75, 0x24, 0xd9, 0x09, 0xed, 0x3f, 0x96, 0x95, 0xe4, 0x8f, 0xcd, 0xdc,
	0xbc, 0xf8, 0x7f, 0x19, 0x71, 0x81, 0x6c, 0x82, 0x02, 0x75, 0xa4, 0xc4, 0x11, 0xda, 0xb8, 0xc1,
	0x24, 0x46, 0x0b, 0x74, 0x21, 0x30, 0x14, 0x25, 0x4f, 0xa3, 0xb9, 0x74, 0xc8, 0x71, 0xaa, 0x67,
	0x28, 0xfa, 0x10, 0x7d, 0x87, 0xee, 0xb2, 0xea, 0xba, 0xe8, 0xae, 0xcb, 0x3e, 0x4c, 0xc1, 0xdb,
	0x78, 0x26, 0x33, 0x96, 0x0d, 0x24, 0x2b, 0xeb, 0x5c, 0xf8, 0x91, 0xe7, 0xf0, 0x3b, 0x3c, 0x67,
	0x0c, 0xbd, 0x09, 0xf5, 0x66, 0xd1, 0xfe, 0xd9, 0xa3, 0x7d, 0xcf, 0xa5, 0x51, 0xb0, 0xaf, 0xc4,
	0x7e, 0x18, 0x05, 0x22, 0x40, 0x35, 0x25, 0xf4, 0x36, 0x68, 0xe0, 0x79, 0x81, 0xbf, 0xaf, 0xff,
	0x68, 0x5b, 0xef, 0xce, 0x2c, 0x08, 0x66, 0x73, 0xb6, 0xaf, 0xa4, 0xb7, 0xf1, 0x74, 0x5f, 0xb8,
	0x1e, 0xe3, 0x82, 0x78, 0xa1, 0x76, 0xc0, 0x5f, 0xc2, 0xad, 0x23, 0x26, 0x06, 0xf3, 0x98, 0x0b,
	0x16, 0x0d, 0x58, 0x24, 0xdc, 0xa9, 0x4b, 0x89, 0x60, 0x0e, 0xfb, 0x29, 0x66, 0x5c, 0xa0, 0xdb,
	0x00, 0x54, 0x1b, 0xc7, 0xee, 0xa4, 0x5b, 0xde, 0x29, 0xef, 0x35, 0x9d, 0xa6, 0xd1, 0x8c, 0x26,
	0xf8, 0x08, 0x6e, 0x5f, 0xb0, 0x9c, 0x87, 0x81, 0xcf, 0x19, 0x7a, 0x00, 0xeb, 0x74, 0xee, 0x32,
	0x5f, 0x8c, 0x29, 0x8f, 0xc6, 0x94, 0x45, 0xc2, 0x80, 0x74, 0xb4, 0x7a, 0xc0, 0xd5, 0x32, 0xfc,
	0x10, 0x36, 0x5e, 0x2e, 0x86, 0x44, 0x90, 0x01, 0xf3, 0x05, 0x8b, 0xec, 0xf6, 0xd7, 0xa0, 0x12,
	0x27, 0xfb, 0xca, 0x9f, 0xf8, 0x15, 0x6c, 0x3b, 0x6c, 0xe6, 0xca, 0xfd, 0xae, 0xe0, 0x8e, 0x76,
	0xa1, 0x6d, 0xcf, 0xef, 0x13, 0x8f, 0x75, 0x57, 0x94, 0xa9, 0x65, 0x74, 0xc7, 0xc4, 0x63, 0xf8,
	0x47, 0xb8, 0x73, 0x8e, 0xf4, 0x8d, 0xcb, 0xc5, 0x77, 0xae, 0x38, 0x7d, 0xee, 0xce, 0x53, 0xb8,
	0x47, 0xd0, 0x99, 0xd0, 0xb9, 0xcb, 0xc5, 0x78, 0xaa, 0xf4, 0x6a, 0x87, 0xd6, 0x01, 0xee, 0xa7,
	0x93, 0xdd, 0xcf, 0xa2, 0x18, 0x84, 0xb6, 0x5e, 0xa8, 0x25, 0xfc, 0x4f, 0x19, 0x7a, 0x45, 0xc7,
	0x37, 0xd9, 0x52, 0xd9, 0x56, 0xd9, 0x7a, 0xc7, 0x16, 0xe7, 0xd9, 0x96, 0x9a, 0xaf, 0xd9, 0xa2,
	0x28, 0x99, 0x2b, 0x05, 0xc9, 0x44, 0x5b, 0xd0, 0xa0, 0x44, 0xdb, 0x2b, 0xca, 0x5e, 0xa7, 0x44,
	0x19, 0xb2, 0xb7, 0x59, 0xfd, 0xe8, 0x36, 0x73, 0xc9, 0xaa, 0xe5, 0x92, 0x85, 0x6e, 0x41, 0x93,
	0x06, 0xfe, 0xd4, 0x9d, 0x79, 0x24, 0xec, 0xd6, 0x0d, 0x80, 0x55, 0xe0, 0x5f, 0xca, 0xd0, 0x31,
	0x64, 0x70, 0x18, 0x0d, 0xa2, 0xc9, 0x25, 0xfc, 0xb9, 0xc2, 0xf5, 0xd8, 0x3b, 0xad, 0x9c, 0xdf,
	0x69, 0x41, 0x1a, 0xaa, 0x45, 0x9c, 0x7a, 0x05, 0x37, 0xb2, 0x57, 0x92, 0xe4, 0xf9, 0x31, 0xd4,
	0x27, 0x54, 0x6a, 0xba, 0xe5, 0x9d, 0xca, 0x5e, 0xeb, 0xe0, 0xbf, 0x17, 0x5d, 0xe4, 0x6b, 0x41,
	0x44, 0xcc, 0x1d, 0xe3, 0x8d, 0x7f, 0x2d, 0xc3, 0xc3, 0x3c, 0x57, 0xce, 0x79, 0xef, 0x06, 0x7e,
	0xb2, 0xc7, 0x3d, 0xe8, 0xd0, 0xb4, 0x21, 0xe1, 0x7d, 0x5a, 0x89, 0x10, 0x54, 0x4f, 0x03, 0x6e,
	0xef, 0x51, 0xfd, 0x46, 0x7b, 0x50, 0x95, 0x94, 0xe9, 0x56, 0xd4, 0xd9, 0x36, 0xfb, 0xba, 0xd8,
	0x33, 0x79, 0x75, 0x94, 0x07, 0xfe, 0xa3, 0x02, 0x1b, 0xc7, 0x4c, 0xbc, 0x0f, 0xa2, 0x77, 0x23,
	0x7f, 0x1a, 0xa4, 0x79, 0x14, 0x73, 0x16, 0x8d, 0x69, 0x10, 0xfb, 0xba, 0xe0, 0x6a, 0x4e, 0x53,
	0x6a, 0x06, 0x52, 0x21, 0xcd, 0x72, 0x23, 0x63, 0x5e, 0xd1, 0x66, 0xa9, 0xd1, 0xe6, 0x6d, 0x58,
	0xf5, 0xb9, 0x31, 0x56, 0x94, 0xb1, 0xe1, 0x73, 0x6d, 0x7a, 0x08, 0xeb, 0x34, 0xf0, 0x05, 0x71,
	0xfd, 0x04, 0xbd, 0xaa, 0x3c, 0xd6, 0x12, 0xb5, 0x76, 0xec, 0x42, 0x43, 0x44, 0x64, 0x3a, 0x75,
	0xa9, 0x62, 0x51, 0xcd, 0xb1, 0x22, 0xba, 0x09, 0x4d, 0x1a, 0xc6, 0x63, 0x11, 0x08, 0x32, 0x37,
	0x0c, 0x5a, 0xa5, 0x61, 0xfc, 0x46, 0xca, 0x72, 0x6b, 0x69, 0x8c, 0x39, 0x9b, 0x74, 0x1b, 0xca,
	0xd6, 0xa0, 0x61, 0x7c, 0xc2, 0x99, 0xa2, 0x8a, 0xc7, 0xbc, 0x20, 0x5a, 0x98, 0xa5, 0xab, 0x9a,
	0x2a, 0x5a, 0xa7, 0x57, 0xdf, 0x01, 0x23, 0x6a, 0x80, 0xa6, 0xf2, 0x00, 0xad, 0x52, 0x18, 0x77,
	0xa1, 0xc3, 0x45, 0x10, 0x91, 0x19, 0x33, 0x20, 0xa0, 0x5c, 0xda, 0x46, 0xa9, 0x51, 0x76, 0xc1,
	0xca, 0x1a, 0xa6, 0xa5, 0x37, 0x32, 0x3a, 0x8b, 0xe3, 0xeb, 0xb4, 0x9b, 0x24, 0xb4, 0x55, 0x8c,
	0x6d, 0xa3, 0xd4, 0x29, 0xb8, 0x0f, 0x6b, 0x7e, 0x30, 0x61, 0x61, 0x10, 0xd9, 0x4c, 0x77, 0x76,
	0xca, 0x7b, 0x1d, 0xa7, 0x63, 0xb5, 0xca, 0x0d, 0x3f, 0x82, 0xeb, 0xc3, 0xc1, 0xb7, 0x67, 0x2c,
	0x3a, 0x73, 0xd9, 0x7b, 0xfb, 0xe0, 0xdc, 0x82, 0x66, 0xf2, 0x52, 0xdb, 0xaa, 0x49, 0x14, 0xf8,
	0xcf, 0x32, 0xa0, 0xf4, 0x9a, 0xf4, 0xeb, 0x71, 0x71, 0xad, 0x3d, 0x86, 0x3a, 0x57, 0x74, 0x56,
	0x37, 0x7e, 0x05, 0xd2, 0x6b, 0xef, 0xec, 0x59, 0x2a, 0x1f, 0x9d, 0x45, 0xe6, 0x3c, 0x1a, 0x73,
	0x77, 0xe6, 0x13, 0x11, 0x47, 0xcc, 0x14, 0x22, 0x44, 0xaf, 0xad, 0x46, 0x3a, 0xf0, 0x94, 0x83,
	0x7e, 0x53, 0x80, 0x27, 0x0e, 0x18, 0xc1, 0xb5, 0x21, 0xe1, 0xa7, 0x4f, 0x03, 0x12, 0x4d, 0x4c,
	0xfc, 0xf8, 0xef, 0x32, 0x5c, 0x4f, 0x29, 0x4d, 0x80, 0xbb, 0xd0, 0x56, 0xd7, 0x36, 0x76, 0x7d,
	0x1a, 0x78, 0xcc, 0x10, 0xbb, 0xa5, 0x74, 0x23, 0xa5, 0x42, 0x8f, 0xa0, 0x43, 0xe3, 0x28, 0x92,
	0x8f, 0x43, 0xcc, 0xc9, 0x8c, 0x99, 0x58, 0xdb, 0xa6, 0x88, 0x4e, 0xa4, 0xce, 0x69, 0x1b, 0x17,
	0x25, 0xa1, 0x5d, 0xa8, 0xbe, 0x67, 0xec, 0x9d, 0x29, 0xb7, 0x8e, 0xf1, 0xd4, 0x78, 0x8e, 0x32,
	0xa1, 0xbb, 0x50, 0xf3, 0x02, 0x5f, 0x9c, 0x76, 0xab, 0x45, 0x3e, 0xda, 0x26, 0x71, 0x16, 0x8c,
	0x44, 0xdd, 0x5a, 0x21, 0x8e, 0x34, 0x61, 0x01, 0x75, 0x73, 0xce, 0x1b, 0x50, 0xcf, 0x04, 0x61,
	0x24, 0xd4, 0x87, 0xea, 0x84, 0x08, 0x7b, 0xec, 0x5e, 0x5f, 0xf7, 0xef, 0xbe, 0xed, 0xdf, 0xfd,
	0x37, 0x36, 0xf1, 0x8e, 0xf2, 0x43, 0x18, 0x6a, 0x3a, 0xce, 0x4a, 0x41, 0x9c, 0xda, 0x24, 0xe9,
	0x52, 0xd3, 0xa1, 0x66, 0x6a, 0x4f, 0x6f, 0x5c, 0x5c, 0x7b, 0xfa, 0x4d, 0xb8, 0xb0, 0xf6, 0xf4,
	0xab, 0xb0, 0xac, 0xf6, 0xf4, 0xab, 0xb0, 0xb4, 0xf6, 0xf4, 0xbb, 0xb0, 0xbc, 0xf6, 0xea, 0x7a,
	0xa3, 0x54, 0xed, 0xe1, 0x63, 0xd8, 0x1c, 0xf9, 0x67, 0x81, 0x4b, 0xd9, 0x90, 0x09, 0xe2, 0xce,
	0x6d, 0xc9, 0x6c, 0x41, 0x43, 0x30, 0xe2, 0x9d, 0x53, 0xbf, 0x2e, 0xc5, 0x91, 0x6a, 0x41, 0xae,
	0x5e, 0x20, 0x6d, 0xfa, 0xa1, 0x6d, 0x1a, 0xcd, 0x68, 0x82, 0x4f, 0x00, 0xbd, 0x70, 0xe5, 0x06,
	0x8b, 0xe7, 0x8c, 0xf1, 0x4b, 0xd1, 0x36, 0xa1, 0xc6, 0x05, 0x49, 0x3a, 0xaf, 0x16, 0x64, 0x93,
	0x62, 0x7e, 0xd2, 0xa4, 0x98, 0x3f, 0xc1, 0xbf, 0x95, 0xa1, 0xf5, 0x52, 0xf2, 0xc2, 0x34, 0xc2,
	0x5d, 0x68, 0x87, 0x64, 0xe1, 0x49, 0x62, 0xaa, 0x0b, 0xd6, 0xa8, 0x2d, 0xa3, 0x1b, 0xca, 0xbb,
	0xbc, 0x0f, 0x6b, 0xd6, 0x25, 0x55, 0xa8, 0x4d, 0xa7, 0x63, 0xb4, 0xba, 0x2e, 0x25, 0x75, 0x3c,
	0x26, 0x4e, 0x03, 0xbb, 0x9d, 0x91, 0xa4, 0x9e, 0x78, 0xa9, 0x27, 0xd9, 0x48, 0xf2, 0x29, 0x36,
	0xd1, 0x9a, 0xe2, 0xb3, 0x22, 0x1e, 0xc0, 0x46, 0x26, 0x74, 0x53, 0x66, 0xff, 0x83, 0x46, 0xa4,
	0x0e, 0xcd, 0x4d, 0x7b, 0x44, 0x86, 0x55, 0xa9, 0x78, 0x1c, 0xeb, 0x82, 0x9f, 0xc2, 0x75, 0xb9,
	0xfa, 0x8a, 0x97, 0xb1, 0x69, 0x2b, 0xc9, 0xa4, 0x4f, 0x09, 0xf8, 0x09, 0x74, 0x64, 0xaf, 0xe7,
	0x21, 0xa1, 0x4c, 0x82, 0xc9, 0xb6, 0xa8, 0xe6, 0x01, 0xbd, 0x58, 0xfd, 0x96, 0xf1, 0xd1, 0x53,
	0x12, 0x99, 0x9a, 0xae, 0x39, 0x46, 0xc2, 0x1f, 0x56, 0x00, 0xa5, 0x4f, 0x60, 0xa2, 0xe8, 0x42,
	0x83, 0xd0, 0xf3, 0x06, 0xd8, 0x74, 0xac, 0x28, 0xc1, 0x89, 0x10, 0xbe, 0xed, 0xb9, 0xf2, 0xb7,
	0xcc, 0xbd, 0x25, 0x89, 0x1f, 0x7b, 0x6f, 0x59, 0x64, 0x92, 0xdb, 0x31, 0xda, 0x63, 0xa5, 0x94,
	0xc7, 0xd7, 0xe4, 0xd5, 0x29, 0xd6, 0x82, 0x62, 0x18, 0xe7, 0x31, 0xd3, 0x37, 0x5b, 0x33, 0x0c,
	0x93, 0x1a, 0x75, 0xaf, 0x09, 0x65, 0xea, 0x05, 0x94, 0x69, 0x24, 0x94, 0x91, 0x27, 0xd6, 0x21,
	0x71, 0xd5, 0xdc, 0x64, 0xfd, 0x69, 0x51, 0x59, 0x22, 0x36, 0x71, 0x05, 0x57, 0x4d, 0x4d, 0x5a,
	0xb4, 0x28, 0x51, 0x04, 0xf9, 0x59, 0xf5, 0xb1, 0x9a, 0x23, 0x7f, 0xa2, 0xff, 0x43, 0xc3, 0xe7,
	0xe3, 0x29, 0x63, 0xbc, 0xdb, 0xca, 0x0c, 0x10, 0x99, 0x0c, 0x3b, 0x75, 0x9f, 0xcb, 0xbf, 0x07,
	0xbf, 0x57, 0x61, 0x65, 0x38, 0x40, 0xcf, 0xa0, 0x39, 0x88, 0x18, 0x11, 0xec, 0x30, 0x0c, 0xd1,
	0xcd, 0x6c, 0x67, 0x38, 0x0c, 0xc3, 0x21, 0x0b, 0xe7, 0x81, 0x22, 0x61, 0x6f, 0x3b, 0x67, 0xd4,
	0x29, 0xa7, 0x0c, 0x97, 0x24, 0xcc, 0x49, 0x38, 0xf9, 0x1c, 0x30, 0x43, 0x36, 0x67, 0x9f, 0x0a,
	0x73, 0x04, 0xeb, 0x3a, 0xa8, 0x24, 0x74, 0xb4, 0x95, 0xf5, 0x4f, 0x0c, 0x97, 0x02, 0xe9, 0xb0,
	0x3e, 0x03, 0x90, 0x0e, 0xec, 0x53, 0x81, 0x9e, 0x40, 0xdd, 0x3c, 0x07, 0x1b, 0x39, 0xb7, 0xd1,
	0xb0, 0xd7, 0xcb, 0xaf, 0x8d, 0x7d, 0xbd, 0x00, 0x97, 0xd0, 0x21, 0xac, 0xda, 0xe1, 0x01, 0x75,
	0x0d, 0x3b, 0x72, 0x33, 0x48, 0x6f, 0xbb, 0xc0, 0xa2, 0x6b, 0x0b, 0x97, 0x0e, 0xfe, 0xaa, 0x41,
	0x6d, 0x38, 0x38, 0x7c, 0x35, 0x42, 0xcf, 0x61, 0x2d, 0x3b, 0x12, 0x7f, 0x7c, 0xa2, 0x67, 0x5e,
	0x28, 0x16, 0xbd, 0xdb, 0x16, 0xad, 0x70, 0x22, 0xc7, 0x25, 0x44, 0xa1, 0x7b, 0xd1, 0x67, 0x18,
	0x7a, 0x50, 0xb8, 0x38, 0xf7, 0x9d, 0x76, 0xf9, 0x26, 0xa7, 0x45, 0xdf, 0x7a, 0x99, 0xf9, 0xbd,
	0xf8, 0xf4, 0xfd, 0x0b, 0x0f, 0x50, 0x38, 0xfc, 0xe3, 0x12, 0xfa, 0x0a, 0x5a, 0xa9, 0xc9, 0xbc,
	0x18, 0xb5, 0x67, 0x2b, 0x33, 0x3f, 0xc2, 0xe3, 0x12, 0xfa, 0x01, 0x50, 0xfe, 0x53, 0x11, 0xed,
	0x98, 0x35, 0x17, 0x7e, 0x04, 0xf7, 0x76, 0x97, 0x78, 0x24, 0xe0, 0xdf, 0xc3, 0xba, 0xc3, 0x38,
	0x13, 0x9f, 0x1f, 0xf9, 0x18, 0xda, 0xe9, 0x2f, 0x79, 0x64, 0x83, 0x2c, 0xf8, 0xbc, 0xef, 0xed,
	0x2c, 0x1f, 0x41, 0x99, 0x24, 0xeb, 0x04, 0xfe, 0x53, 0xf8, 0x2f, 0x06, 0x74, 0xd7, 0x00, 0x2f,
	0xfb, 0xff, 0x45, 0xef, 0xde, 0x72, 0xa7, 0x84, 0xcf, 0x1f, 0x56, 0xa0, 0x25, 0xdf, 0xc3, 0xd7,
	0x92, 0xe9, 0x94, 0xa1, 0x23, 0xb8, 0x66, 0xfc, 0x93, 0x31, 0x14, 0x6d, 0x25, 0x24, 0xc8, 0x4e,
	0xab, 0xbd, 0x6e, 0xde, 0x90, 0x4a, 0xc7, 0xc6, 0x09, 0x67, 0x51, 0xaa, 0xcf, 0xaa, 0x1a, 0xb1,
	0xc5, 0x95, 0x1f, 0x3d, 0x12, 0x56, 0x14, 0xb4, 0x66, 0x5c, 0x42, 0x2f, 0x60, 0x5d, 0xb5, 0xe1,
	0xf3, 0x8e, 0x97, 0x94, 0x70, 0xae, 0x0d, 0x27, 0x25, 0x9c, 0x6f, 0x8f, 0xb8, 0x84, 0x46, 0xd0,
	0xc9, 0x0c, 0x52, 0xe8, 0x66, 0x32, 0xb2, 0xe6, 0xc7, 0xab, 0xa5, 0x50, 0x6f, 0xeb, 0xea, 0xfe,
	0xbe, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x30, 0xfd, 0x76, 0x36, 0xa7, 0x12, 0x00, 0x00,
}
