// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payr/v1/micro/payr.proto

package payr

import (
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderStatus int32

const (
	OrderStatus_CONFIRMING  OrderStatus = 0
	OrderStatus_CONFIRMED   OrderStatus = 1
	OrderStatus_DEACTIVATED OrderStatus = 2
)

var OrderStatus_name = map[int32]string{
	0: "CONFIRMING",
	1: "CONFIRMED",
	2: "DEACTIVATED",
}

var OrderStatus_value = map[string]int32{
	"CONFIRMING":  0,
	"CONFIRMED":   1,
	"DEACTIVATED": 2,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{0}
}

type PlanStatus int32

const (
	PlanStatus_UNPAID  PlanStatus = 0
	PlanStatus_PAID    PlanStatus = 1
	PlanStatus_EXPRIED PlanStatus = 2
)

var PlanStatus_name = map[int32]string{
	0: "UNPAID",
	1: "PAID",
	2: "EXPRIED",
}

var PlanStatus_value = map[string]int32{
	"UNPAID":  0,
	"PAID":    1,
	"EXPRIED": 2,
}

func (x PlanStatus) String() string {
	return proto.EnumName(PlanStatus_name, int32(x))
}

func (PlanStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{1}
}

type RequestCodeRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Discount             float64  `protobuf:"fixed64,2,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCodeRequest) Reset()         { *m = RequestCodeRequest{} }
func (m *RequestCodeRequest) String() string { return proto.CompactTextString(m) }
func (*RequestCodeRequest) ProtoMessage()    {}
func (*RequestCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{0}
}

func (m *RequestCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCodeRequest.Unmarshal(m, b)
}
func (m *RequestCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCodeRequest.Marshal(b, m, deterministic)
}
func (m *RequestCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCodeRequest.Merge(m, src)
}
func (m *RequestCodeRequest) XXX_Size() int {
	return xxx_messageInfo_RequestCodeRequest.Size(m)
}
func (m *RequestCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCodeRequest proto.InternalMessageInfo

func (m *RequestCodeRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestCodeRequest) GetDiscount() float64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

type Code struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Discount             float64  `protobuf:"fixed64,3,opt,name=discount,proto3" json:"discount,omitempty"`
	Revenue              string   `protobuf:"bytes,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{1}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Code) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Code) GetDiscount() float64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Code) GetRevenue() string {
	if m != nil {
		return m.Revenue
	}
	return ""
}

type RequestCodeResponse struct {
	Codes                []*Code  `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCodeResponse) Reset()         { *m = RequestCodeResponse{} }
func (m *RequestCodeResponse) String() string { return proto.CompactTextString(m) }
func (*RequestCodeResponse) ProtoMessage()    {}
func (*RequestCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{2}
}

func (m *RequestCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCodeResponse.Unmarshal(m, b)
}
func (m *RequestCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCodeResponse.Marshal(b, m, deterministic)
}
func (m *RequestCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCodeResponse.Merge(m, src)
}
func (m *RequestCodeResponse) XXX_Size() int {
	return xxx_messageInfo_RequestCodeResponse.Size(m)
}
func (m *RequestCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCodeResponse proto.InternalMessageInfo

func (m *RequestCodeResponse) GetCodes() []*Code {
	if m != nil {
		return m.Codes
	}
	return nil
}

type ReportCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportCodeRequest) Reset()         { *m = ReportCodeRequest{} }
func (m *ReportCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ReportCodeRequest) ProtoMessage()    {}
func (*ReportCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{3}
}

func (m *ReportCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportCodeRequest.Unmarshal(m, b)
}
func (m *ReportCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportCodeRequest.Marshal(b, m, deterministic)
}
func (m *ReportCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportCodeRequest.Merge(m, src)
}
func (m *ReportCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ReportCodeRequest.Size(m)
}
func (m *ReportCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportCodeRequest proto.InternalMessageInfo

func (m *ReportCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ReportCodeResponse struct {
	Report               *Code    `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportCodeResponse) Reset()         { *m = ReportCodeResponse{} }
func (m *ReportCodeResponse) String() string { return proto.CompactTextString(m) }
func (*ReportCodeResponse) ProtoMessage()    {}
func (*ReportCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{4}
}

func (m *ReportCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportCodeResponse.Unmarshal(m, b)
}
func (m *ReportCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportCodeResponse.Marshal(b, m, deterministic)
}
func (m *ReportCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportCodeResponse.Merge(m, src)
}
func (m *ReportCodeResponse) XXX_Size() int {
	return xxx_messageInfo_ReportCodeResponse.Size(m)
}
func (m *ReportCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportCodeResponse proto.InternalMessageInfo

func (m *ReportCodeResponse) GetReport() *Code {
	if m != nil {
		return m.Report
	}
	return nil
}

type Order struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Order type, marking the kind of currency using.
	OrderType string `protobuf:"bytes,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	// How much money left to pay.
	Status               OrderStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=payr.OrderStatus" json:"status,omitempty"`
	IssuedAt             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	TeamId               string               `protobuf:"bytes,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	PlanType             string               `protobuf:"bytes,8,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	Time                 string               `protobuf:"bytes,9,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string               `protobuf:"bytes,10,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	SubId                string               `protobuf:"bytes,11,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	App                  *common.App          `protobuf:"bytes,12,opt,name=app,proto3" json:"app,omitempty"`
	ChartName            string               `protobuf:"bytes,13,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartIconUrl         string               `protobuf:"bytes,14,opt,name=chart_icon_url,json=chartIconUrl,proto3" json:"chart_icon_url,omitempty"`
	BalanceToken         string               `protobuf:"bytes,3,opt,name=balance_token,json=balanceToken,proto3" json:"balance_token,omitempty"`
	BalanceUsd           string               `protobuf:"bytes,15,opt,name=balance_usd,json=balanceUsd,proto3" json:"balance_usd,omitempty"`
	BalanceUsdOriginal   string               `protobuf:"bytes,16,opt,name=balance_usd_original,json=balanceUsdOriginal,proto3" json:"balance_usd_original,omitempty"`
	BalanceTokenOriginal string               `protobuf:"bytes,17,opt,name=balance_token_original,json=balanceTokenOriginal,proto3" json:"balance_token_original,omitempty"`
	Code                 string               `protobuf:"bytes,18,opt,name=code,proto3" json:"code,omitempty"`
	Discount             float64              `protobuf:"fixed64,19,opt,name=discount,proto3" json:"discount,omitempty"`
	DiscountUsd          string               `protobuf:"bytes,20,opt,name=discount_usd,json=discountUsd,proto3" json:"discount_usd,omitempty"`
	DiscountToken        string               `protobuf:"bytes,21,opt,name=discount_token,json=discountToken,proto3" json:"discount_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{5}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_CONFIRMING
}

func (m *Order) GetIssuedAt() *timestamp.Timestamp {
	if m != nil {
		return m.IssuedAt
	}
	return nil
}

func (m *Order) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *Order) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *Order) GetPlanType() string {
	if m != nil {
		return m.PlanType
	}
	return ""
}

func (m *Order) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Order) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

func (m *Order) GetSubId() string {
	if m != nil {
		return m.SubId
	}
	return ""
}

func (m *Order) GetApp() *common.App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *Order) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *Order) GetChartIconUrl() string {
	if m != nil {
		return m.ChartIconUrl
	}
	return ""
}

func (m *Order) GetBalanceToken() string {
	if m != nil {
		return m.BalanceToken
	}
	return ""
}

func (m *Order) GetBalanceUsd() string {
	if m != nil {
		return m.BalanceUsd
	}
	return ""
}

func (m *Order) GetBalanceUsdOriginal() string {
	if m != nil {
		return m.BalanceUsdOriginal
	}
	return ""
}

func (m *Order) GetBalanceTokenOriginal() string {
	if m != nil {
		return m.BalanceTokenOriginal
	}
	return ""
}

func (m *Order) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Order) GetDiscount() float64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Order) GetDiscountUsd() string {
	if m != nil {
		return m.DiscountUsd
	}
	return ""
}

func (m *Order) GetDiscountToken() string {
	if m != nil {
		return m.DiscountToken
	}
	return ""
}

type Subscription struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              string               `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PlanType             string               `protobuf:"bytes,3,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	TeamId               string               `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Status               PlanStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=payr.PlanStatus" json:"status,omitempty"`
	IssuedAt             *timestamp.Timestamp `protobuf:"bytes,6,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Time                 string               `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string               `protobuf:"bytes,9,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	ChartName            string               `protobuf:"bytes,10,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartIconUrl         string               `protobuf:"bytes,11,opt,name=chart_icon_url,json=chartIconUrl,proto3" json:"chart_icon_url,omitempty"`
	OrderType            string               `protobuf:"bytes,12,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	BalanceUsdOriginal   string               `protobuf:"bytes,13,opt,name=balance_usd_original,json=balanceUsdOriginal,proto3" json:"balance_usd_original,omitempty"`
	BalanceTokenOriginal string               `protobuf:"bytes,14,opt,name=balance_token_original,json=balanceTokenOriginal,proto3" json:"balance_token_original,omitempty"`
	Code                 string               `protobuf:"bytes,15,opt,name=code,proto3" json:"code,omitempty"`
	Discount             float64              `protobuf:"fixed64,16,opt,name=discount,proto3" json:"discount,omitempty"`
	DiscountUsd          string               `protobuf:"bytes,17,opt,name=discount_usd,json=discountUsd,proto3" json:"discount_usd,omitempty"`
	DiscountToken        string               `protobuf:"bytes,18,opt,name=discount_token,json=discountToken,proto3" json:"discount_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{6}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Subscription) GetPlanType() string {
	if m != nil {
		return m.PlanType
	}
	return ""
}

func (m *Subscription) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *Subscription) GetStatus() PlanStatus {
	if m != nil {
		return m.Status
	}
	return PlanStatus_UNPAID
}

func (m *Subscription) GetIssuedAt() *timestamp.Timestamp {
	if m != nil {
		return m.IssuedAt
	}
	return nil
}

func (m *Subscription) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *Subscription) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Subscription) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

func (m *Subscription) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *Subscription) GetChartIconUrl() string {
	if m != nil {
		return m.ChartIconUrl
	}
	return ""
}

func (m *Subscription) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Subscription) GetBalanceUsdOriginal() string {
	if m != nil {
		return m.BalanceUsdOriginal
	}
	return ""
}

func (m *Subscription) GetBalanceTokenOriginal() string {
	if m != nil {
		return m.BalanceTokenOriginal
	}
	return ""
}

func (m *Subscription) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Subscription) GetDiscount() float64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Subscription) GetDiscountUsd() string {
	if m != nil {
		return m.DiscountUsd
	}
	return ""
}

func (m *Subscription) GetDiscountToken() string {
	if m != nil {
		return m.DiscountToken
	}
	return ""
}

type PlanType struct {
	PlanType             string   `protobuf:"bytes,1,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	CpuNumber            string   `protobuf:"bytes,2,opt,name=cpu_number,json=cpuNumber,proto3" json:"cpu_number,omitempty"`
	MemoryNumber         string   `protobuf:"bytes,3,opt,name=memory_number,json=memoryNumber,proto3" json:"memory_number,omitempty"`
	StorageNumber        string   `protobuf:"bytes,4,opt,name=storage_number,json=storageNumber,proto3" json:"storage_number,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	PriceWeek            string   `protobuf:"bytes,6,opt,name=price_week,json=priceWeek,proto3" json:"price_week,omitempty"`
	PriceMonth           string   `protobuf:"bytes,7,opt,name=price_month,json=priceMonth,proto3" json:"price_month,omitempty"`
	PriceHour            string   `protobuf:"bytes,8,opt,name=price_hour,json=priceHour,proto3" json:"price_hour,omitempty"`
	PlanTitle            string   `protobuf:"bytes,9,opt,name=plan_title,json=planTitle,proto3" json:"plan_title,omitempty"`
	PlanSet              string   `protobuf:"bytes,10,opt,name=plan_set,json=planSet,proto3" json:"plan_set,omitempty"`
	PlanStatus           string   `protobuf:"bytes,11,opt,name=plan_status,json=planStatus,proto3" json:"plan_status,omitempty"`
	PlanFeatured         bool     `protobuf:"varint,12,opt,name=plan_featured,json=planFeatured,proto3" json:"plan_featured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanType) Reset()         { *m = PlanType{} }
func (m *PlanType) String() string { return proto.CompactTextString(m) }
func (*PlanType) ProtoMessage()    {}
func (*PlanType) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{7}
}

func (m *PlanType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanType.Unmarshal(m, b)
}
func (m *PlanType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanType.Marshal(b, m, deterministic)
}
func (m *PlanType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanType.Merge(m, src)
}
func (m *PlanType) XXX_Size() int {
	return xxx_messageInfo_PlanType.Size(m)
}
func (m *PlanType) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanType.DiscardUnknown(m)
}

var xxx_messageInfo_PlanType proto.InternalMessageInfo

func (m *PlanType) GetPlanType() string {
	if m != nil {
		return m.PlanType
	}
	return ""
}

func (m *PlanType) GetCpuNumber() string {
	if m != nil {
		return m.CpuNumber
	}
	return ""
}

func (m *PlanType) GetMemoryNumber() string {
	if m != nil {
		return m.MemoryNumber
	}
	return ""
}

func (m *PlanType) GetStorageNumber() string {
	if m != nil {
		return m.StorageNumber
	}
	return ""
}

func (m *PlanType) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PlanType) GetPriceWeek() string {
	if m != nil {
		return m.PriceWeek
	}
	return ""
}

func (m *PlanType) GetPriceMonth() string {
	if m != nil {
		return m.PriceMonth
	}
	return ""
}

func (m *PlanType) GetPriceHour() string {
	if m != nil {
		return m.PriceHour
	}
	return ""
}

func (m *PlanType) GetPlanTitle() string {
	if m != nil {
		return m.PlanTitle
	}
	return ""
}

func (m *PlanType) GetPlanSet() string {
	if m != nil {
		return m.PlanSet
	}
	return ""
}

func (m *PlanType) GetPlanStatus() string {
	if m != nil {
		return m.PlanStatus
	}
	return ""
}

func (m *PlanType) GetPlanFeatured() bool {
	if m != nil {
		return m.PlanFeatured
	}
	return false
}

type ListSubsRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubsRequest) Reset()         { *m = ListSubsRequest{} }
func (m *ListSubsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubsRequest) ProtoMessage()    {}
func (*ListSubsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{8}
}

func (m *ListSubsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubsRequest.Unmarshal(m, b)
}
func (m *ListSubsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubsRequest.Merge(m, src)
}
func (m *ListSubsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubsRequest.Size(m)
}
func (m *ListSubsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubsRequest proto.InternalMessageInfo

func (m *ListSubsRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type ListSubsResponse struct {
	Subs                 []*Subscription `protobuf:"bytes,1,rep,name=subs,proto3" json:"subs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSubsResponse) Reset()         { *m = ListSubsResponse{} }
func (m *ListSubsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubsResponse) ProtoMessage()    {}
func (*ListSubsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{9}
}

func (m *ListSubsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubsResponse.Unmarshal(m, b)
}
func (m *ListSubsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubsResponse.Merge(m, src)
}
func (m *ListSubsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubsResponse.Size(m)
}
func (m *ListSubsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubsResponse proto.InternalMessageInfo

func (m *ListSubsResponse) GetSubs() []*Subscription {
	if m != nil {
		return m.Subs
	}
	return nil
}

type ListPlanResponse struct {
	Plans                []*PlanType `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPlanResponse) Reset()         { *m = ListPlanResponse{} }
func (m *ListPlanResponse) String() string { return proto.CompactTextString(m) }
func (*ListPlanResponse) ProtoMessage()    {}
func (*ListPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{10}
}

func (m *ListPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanResponse.Unmarshal(m, b)
}
func (m *ListPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanResponse.Marshal(b, m, deterministic)
}
func (m *ListPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanResponse.Merge(m, src)
}
func (m *ListPlanResponse) XXX_Size() int {
	return xxx_messageInfo_ListPlanResponse.Size(m)
}
func (m *ListPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanResponse proto.InternalMessageInfo

func (m *ListPlanResponse) GetPlans() []*PlanType {
	if m != nil {
		return m.Plans
	}
	return nil
}

type CollectFeeRequest struct {
	CpuNumber            string   `protobuf:"bytes,1,opt,name=cpu_number,json=cpuNumber,proto3" json:"cpu_number,omitempty"`
	MemoryNumber         string   `protobuf:"bytes,2,opt,name=memory_number,json=memoryNumber,proto3" json:"memory_number,omitempty"`
	StorageNumber        string   `protobuf:"bytes,3,opt,name=storage_number,json=storageNumber,proto3" json:"storage_number,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string   `protobuf:"bytes,5,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectFeeRequest) Reset()         { *m = CollectFeeRequest{} }
func (m *CollectFeeRequest) String() string { return proto.CompactTextString(m) }
func (*CollectFeeRequest) ProtoMessage()    {}
func (*CollectFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{11}
}

func (m *CollectFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectFeeRequest.Unmarshal(m, b)
}
func (m *CollectFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectFeeRequest.Marshal(b, m, deterministic)
}
func (m *CollectFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectFeeRequest.Merge(m, src)
}
func (m *CollectFeeRequest) XXX_Size() int {
	return xxx_messageInfo_CollectFeeRequest.Size(m)
}
func (m *CollectFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectFeeRequest proto.InternalMessageInfo

func (m *CollectFeeRequest) GetCpuNumber() string {
	if m != nil {
		return m.CpuNumber
	}
	return ""
}

func (m *CollectFeeRequest) GetMemoryNumber() string {
	if m != nil {
		return m.MemoryNumber
	}
	return ""
}

func (m *CollectFeeRequest) GetStorageNumber() string {
	if m != nil {
		return m.StorageNumber
	}
	return ""
}

func (m *CollectFeeRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *CollectFeeRequest) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

func (m *CollectFeeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PlanFeeRequest struct {
	Plan                 string   `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	TeamId               string   `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TimeUnit             string   `protobuf:"bytes,4,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanFeeRequest) Reset()         { *m = PlanFeeRequest{} }
func (m *PlanFeeRequest) String() string { return proto.CompactTextString(m) }
func (*PlanFeeRequest) ProtoMessage()    {}
func (*PlanFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{12}
}

func (m *PlanFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanFeeRequest.Unmarshal(m, b)
}
func (m *PlanFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanFeeRequest.Marshal(b, m, deterministic)
}
func (m *PlanFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanFeeRequest.Merge(m, src)
}
func (m *PlanFeeRequest) XXX_Size() int {
	return xxx_messageInfo_PlanFeeRequest.Size(m)
}
func (m *PlanFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlanFeeRequest proto.InternalMessageInfo

func (m *PlanFeeRequest) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *PlanFeeRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *PlanFeeRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *PlanFeeRequest) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

func (m *PlanFeeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CollectFeeResponse struct {
	Plan                 string   `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Fee                  string   `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	DiscountToken        string   `protobuf:"bytes,4,opt,name=discount_token,json=discountToken,proto3" json:"discount_token,omitempty"`
	DiscountFee          string   `protobuf:"bytes,5,opt,name=discount_fee,json=discountFee,proto3" json:"discount_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectFeeResponse) Reset()         { *m = CollectFeeResponse{} }
func (m *CollectFeeResponse) String() string { return proto.CompactTextString(m) }
func (*CollectFeeResponse) ProtoMessage()    {}
func (*CollectFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{13}
}

func (m *CollectFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectFeeResponse.Unmarshal(m, b)
}
func (m *CollectFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectFeeResponse.Marshal(b, m, deterministic)
}
func (m *CollectFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectFeeResponse.Merge(m, src)
}
func (m *CollectFeeResponse) XXX_Size() int {
	return xxx_messageInfo_CollectFeeResponse.Size(m)
}
func (m *CollectFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectFeeResponse proto.InternalMessageInfo

func (m *CollectFeeResponse) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *CollectFeeResponse) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *CollectFeeResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CollectFeeResponse) GetDiscountToken() string {
	if m != nil {
		return m.DiscountToken
	}
	return ""
}

func (m *CollectFeeResponse) GetDiscountFee() string {
	if m != nil {
		return m.DiscountFee
	}
	return ""
}

type NewOrderRequest struct {
	TeamId               string      `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Type                 string      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Plan                 string      `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	Time                 string      `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	TimeUnit             string      `protobuf:"bytes,5,opt,name=time_unit,json=timeUnit,proto3" json:"time_unit,omitempty"`
	App                  *common.App `protobuf:"bytes,6,opt,name=App,proto3" json:"App,omitempty"`
	ClusterId            string      `protobuf:"bytes,7,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Code                 string      `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewOrderRequest) Reset()         { *m = NewOrderRequest{} }
func (m *NewOrderRequest) String() string { return proto.CompactTextString(m) }
func (*NewOrderRequest) ProtoMessage()    {}
func (*NewOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{14}
}

func (m *NewOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderRequest.Unmarshal(m, b)
}
func (m *NewOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderRequest.Marshal(b, m, deterministic)
}
func (m *NewOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderRequest.Merge(m, src)
}
func (m *NewOrderRequest) XXX_Size() int {
	return xxx_messageInfo_NewOrderRequest.Size(m)
}
func (m *NewOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderRequest proto.InternalMessageInfo

func (m *NewOrderRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *NewOrderRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewOrderRequest) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *NewOrderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *NewOrderRequest) GetTimeUnit() string {
	if m != nil {
		return m.TimeUnit
	}
	return ""
}

func (m *NewOrderRequest) GetApp() *common.App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *NewOrderRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *NewOrderRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type NewOrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Expiration           int64    `protobuf:"varint,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderResponse) Reset()         { *m = NewOrderResponse{} }
func (m *NewOrderResponse) String() string { return proto.CompactTextString(m) }
func (*NewOrderResponse) ProtoMessage()    {}
func (*NewOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{15}
}

func (m *NewOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderResponse.Unmarshal(m, b)
}
func (m *NewOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderResponse.Marshal(b, m, deterministic)
}
func (m *NewOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderResponse.Merge(m, src)
}
func (m *NewOrderResponse) XXX_Size() int {
	return xxx_messageInfo_NewOrderResponse.Size(m)
}
func (m *NewOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderResponse proto.InternalMessageInfo

func (m *NewOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *NewOrderResponse) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type TeamID struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamID) Reset()         { *m = TeamID{} }
func (m *TeamID) String() string { return proto.CompactTextString(m) }
func (*TeamID) ProtoMessage()    {}
func (*TeamID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{16}
}

func (m *TeamID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamID.Unmarshal(m, b)
}
func (m *TeamID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamID.Marshal(b, m, deterministic)
}
func (m *TeamID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamID.Merge(m, src)
}
func (m *TeamID) XXX_Size() int {
	return xxx_messageInfo_TeamID.Size(m)
}
func (m *TeamID) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamID.DiscardUnknown(m)
}

var xxx_messageInfo_TeamID proto.InternalMessageInfo

func (m *TeamID) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type OrderStatusResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatusResponse) Reset()         { *m = OrderStatusResponse{} }
func (m *OrderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*OrderStatusResponse) ProtoMessage()    {}
func (*OrderStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{17}
}

func (m *OrderStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusResponse.Unmarshal(m, b)
}
func (m *OrderStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusResponse.Marshal(b, m, deterministic)
}
func (m *OrderStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusResponse.Merge(m, src)
}
func (m *OrderStatusResponse) XXX_Size() int {
	return xxx_messageInfo_OrderStatusResponse.Size(m)
}
func (m *OrderStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusResponse proto.InternalMessageInfo

func (m *OrderStatusResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type WithdrawRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CurrencyType         string   `protobuf:"bytes,2,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TargetAddress        string   `protobuf:"bytes,4,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{18}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *WithdrawRequest) GetCurrencyType() string {
	if m != nil {
		return m.CurrencyType
	}
	return ""
}

func (m *WithdrawRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *WithdrawRequest) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

type WithdrawResponse struct {
	ReqId                string   `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	TransanctionHash     string   `protobuf:"bytes,4,opt,name=transanction_hash,json=transanctionHash,proto3" json:"transanction_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{19}
}

func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(m, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

func (m *WithdrawResponse) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *WithdrawResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WithdrawResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *WithdrawResponse) GetTransanctionHash() string {
	if m != nil {
		return m.TransanctionHash
	}
	return ""
}

type PaymentHistoryResponse struct {
	Payments             []*common.Payment `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PaymentHistoryResponse) Reset()         { *m = PaymentHistoryResponse{} }
func (m *PaymentHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentHistoryResponse) ProtoMessage()    {}
func (*PaymentHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f994f2a80bf3f67, []int{20}
}

func (m *PaymentHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentHistoryResponse.Unmarshal(m, b)
}
func (m *PaymentHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentHistoryResponse.Marshal(b, m, deterministic)
}
func (m *PaymentHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentHistoryResponse.Merge(m, src)
}
func (m *PaymentHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentHistoryResponse.Size(m)
}
func (m *PaymentHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentHistoryResponse proto.InternalMessageInfo

func (m *PaymentHistoryResponse) GetPayments() []*common.Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func init() {
	proto.RegisterEnum("payr.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterEnum("payr.PlanStatus", PlanStatus_name, PlanStatus_value)
	proto.RegisterType((*RequestCodeRequest)(nil), "payr.RequestCodeRequest")
	proto.RegisterType((*Code)(nil), "payr.Code")
	proto.RegisterType((*RequestCodeResponse)(nil), "payr.RequestCodeResponse")
	proto.RegisterType((*ReportCodeRequest)(nil), "payr.ReportCodeRequest")
	proto.RegisterType((*ReportCodeResponse)(nil), "payr.ReportCodeResponse")
	proto.RegisterType((*Order)(nil), "payr.Order")
	proto.RegisterType((*Subscription)(nil), "payr.Subscription")
	proto.RegisterType((*PlanType)(nil), "payr.PlanType")
	proto.RegisterType((*ListSubsRequest)(nil), "payr.ListSubsRequest")
	proto.RegisterType((*ListSubsResponse)(nil), "payr.ListSubsResponse")
	proto.RegisterType((*ListPlanResponse)(nil), "payr.ListPlanResponse")
	proto.RegisterType((*CollectFeeRequest)(nil), "payr.CollectFeeRequest")
	proto.RegisterType((*PlanFeeRequest)(nil), "payr.PlanFeeRequest")
	proto.RegisterType((*CollectFeeResponse)(nil), "payr.CollectFeeResponse")
	proto.RegisterType((*NewOrderRequest)(nil), "payr.NewOrderRequest")
	proto.RegisterType((*NewOrderResponse)(nil), "payr.NewOrderResponse")
	proto.RegisterType((*TeamID)(nil), "payr.TeamID")
	proto.RegisterType((*OrderStatusResponse)(nil), "payr.OrderStatusResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "payr.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "payr.WithdrawResponse")
	proto.RegisterType((*PaymentHistoryResponse)(nil), "payr.PaymentHistoryResponse")
}

func init() { proto.RegisterFile("payr/v1/micro/payr.proto", fileDescriptor_0f994f2a80bf3f67) }

var fileDescriptor_0f994f2a80bf3f67 = []byte{
	// 1586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xe9, 0x6e, 0xdb, 0xc6,
	0x13, 0x37, 0x2d, 0x51, 0xc7, 0x48, 0x96, 0xe5, 0xf5, 0x11, 0x46, 0xff, 0x23, 0x0e, 0x9d, 0xb4,
	0x6e, 0x0a, 0xd8, 0x8d, 0x5b, 0x20, 0x6e, 0x8a, 0x16, 0x10, 0x7c, 0xd4, 0x42, 0x1b, 0xc7, 0x60,
	0xec, 0xa6, 0xdf, 0x04, 0x4a, 0xdc, 0x58, 0x44, 0xc4, 0x23, 0xcb, 0x65, 0x52, 0x01, 0xfd, 0x54,
	0xa0, 0xc8, 0x3b, 0xf4, 0x25, 0xfa, 0x10, 0x7d, 0x8c, 0x7e, 0xef, 0x73, 0x14, 0x7b, 0x91, 0x4b,
	0x5a, 0xae, 0xdd, 0x7c, 0xd2, 0xee, 0x1c, 0xbb, 0x33, 0xb3, 0xbf, 0x39, 0x28, 0xb0, 0x62, 0x77,
	0x46, 0x76, 0xdf, 0x3e, 0xde, 0x0d, 0xfc, 0x31, 0x89, 0x76, 0xd9, 0x6e, 0x27, 0x26, 0x11, 0x8d,
	0x50, 0x95, 0xad, 0x7b, 0xab, 0xe3, 0x28, 0x08, 0xa2, 0x70, 0x57, 0xfc, 0x08, 0x56, 0xef, 0xde,
	0x65, 0x14, 0x5d, 0x4e, 0xf1, 0x2e, 0xdf, 0x8d, 0xd2, 0x57, 0xbb, 0xd4, 0x0f, 0x70, 0x42, 0xdd,
	0x20, 0x16, 0x02, 0xf6, 0x09, 0x20, 0x07, 0xbf, 0x49, 0x71, 0x42, 0x0f, 0x22, 0x0f, 0xcb, 0x25,
	0xda, 0x80, 0x5a, 0x98, 0x06, 0x23, 0x4c, 0x2c, 0x63, 0xd3, 0xd8, 0x36, 0x1d, 0xb9, 0x43, 0x3d,
	0x68, 0x78, 0x7e, 0x32, 0x8e, 0xd2, 0x90, 0x5a, 0x8b, 0x9b, 0xc6, 0xb6, 0xe1, 0x64, 0x7b, 0x7b,
	0x02, 0x55, 0x76, 0x04, 0x42, 0x50, 0x1d, 0x47, 0x1e, 0xe6, 0x9a, 0x4d, 0x87, 0xaf, 0xd9, 0x79,
	0x09, 0x75, 0x69, 0x9a, 0x70, 0xad, 0xa6, 0x23, 0x77, 0x85, 0xf3, 0x2a, 0xc5, 0xf3, 0x90, 0x05,
	0x75, 0x82, 0xdf, 0xe2, 0x30, 0xc5, 0x56, 0x95, 0x2b, 0xa9, 0xad, 0xfd, 0x04, 0x56, 0x0b, 0x36,
	0x27, 0x71, 0x14, 0x26, 0x18, 0x6d, 0x82, 0xc9, 0x2e, 0x4b, 0x2c, 0x63, 0xb3, 0xb2, 0xdd, 0xda,
	0x83, 0x1d, 0x1e, 0x22, 0x2e, 0x22, 0x18, 0xf6, 0xc7, 0xb0, 0xe2, 0xe0, 0x38, 0x22, 0x05, 0x5f,
	0xe7, 0xd8, 0x6b, 0xef, 0xb3, 0xa8, 0xe4, 0x82, 0xf2, 0x02, 0x1b, 0x6a, 0x84, 0x53, 0xb9, 0x6c,
	0xf1, 0x06, 0xc9, 0xb1, 0xff, 0x32, 0xc1, 0x7c, 0x4e, 0x3c, 0x4c, 0x50, 0x07, 0x16, 0x7d, 0x4f,
	0x9e, 0xba, 0xe8, 0x7b, 0xe8, 0x7f, 0x00, 0x11, 0x63, 0x0c, 0xe9, 0x2c, 0xc6, 0x32, 0x0e, 0x4d,
	0x4e, 0x39, 0x9f, 0xc5, 0x18, 0x7d, 0x92, 0x85, 0x88, 0x79, 0xdb, 0xd9, 0x5b, 0x11, 0x87, 0xf3,
	0xb3, 0x5e, 0x70, 0x46, 0x16, 0xb5, 0x27, 0xd0, 0xf4, 0x93, 0x24, 0xc5, 0xde, 0xd0, 0xa5, 0x96,
	0xc9, 0x4d, 0xe9, 0xed, 0x88, 0x87, 0xde, 0x51, 0x0f, 0xbd, 0x73, 0xae, 0x1e, 0xda, 0x69, 0x08,
	0xe1, 0x3e, 0x45, 0x4f, 0x01, 0xf0, 0x4f, 0xb1, 0x4f, 0x5c, 0xea, 0x47, 0xa1, 0x55, 0xbb, 0x51,
	0x53, 0x93, 0x46, 0x77, 0xa0, 0x4e, 0xb1, 0x1b, 0x0c, 0x7d, 0xcf, 0xaa, 0x8b, 0x37, 0x64, 0xdb,
	0x81, 0x87, 0xfe, 0x03, 0xcd, 0x78, 0xea, 0x86, 0xc2, 0xad, 0x06, 0x67, 0x35, 0x18, 0x81, 0x7b,
	0x85, 0xa0, 0xca, 0x10, 0x67, 0x35, 0x45, 0x70, 0xd9, 0x9a, 0x29, 0xb0, 0xdf, 0x61, 0x1a, 0xfa,
	0xd4, 0x02, 0xa1, 0xc0, 0x08, 0x17, 0xa1, 0x4f, 0xd1, 0x3a, 0xd4, 0x92, 0x74, 0xc4, 0x6e, 0x69,
	0x71, 0x8e, 0x99, 0xa4, 0xa3, 0x81, 0x87, 0xb6, 0xa0, 0xe2, 0xc6, 0xb1, 0xd5, 0xe6, 0x26, 0xaf,
	0xec, 0xe8, 0x18, 0xdf, 0xe9, 0xc7, 0xb1, 0xc3, 0xb8, 0x2c, 0xc2, 0xe3, 0x89, 0x4b, 0xe8, 0x30,
	0x74, 0x03, 0x6c, 0x2d, 0x89, 0x08, 0x73, 0xca, 0xa9, 0x1b, 0x60, 0xf4, 0x00, 0x3a, 0x82, 0xed,
	0x8f, 0xa3, 0x70, 0x98, 0x92, 0xa9, 0xd5, 0xe1, 0x22, 0x6d, 0x4e, 0x1d, 0x8c, 0xa3, 0xf0, 0x82,
	0x4c, 0xd1, 0x16, 0x2c, 0x8d, 0xdc, 0xa9, 0x1b, 0x8e, 0xf1, 0x90, 0x46, 0xaf, 0x71, 0xc8, 0x71,
	0xd9, 0x74, 0xda, 0x92, 0x78, 0xce, 0x68, 0xe8, 0x1e, 0xb4, 0x94, 0x50, 0x9a, 0x78, 0xd6, 0x32,
	0x17, 0x01, 0x49, 0xba, 0x48, 0x3c, 0xf4, 0x19, 0xac, 0x69, 0x02, 0xc3, 0x88, 0xf8, 0x97, 0x7e,
	0xe8, 0x4e, 0xad, 0x2e, 0x97, 0x44, 0xb9, 0xe4, 0x73, 0xc9, 0x41, 0x5f, 0xc0, 0x46, 0xe1, 0xde,
	0x5c, 0x67, 0x85, 0xeb, 0xac, 0xe9, 0x06, 0x64, 0x5a, 0x0a, 0xbc, 0x48, 0x4b, 0x36, 0x3d, 0xa9,
	0x56, 0x4b, 0x49, 0x75, 0x1f, 0xda, 0x6a, 0xcd, 0x2d, 0x5f, 0xe3, 0x7a, 0x2d, 0x45, 0x63, 0xa6,
	0x3f, 0x84, 0x4e, 0x26, 0x22, 0x22, 0xb0, 0xce, 0x85, 0x96, 0x14, 0x95, 0x5b, 0x60, 0xff, 0x6a,
	0x42, 0xfb, 0x45, 0x3a, 0x4a, 0xc6, 0xc4, 0x8f, 0x39, 0x40, 0xca, 0x78, 0xbf, 0x0b, 0x0d, 0x81,
	0x77, 0xdf, 0x93, 0x68, 0xaf, 0xf3, 0x7d, 0x19, 0x32, 0x95, 0x12, 0x64, 0x34, 0xa0, 0x55, 0x0b,
	0x40, 0xdb, 0xce, 0x32, 0xc4, 0xe4, 0x19, 0xd2, 0x15, 0x19, 0x72, 0x36, 0x75, 0xc3, 0x7f, 0x4a,
	0x90, 0xda, 0x07, 0x27, 0x48, 0xfd, 0x5f, 0x25, 0x88, 0x82, 0x7a, 0xe3, 0x3a, 0xa8, 0x37, 0x4b,
	0x50, 0x2f, 0xc2, 0x15, 0x6e, 0x86, 0x6b, 0x6b, 0x0e, 0x5c, 0x8b, 0x55, 0xa5, 0x5d, 0xae, 0x2a,
	0xd7, 0xe1, 0x70, 0xe9, 0x03, 0x70, 0xd8, 0xb9, 0x05, 0x0e, 0x97, 0xaf, 0xc1, 0x61, 0xf7, 0x06,
	0x1c, 0xae, 0xdc, 0x06, 0x87, 0x68, 0x1e, 0x0e, 0xdf, 0x57, 0xa0, 0x71, 0xa6, 0xb0, 0x53, 0x00,
	0x96, 0x51, 0x02, 0x16, 0x8b, 0x77, 0x9c, 0x0e, 0x65, 0x63, 0x93, 0x05, 0x78, 0x1c, 0xa7, 0xa7,
	0xa2, 0xb7, 0x6d, 0xc1, 0x52, 0x80, 0x83, 0x88, 0xcc, 0x94, 0x84, 0x4c, 0x7c, 0x41, 0x94, 0x42,
	0x0f, 0xa1, 0x93, 0xd0, 0x88, 0xb8, 0x97, 0x58, 0x49, 0x09, 0x8c, 0x2e, 0x49, 0xaa, 0x14, 0x5b,
	0x03, 0x33, 0x26, 0xfe, 0x18, 0x73, 0xa4, 0x36, 0x1d, 0xb1, 0x61, 0x06, 0xf0, 0xc5, 0xf0, 0x1d,
	0xc6, 0xaf, 0x39, 0x2e, 0x9b, 0x4e, 0x93, 0x53, 0x5e, 0x62, 0xfc, 0x9a, 0x15, 0x15, 0xc1, 0x0e,
	0xa2, 0x90, 0x4e, 0x64, 0x95, 0x15, 0x1a, 0xcf, 0x18, 0x25, 0xd7, 0x9f, 0x44, 0x29, 0x91, 0x38,
	0x13, 0xfa, 0x27, 0x51, 0x4a, 0x38, 0x9b, 0x3b, 0xef, 0xd3, 0xa9, 0xaa, 0xb8, 0x3c, 0x1c, 0xe7,
	0x8c, 0xc0, 0xf2, 0x91, 0xb3, 0x13, 0xac, 0xaa, 0x6e, 0x9d, 0xed, 0x5f, 0x60, 0xca, 0x6f, 0xe6,
	0x2c, 0x91, 0x5e, 0x2d, 0x79, 0x73, 0x96, 0x58, 0x2c, 0x36, 0x5c, 0xe0, 0x15, 0x76, 0x69, 0x4a,
	0xb0, 0xc7, 0x81, 0xd6, 0x70, 0xda, 0x8c, 0x78, 0x2c, 0x69, 0xf6, 0x23, 0x58, 0xfe, 0xde, 0x4f,
	0x28, 0x2b, 0x0a, 0xaa, 0xb7, 0x6a, 0xb9, 0x6c, 0xe8, 0xb9, 0x6c, 0x3f, 0x85, 0x6e, 0x2e, 0x2b,
	0xdb, 0xeb, 0x47, 0x50, 0x4d, 0xd2, 0x91, 0x6a, 0xdf, 0x48, 0x64, 0xb7, 0x5e, 0x62, 0x1c, 0xce,
	0xb7, 0xf7, 0x85, 0x2e, 0x7b, 0xf4, 0x4c, 0xf7, 0x01, 0x98, 0xcc, 0x16, 0xa5, 0xdc, 0xc9, 0x4b,
	0x03, 0x7b, 0x7a, 0x47, 0x30, 0xed, 0x3f, 0x0c, 0x58, 0x39, 0x88, 0xa6, 0x53, 0x3c, 0xa6, 0xc7,
	0x38, 0x1b, 0x00, 0x8a, 0xb8, 0x30, 0x6e, 0xc4, 0xc5, 0xe2, 0xad, 0x70, 0x51, 0x99, 0x87, 0x0b,
	0x55, 0x23, 0xaa, 0xd7, 0xd5, 0x08, 0xb3, 0x54, 0x23, 0x54, 0x5e, 0xd5, 0xb4, 0xe1, 0xe4, 0x17,
	0x03, 0x3a, 0x67, 0x3c, 0xf0, 0xfa, 0x0c, 0xc3, 0x3c, 0x54, 0x33, 0x0c, 0x5b, 0x67, 0x77, 0x2d,
	0x6a, 0x77, 0x69, 0xef, 0x51, 0x29, 0x37, 0xf1, 0xdc, 0x88, 0xea, 0x35, 0x46, 0x98, 0x9a, 0x11,
	0xbf, 0x19, 0x80, 0xf4, 0x50, 0xca, 0x77, 0x98, 0x67, 0x48, 0x17, 0x2a, 0xaf, 0xb0, 0xb2, 0x83,
	0x2d, 0x59, 0x7a, 0xe8, 0xbd, 0x55, 0x6c, 0xe6, 0x24, 0x7c, 0x75, 0x4e, 0xc2, 0x17, 0x4a, 0x07,
	0x3b, 0xd7, 0x2c, 0x96, 0x8e, 0x63, 0x8c, 0xed, 0x3f, 0x0d, 0x58, 0x3e, 0xc5, 0xef, 0xf8, 0xec,
	0x74, 0x13, 0x14, 0x79, 0x9c, 0xf2, 0x89, 0x8c, 0xaf, 0x33, 0x37, 0x2a, 0x73, 0xe2, 0x79, 0xeb,
	0xb7, 0xdb, 0x82, 0x4a, 0x3f, 0x8e, 0x65, 0xff, 0x99, 0x37, 0xb3, 0xf4, 0xe5, 0xcc, 0x32, 0x4d,
	0x13, 0x2a, 0xfa, 0x64, 0x5d, 0x82, 0x4f, 0x50, 0x84, 0x71, 0x3c, 0xf4, 0x0d, 0x2d, 0xf4, 0xcf,
	0xa0, 0x9b, 0x3b, 0x27, 0xe3, 0xae, 0x37, 0x5b, 0xa3, 0xd8, 0x6c, 0xff, 0x5f, 0xe8, 0x69, 0xcc,
	0xcb, 0x8a, 0xde, 0xb7, 0xec, 0xfb, 0x50, 0x3b, 0x67, 0x91, 0x38, 0xbc, 0x3e, 0x5b, 0xf7, 0x61,
	0x55, 0x9f, 0x43, 0xd5, 0xa5, 0xf7, 0xc1, 0xe4, 0x97, 0xc8, 0x71, 0xb8, 0xa5, 0x4d, 0xac, 0x8e,
	0xe0, 0xd8, 0xef, 0x0d, 0x58, 0x7e, 0xe9, 0xd3, 0x89, 0x47, 0xdc, 0x77, 0xea, 0x25, 0xba, 0x50,
	0x49, 0xb3, 0x2b, 0xd8, 0x92, 0xa5, 0xd8, 0x38, 0x25, 0x04, 0x87, 0xe3, 0x99, 0x3e, 0x1d, 0xb7,
	0x15, 0x91, 0x97, 0xef, 0x0d, 0xa8, 0xb9, 0x41, 0xf6, 0xa5, 0xd0, 0x74, 0xe4, 0x8e, 0xc1, 0x86,
	0xba, 0xe4, 0x12, 0xd3, 0xa1, 0xeb, 0x79, 0x04, 0x27, 0x89, 0x82, 0x8d, 0xa0, 0xf6, 0x05, 0xd1,
	0xfe, 0x19, 0xba, 0xb9, 0x21, 0xd2, 0x81, 0x75, 0x36, 0xd0, 0xbf, 0xc9, 0xfd, 0x35, 0x09, 0x7e,
	0xa3, 0x05, 0x7d, 0x91, 0x7f, 0xfb, 0x88, 0x66, 0xd6, 0x85, 0x4a, 0x90, 0x5c, 0xca, 0xab, 0xd9,
	0x12, 0x7d, 0x0a, 0x2b, 0x94, 0xb8, 0x61, 0xe2, 0x86, 0x63, 0x16, 0xc7, 0xe1, 0xc4, 0x4d, 0x26,
	0xf2, 0xea, 0xae, 0xce, 0x38, 0x71, 0x93, 0x89, 0xfd, 0x1d, 0x6c, 0x9c, 0xb9, 0xb3, 0x00, 0x87,
	0xf4, 0xc4, 0x67, 0x25, 0x61, 0x96, 0xd9, 0xf0, 0x18, 0x1a, 0xb1, 0xe0, 0xa8, 0xe2, 0xb5, 0x5e,
	0x84, 0x8a, 0xd4, 0x73, 0x32, 0xb1, 0x47, 0x5f, 0x43, 0x4b, 0x7b, 0x0e, 0xd4, 0x01, 0x38, 0x78,
	0x7e, 0x7a, 0x3c, 0x70, 0x9e, 0x0d, 0x4e, 0xbf, 0xed, 0x2e, 0xa0, 0x25, 0x68, 0xca, 0xfd, 0xd1,
	0x61, 0xd7, 0x40, 0xcb, 0xd0, 0x3a, 0x3c, 0xea, 0x1f, 0x9c, 0x0f, 0x7e, 0xe8, 0x9f, 0x1f, 0x1d,
	0x76, 0x17, 0x1f, 0xed, 0x02, 0xe4, 0x33, 0x13, 0x02, 0xa8, 0x5d, 0x9c, 0x9e, 0xf5, 0x07, 0x87,
	0xdd, 0x05, 0xd4, 0x80, 0x2a, 0x5f, 0x19, 0xa8, 0x05, 0xf5, 0xa3, 0x1f, 0xcf, 0x9c, 0x01, 0x53,
	0xd8, 0xfb, 0xdd, 0x84, 0xea, 0x99, 0x3b, 0x23, 0xa8, 0x0f, 0x90, 0xe7, 0x3c, 0xba, 0xa3, 0x3e,
	0x7f, 0x4a, 0x05, 0xb5, 0x67, 0x5d, 0x65, 0x08, 0x67, 0xed, 0x05, 0xf4, 0x15, 0xd4, 0x65, 0xed,
	0x42, 0x6b, 0x79, 0x91, 0xbe, 0xb5, 0x72, 0x43, 0x21, 0x1f, 0xad, 0x0b, 0xb9, 0x52, 0x9a, 0xf7,
	0x36, 0xca, 0xe4, 0x4c, 0x79, 0xbf, 0x18, 0xb5, 0xb6, 0x10, 0x14, 0xd0, 0xef, 0xdd, 0xbd, 0xfa,
	0xb5, 0x95, 0x6b, 0xee, 0x41, 0xeb, 0x80, 0x8d, 0x3c, 0x53, 0x71, 0x73, 0x51, 0x73, 0xb5, 0xf8,
	0x5a, 0x47, 0x41, 0x4c, 0x67, 0xf6, 0x02, 0xfa, 0x12, 0x1a, 0xaa, 0x49, 0xa1, 0x79, 0x22, 0xca,
	0xd0, 0x72, 0x27, 0x13, 0x5e, 0xaa, 0xde, 0xa8, 0xbc, 0x2c, 0xf5, 0x55, 0x5d, 0x59, 0x6f, 0xa1,
	0x42, 0x59, 0xc1, 0x5c, 0x29, 0x97, 0xf2, 0x4f, 0x29, 0x97, 0xb3, 0xc1, 0x5e, 0x40, 0xdf, 0x40,
	0xa7, 0x88, 0xd2, 0x92, 0xaf, 0xff, 0x95, 0x2f, 0x36, 0x17, 0xc9, 0xf6, 0x02, 0x3a, 0x84, 0x96,
	0xf6, 0x61, 0x8e, 0xe4, 0x53, 0x5e, 0xfd, 0x7f, 0x41, 0x85, 0x7b, 0xce, 0x57, 0xbc, 0xbd, 0xc0,
	0x50, 0x96, 0x7f, 0x7c, 0x2b, 0x94, 0x5d, 0xf9, 0x6e, 0xef, 0x59, 0x57, 0x19, 0xea, 0x88, 0x51,
	0x8d, 0x47, 0xfa, 0xf3, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xed, 0x1c, 0x8c, 0x34, 0x11,
	0x00, 0x00,
}
