// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify/v1/accountbalance.proto

package notify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountBalanceChangeEvent struct {
	FromAccountAddress   string       `protobuf:"bytes,1,opt,name=fromAccountAddress,proto3" json:"fromAccountAddress,omitempty"`
	ToAccountAddress     string       `protobuf:"bytes,2,opt,name=toAccountAddress,proto3" json:"toAccountAddress,omitempty"`
	Balance              string       `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	TxHash               string       `protobuf:"bytes,4,opt,name=txHash,proto3" json:"txHash,omitempty"`
	AccountsType         AccountsType `protobuf:"varint,5,opt,name=AccountsType,proto3,enum=notify.AccountsType" json:"AccountsType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AccountBalanceChangeEvent) Reset()         { *m = AccountBalanceChangeEvent{} }
func (m *AccountBalanceChangeEvent) String() string { return proto.CompactTextString(m) }
func (*AccountBalanceChangeEvent) ProtoMessage()    {}
func (*AccountBalanceChangeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e88a97aae8b980, []int{0}
}

func (m *AccountBalanceChangeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalanceChangeEvent.Unmarshal(m, b)
}
func (m *AccountBalanceChangeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalanceChangeEvent.Marshal(b, m, deterministic)
}
func (m *AccountBalanceChangeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalanceChangeEvent.Merge(m, src)
}
func (m *AccountBalanceChangeEvent) XXX_Size() int {
	return xxx_messageInfo_AccountBalanceChangeEvent.Size(m)
}
func (m *AccountBalanceChangeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalanceChangeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalanceChangeEvent proto.InternalMessageInfo

func (m *AccountBalanceChangeEvent) GetFromAccountAddress() string {
	if m != nil {
		return m.FromAccountAddress
	}
	return ""
}

func (m *AccountBalanceChangeEvent) GetToAccountAddress() string {
	if m != nil {
		return m.ToAccountAddress
	}
	return ""
}

func (m *AccountBalanceChangeEvent) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *AccountBalanceChangeEvent) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *AccountBalanceChangeEvent) GetAccountsType() AccountsType {
	if m != nil {
		return m.AccountsType
	}
	return AccountsType_AccountsUnknown
}

func init() {
	proto.RegisterType((*AccountBalanceChangeEvent)(nil), "notify.AccountBalanceChangeEvent")
}

func init() { proto.RegisterFile("notify/v1/accountbalance.proto", fileDescriptor_e5e88a97aae8b980) }

var fileDescriptor_e5e88a97aae8b980 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0xcb, 0x2f, 0xc9,
	0x4c, 0xab, 0xd4, 0x2f, 0x33, 0xd4, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x49, 0x4a, 0xcc,
	0x49, 0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xc8, 0x4b, 0x89,
	0x21, 0xd4, 0x25, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0x41, 0xe4, 0x95, 0x1e, 0x33, 0x72, 0x49, 0x3a,
	0x42, 0x34, 0x3a, 0x41, 0x34, 0x3a, 0x67, 0x24, 0xe6, 0xa5, 0xa7, 0xba, 0x96, 0xa5, 0xe6, 0x95,
	0x08, 0xe9, 0x71, 0x09, 0xa5, 0x15, 0xe5, 0xe7, 0x42, 0x15, 0x38, 0xa6, 0xa4, 0x14, 0xa5, 0x16,
	0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x61, 0x91, 0x11, 0xd2, 0xe2, 0x12, 0x28, 0xc9,
	0x47, 0x53, 0xcd, 0x04, 0x56, 0x8d, 0x21, 0x2e, 0x24, 0xc1, 0xc5, 0x0e, 0x75, 0xaa, 0x04, 0x33,
	0x58, 0x09, 0x8c, 0x2b, 0x24, 0xc6, 0xc5, 0x56, 0x52, 0xe1, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0x02,
	0x96, 0x80, 0xf2, 0x84, 0x2c, 0xb8, 0x78, 0xa0, 0x66, 0x14, 0x87, 0x54, 0x16, 0xa4, 0x4a, 0xb0,
	0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x89, 0xe8, 0x41, 0xbc, 0xa6, 0x87, 0x2c, 0x17, 0x84, 0xa2, 0x32,
	0x89, 0x0d, 0xec, 0x59, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x36, 0x17, 0x2e, 0x2e,
	0x01, 0x00, 0x00,
}
